Repository sparcs-kaist/clubs, pull requests merged in 2024-07, with the labels that each got.

#329 impl my page service pages
  packages/web/src/app/my/activity-certificate/[id]/page.tsx
  packages/web/src/app/my/activity-certificate/page.tsx
  packages/web/src/app/my/common-space/[id]/page.tsx
  packages/web/src/app/my/common-space/page.tsx
  packages/web/src/app/my/printing-business/[id]/page.tsx
  packages/web/src/app/my/printing-business/page.tsx
  packages/web/src/app/my/rental-business/[id]/page.tsx
  packages/web/src/app/my/rental-business/page.tsx
  packages/web/src/common/components/Pagination.tsx
  packages/web/src/common/components/Table/TableCell.tsx
  packages/web/src/constants/tableTagList.ts
  packages/web/src/features/manage-club/component/ActivityCertificateTable.tsx
  packages/web/src/features/manage-club/component/ActivityReportTable.tsx
  packages/web/src/features/manage-club/component/CommonSpaceTable.tsx
  packages/web/src/features/manage-club/component/FundingTable.tsx
  packages/web/src/features/manage-club/component/MembersTable.tsx
  packages/web/src/features/manage-club/component/PrintingTable.tsx
  packages/web/src/features/manage-club/component/RentalTable.tsx
  packages/web/src/features/my/activity-certificate/frame/MyCertificateDetailFrame.tsx
  packages/web/src/features/my/common-space/frame/MyCommonSpaceDetailFrame.tsx
  packages/web/src/features/my/component/MyActivityCertificateTable.tsx
  packages/web/src/features/my/component/MyCommonSpaceTable.tsx
  packages/web/src/features/my/component/MyPrintingTable.tsx
  packages/web/src/features/my/component/MyRentalTable.tsx
  packages/web/src/features/my/component/MyServiceTable.tsx
  packages/web/src/features/my/printing-business/frame/MyPrintingDetailFrame.tsx
  packages/web/src/features/my/rental-business/frame/MyRentalDetailFrame.tsx
Labels: enhancement, front-end

#326 309 impl rnt004 rnt006 interface
  packages/interface/src/api/rental/endpoint/apiRnt004.ts
  packages/interface/src/api/rental/endpoint/apiRnt006.ts
  packages/interface/src/api/rental/index.ts
Labels: enhancement, interface

#332 Auth 모듈 구현
  .env.example
  packages/api/package.json
  packages/api/src/app.module.ts
  packages/api/src/feature/auth/auth.exception.ts
  packages/api/src/feature/auth/auth.module.ts
  packages/api/src/feature/auth/controller/auth.controller.ts
  packages/api/src/feature/auth/dto/auth.dto.ts
  packages/api/src/feature/auth/repository/auth.repository.ts
  packages/api/src/feature/auth/service/auth.service.ts
  packages/api/src/feature/auth/strategy/jwt-access.strategy.ts
  packages/api/src/feature/auth/strategy/jwt-refresh.strategy.ts
  packages/api/src/main.ts
  pnpm-lock.yaml
Labels: back-end

#323 feat: implement PRT-003
  packages/api/src/common/repository/club.repository.ts
  packages/api/src/feature/club/repository/club.club-representative-d.repository.ts
  packages/api/src/feature/promotional-printing/controller/promotional-printing.controller.ts
  packages/api/src/feature/promotional-printing/promotional-printing.module.ts
  packages/api/src/feature/promotional-printing/repository/promotional-printing-order.repository.ts
  packages/api/src/feature/promotional-printing/service/promotional-printing.service.ts
  packages/interface/src/api/promotional-printing/endpoint/apiPrt003.ts
  packages/interface/src/api/promotional-printing/index.ts
Labels: enhancement, back-end, interface

#318 Separate local db setting commands
  README.md
Labels: enhancement, back-end, interface

#340 refactor getPrintSize
  packages/web/src/app/my/printing-business/page.tsx
  packages/web/src/features/manage-club/component/PrintingTable.tsx
  packages/web/src/features/my/component/MyPrintingTable.tsx
  packages/web/src/utils/getPrintSize.ts
Labels: front-end

#345 Remove studentT repository injection from common to club module
  packages/api/src/feature/club/club.module.ts
  packages/api/src/feature/club/repository/club.club-student-t.repository.ts
  packages/api/src/feature/club/repository/club.semester-d.repository.ts
  packages/api/src/feature/club/service/club.public.service.ts
  packages/api/src/feature/club/service/club.service.ts
  packages/api/src/feature/common-space/common-space.module.ts
  packages/api/src/feature/common-space/service/common-space.service.ts
  packages/api/src/feature/user/service/user.service.ts
  packages/api/src/feature/user/user.module.ts
Labels: back-end

#341 add responsive design to clubs page
  packages/web/src/app/clubs/page.tsx
  packages/web/src/features/clubs/components/ClubListGrid.tsx
  packages/web/src/features/clubs/frames/ClubsPageMainFrame.tsx
Labels: front-end

#356 impl funding create frame
  packages/web/src/app/manage-club/funding/create/page.tsx
  packages/web/src/common/components/CheckboxOption.tsx
  packages/web/src/common/components/Forms/DateInput.tsx
  packages/web/src/common/components/Select/index.tsx
  packages/web/src/features/manage-club/funding/create/frame/AddEvidenceFrame.tsx
  packages/web/src/features/manage-club/funding/create/frame/BasicEvidenceFrame.tsx
  packages/web/src/features/manage-club/funding/create/frame/FundingInfoFrame.tsx
  packages/web/src/utils/Date/formateDate.ts
Labels: enhancement, front-end

#349 table component refactoring
  packages/web/src/app/my/activity-certificate/page.tsx
  packages/web/src/app/my/common-space/page.tsx
  packages/web/src/app/my/printing-business/page.tsx
  packages/web/src/app/my/rental-business/page.tsx
  packages/web/src/features/my/component/MyServiceTable.tsx
Labels: enhancement, front-end

#358 impl evidence block for create funding
  packages/web/src/features/manage-club/funding/create/components/EvidenceBlockTitle.tsx
  packages/web/src/features/manage-club/funding/create/components/OtherEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/create/frame/AddEvidenceFrame.tsx
  packages/web/src/features/manage-club/funding/create/frame/BasicEvidenceFrame.tsx
  packages/web/src/features/manage-club/funding/create/frame/FundingInfoFrame.tsx
Labels: enhancement, front-end

#346 feat: impl clb004-clb005
  packages/api/src/common/repository/club.club-t.respository.ts
  packages/api/src/feature/club/club.module.ts
  packages/api/src/feature/club/controller/club.controller.ts
  packages/api/src/feature/club/repository/club.club-representative-d.repository.ts
  packages/api/src/feature/club/repository/club.get-student-club-brief.ts
  packages/api/src/feature/club/repository/club.put-student-club-brief.ts
  packages/api/src/feature/club/service/club.service.ts
  packages/interface/src/api/club/endpoint/apiClb004.ts
  packages/interface/src/api/club/endpoint/apiClb005.ts
Labels: back-end

#350 impl progressStatus
  packages/web/src/common/components/ProgressCheckSection/index.tsx
  packages/web/src/common/components/ProgressStatus.tsx
  packages/web/src/features/manage-club/activity-certificate/frame/ManageCertificateDetailFrame.tsx
  packages/web/src/features/manage-club/common-space/frame/ManageCommonSpaceDetailFrame.tsx
  packages/web/src/features/manage-club/printing/frame/ManagePrintingDetailFrame.tsx
  packages/web/src/features/manage-club/rental/frame/ManageRentalDetailFrame.tsx
  packages/web/src/features/my/activity-certificate/frame/MyCertificateDetailFrame.tsx
  packages/web/src/features/my/common-space/frame/MyCommonSpaceDetailFrame.tsx
  packages/web/src/features/my/printing-business/frame/MyPrintingDetailFrame.tsx
  packages/web/src/features/my/rental-business/frame/MyRentalDetailFrame.tsx
Labels: enhancement, front-end

#360 impl fixture evidence block
  packages/web/src/common/components/FileUpload.tsx
  packages/web/src/common/components/Select/index.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportCreateFrame.tsx
  packages/web/src/features/manage-club/funding/create/components/FixtureEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/create/components/OtherEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/create/frame/AddEvidenceFrame.tsx
  packages/web/src/features/manage-club/funding/create/frame/BasicEvidenceFrame.tsx
  packages/web/src/features/manage-club/funding/create/frame/FundingInfoFrame.tsx
Labels: enhancement, front-end

#343 fix: move pagehead component into flexWrapper component
  packages/web/src/app/manage-club/activity-certificate/page.tsx
  packages/web/src/app/manage-club/common-space/page.tsx
  packages/web/src/app/manage-club/funding/page.tsx
  packages/web/src/app/manage-club/printing-business/page.tsx
  packages/web/src/app/manage-club/rental-business/page.tsx
  packages/web/src/features/manage-club/funding/frame/ManageClubFundingMainFrame.tsx
  packages/web/src/features/manageClubTable/frames/ManageClubTableMainFrame.tsx
Labels: front-end

#364 impl transportation evidence block
  packages/web/src/features/manage-club/funding/create/components/NonCorpEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/create/components/TransportEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/create/frame/AddEvidenceFrame.tsx
Labels: enhancement, front-end

#359 320 modal refactoring
  packages/web/package.json
  packages/web/src/common/components/Modal/ModalExample.tsx
  packages/web/src/common/components/Modal/index.tsx
  packages/web/src/common/providers/UseClientProvider.tsx
  packages/web/src/features/rental-business/components/SelectRangeCalendar/SelectRangeCalendar.tsx
  packages/web/src/features/rental-business/components/SelectRangeCalendar/_atomic/RangeCalendar.tsx
  packages/web/src/features/rental-business/components/SelectRangeCalendar/_atomic/SelectRange.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoSecondFrame.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/index.tsx
  pnpm-lock.yaml
Labels: front-end

#258 233 common space connect backend
  packages/web/src/common/components/Timetable/_atomic/TimetableDateList.tsx
  packages/web/src/common/components/Timetable/_atomic/TimetableTable.tsx
  packages/web/src/common/components/Timetable/index.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoFirstFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoSecondFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoThirdFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/index.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/mockCommonSpaceList.ts
  packages/web/src/features/common-space/frames/CommonSpaceMainFrame.tsx
  packages/web/src/features/common-space/service/_mock/mockupCommonSpaceUsageOrders.ts
  packages/web/src/features/common-space/service/_mock/mockupCommonSpaces.ts
  packages/web/src/features/common-space/service/_mock/mockupUserProfile.ts
  packages/web/src/features/common-space/service/getCommonSpaceUsageOrders.ts
  packages/web/src/features/common-space/service/getCommonSpaces.ts
  packages/web/src/features/common-space/service/getUserProfile.ts
  packages/web/src/features/common-space/service/postCommonSpaceUsageOrder.ts
  packages/web/src/features/common-space/types/commonSpace.ts
  packages/web/src/utils/Date/formateDate.ts
Labels: front-end

#384 feat: add link to credits page
  packages/web/src/constants/paths.ts
Labels: enhancement, front-end

#382 feat: credit for daystar
  packages/web/src/features/credits/credits.ts
Labels: enhancement, front-end

#385 impl register club subpage components
  packages/web/src/features/register-club/components/RulesButton.tsx
  packages/web/src/features/register-club/components/SingleUploadWithTextAndTemplate.tsx
Labels: front-end

#386 impl additional UI for changing representative delegate
  packages/web/src/constants/changeRepresentative.ts
  packages/web/src/features/manage-club/component/ChangeRepresentative.tsx
  packages/web/src/features/manage-club/component/ChangeRepresentativeCard.tsx
  packages/web/src/features/manage-club/frame/_atomic/InfoManageFrame.tsx
  packages/web/src/features/my/component/ChangeRepresentativeModalContent.tsx
  packages/web/src/features/my/component/MyChangeRepresentative.tsx
  packages/web/src/styles/themes/colors.ts
Labels: enhancement, front-end

#390 impl fnd 004-006 interface
  packages/interface/src/api/funding/endpoint/apiFnd004.ts
  packages/interface/src/api/funding/endpoint/apiFnd005.ts
  packages/interface/src/api/funding/endpoint/apiFnd006.ts
  packages/interface/src/api/funding/index.ts
  packages/interface/src/common/enum/funding.enum.ts
Labels: enhancement, interface

#394 fix import for rental
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoSecondFrame.tsx
Labels: front-end

#387 feat: chacha's credit
  packages/web/src/features/credits/credits.ts
Labels: enhancement, good first issue, front-end

#395 impl fnd 001 002 003 interface
  packages/interface/src/api/funding/endpoint/apiFnd001.ts
  packages/interface/src/api/funding/endpoint/apiFnd002.ts
  packages/interface/src/api/funding/endpoint/apiFnd003.ts
  packages/interface/src/api/funding/index.ts
  packages/interface/src/common/enum/funding.enum.ts
Labels: enhancement, interface

#355 335 impl rnt004 rnt006 api
  packages/api/src/drizzle/schema/rental.schema.ts
  packages/api/src/feature/club/service/club.service.ts
  packages/api/src/feature/rental/controller/rental.controller.ts
  packages/api/src/feature/rental/rental.module.ts
  packages/api/src/feature/rental/repository/rental.rental-object.repository.ts
  packages/api/src/feature/rental/repository/rental.rental-order.repository.ts
  packages/api/src/feature/rental/repository/rental.rental-service.repository.ts
  packages/api/src/feature/rental/service/rental.service.ts
  packages/interface/src/api/rental/endpoint/apiRnt002.ts
  packages/interface/src/api/rental/endpoint/apiRnt003.ts
  packages/interface/src/api/rental/endpoint/apiRnt004.ts
  packages/interface/src/common/enum/rental.enum.ts
  packages/web/src/constants/tableTagList.ts
  packages/web/src/features/manage-club/component/MoreDetailTitle.tsx
Labels: back-end

#363 Impl file upload
  .env.example
  packages/api/package.json
  packages/api/src/app.module.ts
  packages/api/src/drizzle/schema/file.schema.ts
  packages/api/src/feature/file/controller/file.controller.ts
  packages/api/src/feature/file/file.exception.ts
  packages/api/src/feature/file/file.module.ts
  packages/api/src/feature/file/repository/file.repository.ts
  packages/api/src/feature/file/service/file.service.ts
  packages/api/src/main.ts
  packages/interface/src/api/file/endpoint/apiFil001.ts
  packages/interface/src/api/file/index.ts
  pnpm-lock.yaml
Labels: back-end

#404 Implement ACF-003 and ACF-007 API
  packages/api/src/feature/activity-certificate/activity-certificate.module.ts
  packages/api/src/feature/activity-certificate/controller/activity-certificate.controller.ts
  packages/api/src/feature/activity-certificate/repository/activity-certificate.repository.ts
  packages/api/src/feature/activity-certificate/service/activity-certificate.service.ts
  packages/interface/src/api/activity-certificate/endpoint/apiAcf003.ts
  packages/interface/src/api/activity-certificate/endpoint/apiAcf007.ts
  packages/interface/src/api/activity-certificate/index.ts
Labels: enhancement, back-end, interface

#409 Add credit (malloc)
  packages/web/src/features/credits/credits.ts
Labels: enhancement, good first issue, front-end

#398 fix background gradient uniform
  packages/web/src/styles/globals.css
Labels: enhancement, good first issue, front-end

#388 feat: add credit(ryan)
  packages/web/src/features/credits/credits.ts
Labels: enhancement, good first issue, front-end

#411 369 impl auth moudle interface and detail
  packages/api/src/feature/auth/controller/auth.controller.ts
  packages/api/src/feature/auth/repository/auth.repository.ts
  packages/api/src/feature/auth/service/auth.service.ts
  packages/interface/src/api/auth/endpoint/apiAut001.ts
  packages/interface/src/api/auth/endpoint/apiAut002.ts
  packages/interface/src/api/auth/endpoint/apiAut003.ts
Labels: back-end

#410 mypage service connect backend
  packages/interface/src/api/promotional-printing/endpoint/apiPrt005.ts
  packages/web/src/app/my/page.tsx
  packages/web/src/common/components/Table/TableButtonCell.tsx
  packages/web/src/common/components/Table/TableCell.tsx
  packages/web/src/common/components/Table/TableWrapper.tsx
  packages/web/src/features/my/frame/MyClubFrame.tsx
  packages/web/src/features/my/frame/MyInfoFrame.tsx
  packages/web/src/features/my/frame/MyPageMainFrame.tsx
  packages/web/src/features/my/frame/MyServiceFrame.tsx
  packages/web/src/features/my/frame/_atomic/MyInfoFrame.tsx
  packages/web/src/features/my/frame/_atomic/MyServiceFrame.tsx
  packages/web/src/features/my/service/getMyActivityCertificate.ts
  packages/web/src/features/my/service/getMyCommonSpace.ts
  packages/web/src/features/my/service/getMyPrinting.ts
  packages/web/src/features/my/service/getMyRentals.ts
Labels: enhancement, front-end

#408 add credit (casio)
  packages/web/src/features/credits/credits.ts
Labels: enhancement, good first issue, front-end

#423 Move useGetUserProfile
  packages/web/src/common/services/_mock/mockupUserProfile.ts
  packages/web/src/common/services/getUserProfile.ts
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoFirstFrame.tsx
  packages/web/src/features/my/frame/MyInfoFrame.tsx
  packages/web/src/features/printing-business/frame/PrintingBusinessMainFrame.tsx
  packages/web/src/features/printing-business/service/_mock/mockupUserProfile.ts
  packages/web/src/features/printing-business/service/getUserProfile.ts
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoFirstFrame.tsx
Labels: front-end

#397 Implement REG-001, 002, 003 interface
  packages/interface/src/api/registration/apiReg001.ts
  packages/interface/src/api/registration/apiReg002.ts
  packages/interface/src/api/registration/apiReg003.ts
  packages/interface/src/common/commonString.ts
  packages/interface/src/common/enum/registration.enum.ts
  packages/interface/src/common/enum/user.enum.ts
Labels: enhancement, interface

#420 feat: init socket
  packages/api/package.json
  packages/api/src/app.module.ts
  packages/api/src/feature/socket/socket.gateway.spec.ts
  packages/api/src/feature/socket/socket.gateway.ts
  packages/api/src/feature/socket/socket.module.ts
  packages/api/src/feature/socket/socket.repository.ts
  packages/api/src/feature/socket/socket.service.ts
  packages/web/package.json
  pnpm-lock.yaml
Labels: enhancement, back-end

#425 impl manage club funding detail page
  packages/interface/src/api/funding/endpoint/apiFnd001.ts
  packages/interface/src/api/funding/endpoint/apiFnd002.ts
  packages/interface/src/api/funding/endpoint/apiFnd003.ts
  packages/web/src/app/manage-club/funding/[id]/page.tsx
  packages/web/src/common/components/FilePreview.tsx
  packages/web/src/features/manage-club/funding/detail/components/BasicEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/components/FixtureEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/components/FundingInfoList.tsx
  packages/web/src/features/manage-club/funding/detail/components/NonCorpEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/components/OtherEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/components/TransportationEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/frame/FundingDetailFrame.tsx
  packages/web/src/features/manage-club/funding/detail/frame/_atomic/fundingDetailModal.tsx
  packages/web/src/features/manage-club/service/_mock/mockFundingDetail.ts
  packages/web/src/utils/fundingEnumMap.ts
Labels: enhancement, front-end

#436 impl manage club edit funding page
  packages/web/src/app/manage-club/funding/[id]/edit/page.tsx
  packages/web/src/app/manage-club/funding/create/page.tsx
  packages/web/src/features/manage-club/funding/component/EvidenceBlockTitle.tsx
  packages/web/src/features/manage-club/funding/component/FixtureEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/component/NonCorpEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/component/OtherEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/component/TransportEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/frame/AddEvidenceFrame.tsx
  packages/web/src/features/manage-club/funding/frame/BasicEvidenceFrame.tsx
  packages/web/src/features/manage-club/funding/frame/FundingInfoFrame.tsx
  packages/web/src/features/manage-club/service/_mock/mockFundingDetail.ts
Labels: enhancement, front-end

#428 Impl /register-club ClubButton Component
  packages/web/src/app/register-club/page.tsx
  packages/web/src/features/register-club/components/ClubButton.tsx
Labels: enhancement, good first issue, front-end

#383 add credits
  packages/web/src/features/credits/components/MemberCardSection.tsx
  packages/web/src/features/credits/credits.ts
  packages/web/src/features/credits/frames/CreditsMainFrame.tsx
Labels: front-end

#440 modify funding pages
  packages/web/src/app/manage-club/funding/[id]/edit/page.tsx
  packages/web/src/app/manage-club/funding/[id]/page.tsx
  packages/web/src/app/manage-club/funding/create/page.tsx
  packages/web/src/app/manage-club/funding/page.tsx
  packages/web/src/features/manage-club/funding/component/NewFundingListSection.tsx
  packages/web/src/features/manage-club/funding/components/EvidenceBlockTitle.tsx
  packages/web/src/features/manage-club/funding/components/FixtureEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/components/NewFundingListSection.tsx
  packages/web/src/features/manage-club/funding/components/NonCorpEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/components/OtherEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/components/PastFundingListSection.tsx
  packages/web/src/features/manage-club/funding/components/TransportEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/components/_atomic/NewFundingListTable.tsx
  packages/web/src/features/manage-club/funding/components/_atomic/PastFundingListTable.tsx
  packages/web/src/features/manage-club/funding/components/_atomic/PastSingleSemesterFundingListSection.tsx
  packages/web/src/features/manage-club/funding/detail/frame/_atomic/fundingDetailModal.tsx
  packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
  packages/web/src/features/manage-club/funding/frame/ManageClubFundingMainFrame.tsx
  packages/web/src/features/manage-club/funding/frames/AddEvidenceFrame.tsx
  packages/web/src/features/manage-club/funding/frames/BasicEvidenceFrame.tsx
  packages/web/src/features/manage-club/funding/frames/FundingInfoFrame.tsx
  packages/web/src/features/manage-club/funding/types/funding.ts
Labels: enhancement, front-end

#445 #412: Add "Overdue" process state tag for rental business
  packages/web/src/features/manageClubTable/types/ManageClubTable.ts
  packages/web/src/features/manageClubTable/types/ManageClubTableConst.ts
  packages/web/src/features/manageClubTable/types/mock.ts
Labels: enhancement, good first issue, front-end

#438 Iconbutton Refactoring
  packages/web/src/app/manage-club/funding/[id]/edit/page.tsx
  packages/web/src/app/manage-club/funding/create/page.tsx
  packages/web/src/common/components/Buttons/Button.tsx
  packages/web/src/common/components/Buttons/IconButton.tsx
  packages/web/src/common/components/Buttons/TextButton.tsx
  packages/web/src/common/components/Forms/IconButton.tsx
  packages/web/src/common/components/Modal/CancellableModalContent.tsx
  packages/web/src/common/components/Modal/ConfirmModalContent.tsx
  packages/web/src/common/components/Modal/ModalExample.tsx
  packages/web/src/common/components/MoreDetailTitle.tsx
  packages/web/src/common/components/MyMenu/index.tsx
  packages/web/src/common/components/NavTools/MobileNavMenu.tsx
  packages/web/src/common/components/Table/TableButton.tsx
  packages/web/src/common/components/Table/TableButtonCell.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoSecondFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/index.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateNoticeFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/index.tsx
  packages/web/src/features/common-space/frames/CommonSpaceNoticeFrame.tsx
  packages/web/src/features/credits/credits.ts
  packages/web/src/features/manage-club/activity-certificate/frame/ManageCertificateDetailFrame.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportCreateFrame.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportMainFrame.tsx
  packages/web/src/features/manage-club/common-space/frame/ManageCommonSpaceDetailFrame.tsx
  packages/web/src/features/manage-club/component/ChangeRepresentativeCard.tsx
  packages/web/src/features/manage-club/component/MoreDetailTitle.tsx
  packages/web/src/features/manage-club/frame/_atomic/InfoManageFrame.tsx
  packages/web/src/features/manage-club/funding/component/NewFundingListSection.tsx
  packages/web/src/features/manage-club/funding/components/NewFundingListSection.tsx
  packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
  packages/web/src/features/manage-club/members/components/MemberSearchAndFilter.tsx
  packages/web/src/features/manage-club/members/frames/AllMemberListFrame.tsx
  packages/web/src/features/manage-club/printing/frame/ManagePrintingDetailFrame.tsx
  packages/web/src/features/manage-club/rental/frame/ManageRentalDetailFrame.tsx
  packages/web/src/features/manage-club/service/_mock/mockFundingDetail.ts
  packages/web/src/features/my/activity-certificate/frame/MyCertificateDetailFrame.tsx
  packages/web/src/features/my/common-space/frame/MyCommonSpaceDetailFrame.tsx
  packages/web/src/features/my/component/ChangeRepresentativeModalContent.tsx
  packages/web/src/features/my/frame/MyInfoFrame.tsx
  packages/web/src/features/my/printing-business/frame/MyPrintingDetailFrame.tsx
  packages/web/src/features/my/rental-business/frame/MyRentalDetailFrame.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/index.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessNotice.tsx
  packages/web/src/features/register-club/components/RulesButton.tsx
  packages/web/src/features/register-club/components/SingleUploadWithTextAndTemplate.tsx
  packages/web/src/features/rental-business/components/SelectRangeCalendar/_atomic/SelectRange.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoSecondFrame.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/index.tsx
  packages/web/src/features/rental-business/frames/RentalNoticeFrame.tsx
Labels: enhancement, good first issue, front-end

#456 Update MainPageMainFrame.tsx
  packages/web/src/features/landing/frames/MainPageMainFrame.tsx
Labels: front-end

#446 Add advisory professor approval column
  packages/web/src/constants/tableTagList.ts
  packages/web/src/features/manage-club/activity-report/_mock/mock.ts
  packages/web/src/features/manage-club/activity-report/components/NewActivityReportList.tsx
  packages/web/src/features/manage-club/activity-report/types/activityReport.ts
  packages/web/src/features/manage-club/component/ActivityReportTable.tsx
  packages/web/src/features/manage-club/service/_mock/mockManageClub.ts
Labels: enhancement, good first issue, front-end

#453 Implement ACT-006, ACT-009
  packages/api/src/feature/activity/activity.module.ts
  packages/api/src/feature/activity/controller/activity.activity-term.controller.ts
  packages/api/src/feature/activity/repository/activity.activity-term.repository.ts
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/activity/service/activity.activity-term.service.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/api/src/feature/club/repository/club.semester-d.repository.ts
  packages/api/src/feature/club/service/club.public.service.ts
  packages/interface/src/api/activity/endpoint/apiAct006.ts
  packages/interface/src/api/activity/endpoint/apiAct009.ts
  packages/interface/src/api/activity/index.ts
Labels: enhancement, back-end, interface

#458 fix: move button
  packages/web/src/app/manage-club/funding/[id]/edit/page.tsx
  packages/web/src/app/manage-club/funding/create/page.tsx
  packages/web/src/common/components/Button.tsx
  packages/web/src/common/components/Modal/CancellableModalContent.tsx
  packages/web/src/common/components/Modal/ConfirmModalContent.tsx
  packages/web/src/common/components/Modal/ModalExample.tsx
  packages/web/src/common/components/MyMenu/index.tsx
  packages/web/src/common/components/NavTools/MobileNavMenu.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/index.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateNoticeFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/index.tsx
  packages/web/src/features/common-space/frames/CommonSpaceNoticeFrame.tsx
  packages/web/src/features/manage-club/activity-certificate/frame/ManageCertificateDetailFrame.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportCreateFrame.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportMainFrame.tsx
  packages/web/src/features/manage-club/common-space/frame/ManageCommonSpaceDetailFrame.tsx
  packages/web/src/features/manage-club/frame/_atomic/InfoManageFrame.tsx
  packages/web/src/features/manage-club/funding/component/NewFundingListSection.tsx
  packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
  packages/web/src/features/manage-club/printing/frame/ManagePrintingDetailFrame.tsx
  packages/web/src/features/manage-club/rental/frame/ManageRentalDetailFrame.tsx
  packages/web/src/features/my/activity-certificate/frame/MyCertificateDetailFrame.tsx
  packages/web/src/features/my/common-space/frame/MyCommonSpaceDetailFrame.tsx
  packages/web/src/features/my/component/ChangeRepresentativeModalContent.tsx
  packages/web/src/features/my/frame/MyInfoFrame.tsx
  packages/web/src/features/my/printing-business/frame/MyPrintingDetailFrame.tsx
  packages/web/src/features/my/rental-business/frame/MyRentalDetailFrame.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/index.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessNotice.tsx
  packages/web/src/features/register-club/components/RulesButton.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/index.tsx
  packages/web/src/features/rental-business/frames/RentalNoticeFrame.tsx
Labels: bug, front-end

#459 Implement funding tag & Add committe tag
  packages/web/src/constants/tableTagList.ts
  packages/web/src/features/manage-club/component/FundingTable.tsx
  packages/web/src/features/manage-club/funding/components/_atomic/NewFundingListTable.tsx
  packages/web/src/features/manage-club/funding/components/_atomic/PastFundingListTable.tsx
  packages/web/src/features/manage-club/funding/components/_atomic/PastSingleSemesterFundingListSection.tsx
  packages/web/src/features/manage-club/service/_mock/mockManageClub.ts
Labels: enhancement, good first issue, front-end

#426 Typography component refactoring
  packages/web/src/common/components/FoldableSection.tsx
  packages/web/src/common/components/Forms/DateRangeInput.tsx
  packages/web/src/common/components/Forms/IconButton.tsx
  packages/web/src/common/components/Info.tsx
  packages/web/src/common/components/PageHead/_atomic/BreadCrumbItem.tsx
  packages/web/src/common/components/Typography.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoThirdFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateNoticeFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoSecondFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoThirdFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceNoticeFrame.tsx
  packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessNotice.tsx
  packages/web/src/features/rental-business/components/ItemButton.tsx
  packages/web/src/features/rental-business/components/Rentals/Vacuum.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoSecondFrame.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoThirdFrame.tsx
  packages/web/src/features/rental-business/frames/RentalNoticeFrame.tsx
  packages/web/src/styles/globals.css
Labels: enhancement, front-end

#444 Edit feature/manage-club folder name
  packages/web/src/app/manage-club/page.tsx
  packages/web/src/features/manage-club/component/ManageFrameWrapper.tsx
  packages/web/src/features/manage-club/component/MoreDetailTitle.tsx
  packages/web/src/features/manage-club/components/ActivityCertificateTable.tsx
  packages/web/src/features/manage-club/components/ActivityReportTable.tsx
  packages/web/src/features/manage-club/components/ChangeRepresentative.tsx
  packages/web/src/features/manage-club/components/ChangeRepresentativeCard.tsx
  packages/web/src/features/manage-club/components/CommonSpaceTable.tsx
  packages/web/src/features/manage-club/components/FundingTable.tsx
  packages/web/src/features/manage-club/components/MembersTable.tsx
  packages/web/src/features/manage-club/components/PrintingTable.tsx
  packages/web/src/features/manage-club/components/RentalTable.tsx
  packages/web/src/features/manage-club/frame/ManageClubMainFrame.tsx
  packages/web/src/features/manage-club/frame/_atomic/ActivityManageFrame.tsx
  packages/web/src/features/manage-club/frame/_atomic/ServiceManageFrame.tsx
  packages/web/src/features/manage-club/frames/ActivityManageFrame.tsx
  packages/web/src/features/manage-club/frames/InfoManageFrame.tsx
  packages/web/src/features/manage-club/frames/MembersManageFrame.tsx
  packages/web/src/features/manage-club/frames/ServiceManageFrame.tsx
  packages/web/src/features/my/component/MyChangeRepresentative.tsx
Labels: enhancement, front-end

#421 415 impl auth detail
  packages/api/src/app.controller.ts
  packages/api/src/app.module.ts
  packages/api/src/common/repository/executive.repository.ts
  packages/api/src/common/util/decorators/method-decorator.ts
  packages/api/src/common/util/decorators/param-decorator.ts
  packages/api/src/drizzle/schema/refresh-token.schema.ts
  packages/api/src/drizzle/schema/user.schema.ts
  packages/api/src/feature/auth/auth.module.ts
  packages/api/src/feature/auth/controller/auth.controller.ts
  packages/api/src/feature/auth/guard/jwt-access.guard.ts
  packages/api/src/feature/auth/guard/jwt-refresh.guard.ts
  packages/api/src/feature/auth/repository/auth.repository.ts
  packages/api/src/feature/auth/service/auth.service.ts
  packages/api/src/feature/auth/strategy/jwt-access.strategy.ts
  packages/api/src/feature/auth/strategy/jwt-refresh.strategy.ts
  packages/api/src/feature/user/user.module.ts
Labels: back-end

#468 Fix gap in /manage-club page
  packages/web/src/features/manage-club/frames/ActivityManageFrame.tsx
  packages/web/src/features/manage-club/frames/MembersManageFrame.tsx
  packages/web/src/features/manage-club/frames/ServiceManageFrame.tsx
Labels: bug, good first issue, front-end

#465 Implement register button on club card
  packages/web/src/app/clubs/page.tsx
  packages/web/src/common/components/Buttons/TextButton.tsx
  packages/web/src/features/clubs/components/ClubCard.tsx
  packages/web/src/features/clubs/components/ClubListGrid.tsx
  packages/web/src/features/clubs/frames/ClubsPageMainFrame.tsx
  packages/web/src/features/clubs/frames/ClubsSectionFrame.tsx
Labels: enhancement, good first issue, front-end

#464 progressstatus for manage club
  packages/web/src/app/manage-club/activity-certificate/[id]/page.tsx
  packages/web/src/app/manage-club/common-space/[id]/page.tsx
  packages/web/src/app/manage-club/printing-business/[id]/page.tsx
  packages/web/src/app/manage-club/rental-business/[id]/page.tsx
  packages/web/src/common/components/ProgressCheckSection/ProgressCheckSectionWrapper.tsx
  packages/web/src/common/components/ProgressCheckSection/_atomic/Progress.tsx
  packages/web/src/common/components/ProgressCheckSection/index.tsx
  packages/web/src/common/components/ProgressStatus.tsx
  packages/web/src/common/components/RejectReasonToast.tsx
  packages/web/src/constants/manageClubProgress.ts
  packages/web/src/features/manage-club/activity-certificate/components/ManageActivityCertificate.tsx
  packages/web/src/features/manage-club/activity-certificate/frame/ManageCertificateDetailFrame.tsx
  packages/web/src/features/manage-club/activity-certificate/frames/ManageCertificateDetailFrame.tsx
  packages/web/src/features/manage-club/common-space/components/ManageCommonSpaceProgress.tsx
  packages/web/src/features/manage-club/common-space/frame/ManageCommonSpaceDetailFrame.tsx
  packages/web/src/features/manage-club/common-space/frames/ManageCommonSpaceDetailFrame.tsx
  packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
  packages/web/src/features/manage-club/printing/components/ManagePrintingProgress.tsx
  packages/web/src/features/manage-club/printing/frame/ManagePrintingDetailFrame.tsx
  packages/web/src/features/manage-club/printing/frames/ManagePrintingDetailFrame.tsx
  packages/web/src/features/manage-club/rental/components/ManageRentalProgress.tsx
  packages/web/src/features/manage-club/rental/frame/ManageRentalDetailFrame.tsx
  packages/web/src/features/manage-club/rental/frames/ManageRentalDetailFrame.tsx
  packages/web/src/utils/Date/formateDate.ts
Labels: enhancement, front-end

#481 433 implement reg 001
  packages/api/src/app.module.ts
  packages/api/src/drizzle/drizzle.provider.ts
  packages/api/src/drizzle/schema/registration.schema.ts
  packages/api/src/feature/registration/controller/registration.controller.ts
  packages/api/src/feature/registration/dto/registration.dto.ts
  packages/api/src/feature/registration/registration.module.ts
  packages/api/src/feature/registration/repository/registration.repository.ts
  packages/api/src/feature/registration/service/registration.service.ts
  packages/interface/src/api/registration/endpoint/apiReg001.ts
  packages/interface/src/api/registration/endpoint/apiReg002.ts
  packages/interface/src/api/registration/endpoint/apiReg003.ts
  packages/interface/src/api/registration/index.ts
Labels: enhancement, back-end

#402 impl register club subpages
  packages/web/src/app/register-club/promotional/page.tsx
  packages/web/src/app/register-club/provisional/page.tsx
  packages/web/src/app/register-club/renewal/page.tsx
  packages/web/src/features/credits/components/MemberCard.tsx
  packages/web/src/features/register-club/components/AdvancedInformFrame.tsx
  packages/web/src/features/register-club/components/BasicInformFrame.tsx
  packages/web/src/features/register-club/components/ClubRegulationsComplianceSection.tsx
  packages/web/src/features/register-club/components/ClubRulesFrame.tsx
  packages/web/src/features/register-club/components/ProfessorInformFrame.tsx
  packages/web/src/features/register-club/components/_atomic/DivisionSelect.tsx
  packages/web/src/features/register-club/components/_atomic/MonthSelect.tsx
  packages/web/src/features/register-club/components/_atomic/YearSelect.tsx
  packages/web/src/features/register-club/frame/RegisterClubMainFrame.tsx
  packages/web/src/features/register-club/types/registerClub.ts
Labels: front-end

#491 Fix responsive view on /clubs page
  packages/web/src/features/clubs/components/ClubListGrid.tsx
Labels: bug, good first issue, front-end

#492 Show clubcard differently based on login status
  packages/web/src/features/clubs/components/ClubCard.tsx
Labels: enhancement, good first issue, front-end

#498 Remove common Repositories
  packages/api/src/common/repository/semester.repository.ts
  packages/api/src/common/repository/student.repository.ts
  packages/api/src/feature/activity-certificate/activity-certificate.module.ts
  packages/api/src/feature/activity-certificate/service/activity-certificate.service.ts
  packages/api/src/feature/auth/service/auth.service.ts
  packages/api/src/feature/club/club.module.ts
  packages/api/src/feature/club/repository/club.club-t.repository.ts
  packages/api/src/feature/club/repository/club.repository.ts
  packages/api/src/feature/club/repository/club.semester-d.repository.ts
  packages/api/src/feature/club/service/club.public.service.ts
  packages/api/src/feature/club/service/club.service.ts
  packages/api/src/feature/common-space/common-space.module.ts
  packages/api/src/feature/common-space/service/common-space.service.ts
  packages/api/src/feature/promotional-printing/promotional-printing.module.ts
  packages/api/src/feature/promotional-printing/service/promotional-printing.service.ts
  packages/api/src/feature/user/repository/executive.repository.ts
  packages/api/src/feature/user/repository/user.repository.ts
  packages/api/src/feature/user/service/user.service.ts
  packages/api/src/feature/user/user.module.ts
Labels: invalid, back-end

#483 fix clb interface
  packages/interface/src/api/club/endpoint/apiClb001.ts
  packages/interface/src/api/club/endpoint/apiClb002.ts
  packages/interface/src/api/club/endpoint/apiClb003.ts
  packages/interface/src/api/club/endpoint/apiClb004.ts
  packages/interface/src/api/club/endpoint/apiClb008.ts
  packages/interface/src/api/club/endpoint/apiClb009.ts
  packages/interface/src/api/club/endpoint/apiClb010.ts
  packages/interface/src/api/club/endpoint/apiClb011.ts
  packages/interface/src/api/club/endpoint/apiClb012.ts
  packages/interface/src/api/club/endpoint/apiClb013.ts
  packages/interface/src/api/club/endpoint/apiClb014.ts
  packages/web/src/features/clubDetails/services/_mock/mockupClubDetail.ts
  packages/web/src/features/clubs/services/_mock/mockupClubData.ts
Labels: enhancement, interface

#454 Impl /register-club Page layout
  packages/web/src/app/register-club/page.tsx
  packages/web/src/features/register-club/components/ClubButton.tsx
Labels: enhancement, good first issue, front-end

#501 451 add button on clubs detail page for member registration perio
  packages/web/src/app/clubs/[id]/page.tsx
  packages/web/src/common/components/PageHead/index.tsx
  packages/web/src/features/clubDetails/frames/ClubDetailMainFrame.tsx
Labels: enhancement, good first issue, front-end

#430 impl login auth fe
  packages/interface/src/api/auth/endpoint/apiAut003.ts
  packages/web/package.json
  packages/web/src/common/components/Header/_atomic/Login.tsx
  packages/web/src/common/components/MyMenu/_atomic/Profile.tsx
  packages/web/src/common/components/MyMenu/_atomic/ProfileList.tsx
  packages/web/src/common/components/MyMenu/index.tsx
  packages/web/src/common/providers/AuthContext.tsx
  packages/web/src/common/services/_mock/mockAccessToken.ts
  packages/web/src/common/services/postLogin.ts
  packages/web/src/common/services/postLogout.ts
  packages/web/src/lib/_axios/axiosAuthTokenInterceptor.ts
  packages/web/src/lib/_axios/axiosErrorInterceptor.ts
  packages/web/src/lib/_axios/postRefresh.ts
  packages/web/src/utils/getUserType.ts
  pnpm-lock.yaml
Labels: enhancement, front-end

#503 Impl /register-club responsive design
  packages/web/src/app/register-club/page.tsx
  packages/web/src/features/register-club/components/ClubButton.tsx
Labels: enhancement, good first issue, front-end

#448 Implement UnitInput
  packages/web/src/common/components/Forms/TextInput.tsx
  packages/web/src/common/components/Forms/UnitInput.tsx
  packages/web/src/features/manage-club/funding/frames/FundingInfoFrame.tsx
Labels: enhancement, good first issue, front-end

#263 activity certificate connect backend
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoFirstFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateMainFrame.tsx
  packages/web/src/features/activity-certificate/services/_mock/mockupUserClubs.ts
  packages/web/src/features/activity-certificate/services/getUserClubs.ts
  packages/web/src/features/activity-certificate/types/activityCertificate.ts
Labels: front-end
