Repository sparcs-kaist/clubs, pull requests merged in 2024-11, with the labels that each got.

#1182 update apiAcf002 findClubActivities
  packages/api/src/feature/activity-certificate/controller/activity-certificate.controller.ts
  packages/api/src/feature/activity-certificate/service/activity-certificate.service.ts
  packages/api/src/feature/club/repository/club.repository.ts
  packages/interface/src/api/activity-certificate/endpoint/apiAcf002.ts
Labels: back-end

#1185 1184 fix findclubactivities object assign issue
  packages/api/src/feature/activity-certificate/controller/activity-certificate.controller.ts
  packages/api/src/feature/club/repository/club.repository.ts
Labels: bug, back-end

#1191 modify itemnumberinput
  packages/web/src/common/components/Forms/ItemNumberInput.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoFirstFrame.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormSecond.tsx
  packages/web/src/features/rental-business/components/Rentals/Easel.tsx
  packages/web/src/features/rental-business/components/Rentals/HandCart.tsx
  packages/web/src/features/rental-business/components/Rentals/Mat.tsx
  packages/web/src/features/rental-business/components/Rentals/Tool.tsx
Labels: enhancement, front-end

#1192 Feat: feature to change agenda item order
  packages/web/src/features/meeting/agenda/create/components/AgendaBlock.tsx
  packages/web/src/features/meeting/agenda/create/frames/NewAgendaFrame.tsx
  packages/web/src/features/meeting/services/_mock/mockupMeetingAgenda.ts
Labels: front-end

#1189 Modify meeting.schema.ts
  packages/api/src/drizzle/schema/meeting.schema.ts
  packages/api/src/feature/meeting/meeting.repository.ts
  packages/api/src/feature/meeting/meeting.service.ts
Labels: back-end

#1176 Add Search and Multifilter in /executive/register-club
  packages/interface/src/common/enum/registration.enum.ts
  packages/web/src/common/components/MultiFilter/_atomic/DetailFilterDropdown.tsx
  packages/web/src/common/components/MultiFilter/_atomic/MultiFilterDropdown.tsx
  packages/web/src/features/executive/register-club/frames/ExecutiveRegistrationClubFrame.tsx
  packages/web/src/features/executive/register-club/services/_mock/mockRegisterClub.ts
  packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
  packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
  packages/web/src/types/divisions.types.ts
Labels: enhancement, front-end

#1194 Remove autoincrement from positions in meeting mapping
  packages/api/src/drizzle/schema/meeting.schema.ts
Labels: back-end

#1180 migrate activityCertificate to use react-hook-form
  packages/web/src/common/components/Forms/DateInput.tsx
  packages/web/src/common/components/Forms/DateRangeInput.tsx
  packages/web/src/common/components/Forms/ItemNumberInput.tsx
  packages/web/src/common/components/Forms/PhoneInput.tsx
  packages/web/src/common/components/StyledBottom.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoFirstFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoSecondFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoThirdFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/index.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateMainFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateNoticeFrame.tsx
  packages/web/src/features/activity-certificate/services/_mock/mockupUserClubs.ts
  packages/web/src/features/activity-certificate/services/getUserClubs.ts
  packages/web/src/features/activity-certificate/services/useGetUserClubs.ts
  packages/web/src/features/activity-certificate/services/useGetUserInfo.tsx
  packages/web/src/features/activity-certificate/services/usePostActivityCertificate.ts
  packages/web/src/features/activity-certificate/types/activityCertificate.ts
  packages/web/src/features/activity-certificate/utils/formatActivityDuration.ts
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/index.tsx
  packages/web/src/features/common-space/frames/CommonSpaceNoticeFrame.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessNotice.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/index.tsx
  packages/web/src/features/rental-business/frames/RentalNoticeFrame.tsx
Labels: front-end

#1196 userType enum issue
  packages/interface/src/common/enum/user.enum.ts
  packages/web/src/common/components/Header/_atomic/Login.tsx
  packages/web/src/common/components/MyMenu/index.tsx
  packages/web/src/common/components/withAuthorization.tsx
  packages/web/src/utils/getUserType.ts
Labels: front-end

#1201 Verify NotNull in MeetingMapping position attributes
  packages/api/src/drizzle/schema/meeting.schema.ts
Labels: back-end

#1121 Impl tooltip component
  packages/web/src/common/components/Tooltip.tsx
Labels: front-end

#1179 Add Search and Multifilter in /executive/register-member
  packages/web/src/features/executive/register-member/_mock/mockMemberRegistration.tsx
  packages/web/src/features/executive/register-member/frames/ExecutiveRegisterMemberFrame.tsx
Labels: enhancement, front-end

#1206 fix meeting announcemnt issue
  packages/api/src/app.module.ts
  packages/api/src/drizzle/schema/meeting.schema.ts
  packages/api/src/feature/meeting/announcement/announcement.controller.ts
  packages/api/src/feature/meeting/meeting.controller.ts
  packages/api/src/feature/meeting/meeting.repository.ts
  packages/api/src/feature/meeting/meeting.service.ts
  packages/interface/src/api/meeting/apiMee004.ts
  packages/interface/src/api/meeting/apiMee005.ts
Labels: back-end

#1210 update ActivityCertificateInfoFirstFrame phoneNumber validation
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoFirstFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateMainFrame.tsx
Labels: front-end

#1204 fix: update meeting announcement routing
  packages/web/src/app/meeting/announcement/create/page.tsx
  packages/web/src/app/meeting/page.tsx
  packages/web/src/common/components/Forms/DateInput.tsx
  packages/web/src/features/meeting/components/MeetingInformationFrame.tsx
  packages/web/src/features/meeting/components/MeetingNoticeItem.tsx
  packages/web/src/features/meeting/services/useCreateMeeting.ts
Labels: front-end

#1227 Fix representative change bugs
  packages/api/src/feature/club/delegate/delegate.service.ts
Labels: bug, back-end

#1226 apply sem001
  packages/web/src/common/services/getSemesters.ts
  packages/web/src/features/clubDetails/components/RegisterInfo.tsx
  packages/web/src/features/clubs/components/ClubRegistrationButton.tsx
  packages/web/src/features/clubs/frames/ClubsStudentFrame.tsx
  packages/web/src/features/manage-club/components/MembersTable.tsx
  packages/web/src/features/manage-club/frames/MemberManageFrame.tsx
  packages/web/src/features/manage-club/frames/RegistrationManageFrame.tsx
  packages/web/src/features/manage-club/members/frames/RegisterMemberListFrame.tsx
  packages/web/src/features/my/frames/MyClubFrame.tsx
  packages/web/src/features/my/frames/ProfessorMyClubFrame.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
  packages/web/src/features/register-club/frames/RegisterClubFrame.tsx
  packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
  packages/web/src/utils/getSemesterNow.ts
Labels: enhancement, front-end

#1214 add club delegate module
  packages/api/src/feature/activity-certificate/activity-certificate.module.ts
  packages/api/src/feature/activity-certificate/service/activity-certificate.service.ts
  packages/api/src/feature/club/club.module.ts
  packages/api/src/feature/club/delegate/club.club-delegate-d.repository.ts
  packages/api/src/feature/club/delegate/delegate.module.ts
  packages/api/src/feature/club/delegate/delegate.service.ts
  packages/api/src/feature/club/service/club.public.service.ts
  packages/api/src/feature/club/service/club.service.ts
  packages/api/src/feature/promotional-printing/promotional-printing.module.ts
  packages/api/src/feature/promotional-printing/service/promotional-printing.service.ts
Labels: back-end

#1217 Impl MEE 006 008 010 api
  packages/api/src/drizzle/schema/meeting.schema.ts
  packages/api/src/feature/meeting/agenda/agenda.controller.ts
  packages/api/src/feature/meeting/agenda/agenda.module.ts
  packages/api/src/feature/meeting/agenda/agenda.service.ts
  packages/api/src/feature/meeting/meeting.module.ts
  packages/api/src/feature/meeting/meeting.repository.ts
  packages/interface/src/api/meeting/apiMee006.ts
  packages/interface/src/api/meeting/apiMee008.ts
  packages/interface/src/api/meeting/apiMee010.ts
Labels: back-end

#1202 Migrate /common-space to react-hook-form
  packages/api/src/feature/common-space/controller/common-space.controller.ts
  packages/web/src/common/components/Timetable/_atomic/TimetableDateList.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoFirstFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoSecondFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoThirdFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/index.tsx
  packages/web/src/features/common-space/frames/CommonSpaceMainFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceNoticeFrame.tsx
  packages/web/src/features/common-space/service/_mock/mockupCommonSpaceUsageOrders.ts
  packages/web/src/features/common-space/service/getCommonSpaces.ts
  packages/web/src/features/common-space/types/commonSpace.ts
Labels: enhancement, front-end
