Repository sparcs-kaist/clubs, pull requests merged in 2024-10, with the labels that each got.

#1125 Add chacha credit
  packages/web/src/features/credits/credits.ts
Labels: enhancement, front-end

#1133 1120 member registration fix register button flicker on club detail page
  packages/web/src/features/clubDetails/components/RegisterInfo.tsx
  packages/web/src/features/clubDetails/frames/ClubDetailMainFrame.tsx
  packages/web/src/features/clubDetails/services/getMyMemberRegistration.ts
  packages/web/src/features/clubs/components/ClubCard.tsx
  packages/web/src/features/clubs/components/ClubRegistrationButton.tsx
  packages/web/src/features/clubs/components/MobileClubCard.tsx
  packages/web/src/hooks/isInClub.ts
Labels: bug, front-end

#1115 connect api to meeting create page
  packages/web/src/app/meeting/[id]/edit/page.tsx
  packages/web/src/app/meeting/[id]/page.tsx
  packages/web/src/app/meeting/announcement/create/page.tsx
  packages/web/src/common/components/Modal/ErrorModal.tsx
  packages/web/src/common/components/withAuthorization.tsx
  packages/web/src/features/meeting/components/MeetingAnnouncementForm.tsx
  packages/web/src/features/meeting/components/MeetingAnnouncementFrame.tsx
  packages/web/src/features/meeting/components/MeetingInformationFrame.tsx
  packages/web/src/features/meeting/constants/meetingTemplate.ts
  packages/web/src/features/meeting/services/useCreateMeeting.ts
  packages/web/src/features/meeting/services/useUpdateMeeting.ts
  packages/web/src/utils/getSemester.ts
  packages/web/src/utils/getUserType.ts
Labels: front-end

#1144 Modify /meeting page
  packages/web/src/app/meeting/page.tsx
  packages/web/src/features/meeting/components/MeetingNoticeItem.tsx
Labels: enhancement, front-end

#1107 Impl Markdown Editor
  packages/web/package.json
  packages/web/src/assets/table-column-plus-after-disabled.svg
  packages/web/src/assets/table-column-plus-after.svg
  packages/web/src/assets/table-column-plus-before-disabled.svg
  packages/web/src/assets/table-column-plus-before.svg
  packages/web/src/assets/table-column-remove-disabled.svg
  packages/web/src/assets/table-column-remove.svg
  packages/web/src/assets/table-merge-cells-disabled.svg
  packages/web/src/assets/table-merge-cells.svg
  packages/web/src/assets/table-row-plus-after-disabled.svg
  packages/web/src/assets/table-row-plus-after.svg
  packages/web/src/assets/table-row-plus-before-disabled.svg
  packages/web/src/assets/table-row-plus-before.svg
  packages/web/src/assets/table-row-remove-disabled.svg
  packages/web/src/assets/table-row-remove.svg
  packages/web/src/assets/table-split-cell-disabled.svg
  packages/web/src/assets/table-split-cell.svg
  packages/web/src/common/components/Buttons/IconButton.tsx
  packages/web/src/common/components/Markdown/index.tsx
  packages/web/src/common/components/Markdown/styles.scss
  pnpm-lock.yaml
Labels: enhancement, front-end

#1151 Add clickable label
  packages/web/src/common/components/CheckboxOption.tsx
  packages/web/src/common/components/Radio/RadioOption.tsx
Labels: enhancement, front-end

#1155 Add label to radio & Add children to info
  packages/web/src/common/components/Info.tsx
  packages/web/src/common/components/Radio/index.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/_atomic/BinaryRadio.tsx
  packages/web/src/features/rental-business/components/Rentals/Vacuum.tsx
Labels: enhancement, front-end

#1146 add fall semester credit for ava
  packages/web/src/features/credits/credits.ts
Labels: front-end

#1157 1116 edit dateinput component
  packages/web/package.json
  packages/web/src/app/meeting/[id]/edit/page.tsx
  packages/web/src/app/meeting/announcement/create/page.tsx
  packages/web/src/common/components/Buttons/TextButton.tsx
  packages/web/src/common/components/FormController.tsx
  packages/web/src/common/components/Forms/DateInput.tsx
  packages/web/src/common/components/NavTools/MobileNavMenu.tsx
  packages/web/src/features/meeting/components/MeetingInformationFrame.tsx
  packages/web/src/utils/Date/formatDate.ts
  pnpm-lock.yaml
Labels: front-end

#1096 member registration connect backend for change delegate
  packages/api/src/feature/club/delegate/delegate.service.ts
  packages/api/src/feature/club/repository/club.club-delegate-d.repository.ts
  packages/interface/src/api/club/endpoint/apiClb006.ts
  packages/interface/src/api/club/endpoint/apiClb007.ts
  packages/web/src/common/components/Select/index.tsx
  packages/web/src/features/manage-club/components/ChangeRepresentativeCardV1.tsx
  packages/web/src/features/manage-club/frames/InfoManageFrame.tsx
  packages/web/src/features/manage-club/frames/ManageClubFrame.tsx
  packages/web/src/features/manage-club/frames/_atomic/RepresentativeLoadFrame.tsx
  packages/web/src/features/manage-club/services/_mock/mockDelegate.ts
  packages/web/src/features/manage-club/services/getChangeDelegateRequests.ts
  packages/web/src/features/manage-club/services/getDelegateCandidates.ts
  packages/web/src/features/manage-club/services/updateClubDelegate.ts
  packages/web/src/hooks/checkManageClub.ts
Labels: enhancement, front-end

#1161 Fix club member search filter
  packages/web/src/features/manage-club/members/components/AllMemberList.tsx
  packages/web/src/features/manage-club/members/frames/AllMemberListFrame.tsx
Labels: bug, front-end

#1158 Impl multiselect filter
  packages/web/src/common/components/MultiFilter/Index.tsx
  packages/web/src/common/components/MultiFilter/_atomic/DetailFilter.tsx
  packages/web/src/common/components/MultiFilter/_atomic/DetailFilterButton.tsx
  packages/web/src/common/components/MultiFilter/_atomic/DetailFilterDropdown.tsx
  packages/web/src/common/components/MultiFilter/_atomic/MultiFilterButton.tsx
  packages/web/src/common/components/MultiFilter/_atomic/MultiFilterDropdown.tsx
  packages/web/src/common/components/MultiFilter/types/FilterCategories.ts
  packages/web/src/common/components/Select/Dropdown.tsx
  packages/web/src/common/components/SelectedItem.tsx
Labels: enhancement, front-end
