Repository sparcs-kaist/clubs, pull requests merged in 2024-09, with the labels that each got.

#966 fix: act011
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/interface/src/api/activity/endpoint/apiAct011.ts
  packages/web/src/features/my/register-club/components/MyRegisterClubAcfTable.tsx
Labels: back-end

#967 feat: connect act002 act011
  packages/web/src/common/components/File/ThumbnailPreviewList.tsx
  packages/web/src/features/manage-club/activity-report/_mock/mock.ts
  packages/web/src/features/manage-club/activity-report/components/PastActivityReportList.tsx
  packages/web/src/features/register-club/components/ActivityReportFrame.tsx
  packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
Labels: front-end, interface

#869 feat: link not found
  packages/web/src/app/activity-certificate/page.tsx
  packages/web/src/app/common-space/page.tsx
  packages/web/src/app/example/page.tsx
  packages/web/src/app/executive/activity-certificate/page.tsx
  packages/web/src/app/executive/printing-business/page.tsx
  packages/web/src/app/executive/register-member/[id]/page.tsx
  packages/web/src/app/executive/register-member/page.tsx
  packages/web/src/app/executive/rental-business/page.tsx
  packages/web/src/app/manage-club/activity-certificate/[id]/page.tsx
  packages/web/src/app/manage-club/activity-certificate/page.tsx
  packages/web/src/app/manage-club/activity-report/[id]/edit/page.tsx
  packages/web/src/app/manage-club/activity-report/[id]/page.tsx
  packages/web/src/app/manage-club/activity-report/create/page.tsx
  packages/web/src/app/manage-club/activity-report/page.tsx
  packages/web/src/app/manage-club/common-space/[id]/page.tsx
  packages/web/src/app/manage-club/common-space/page.tsx
  packages/web/src/app/manage-club/funding/[id]/edit/page.tsx
  packages/web/src/app/manage-club/funding/[id]/page.tsx
  packages/web/src/app/manage-club/funding/create/page.tsx
  packages/web/src/app/manage-club/funding/page.tsx
  packages/web/src/app/manage-club/members/page.tsx
  packages/web/src/app/manage-club/printing-business/[id]/page.tsx
  packages/web/src/app/manage-club/printing-business/page.tsx
  packages/web/src/app/manage-club/rental-business/[id]/page.tsx
  packages/web/src/app/manage-club/rental-business/page.tsx
  packages/web/src/app/manage-division/page.tsx
  packages/web/src/app/meeting/[id]/page.tsx
  packages/web/src/app/meeting/agenda/create/page.tsx
  packages/web/src/app/meeting/page.tsx
  packages/web/src/app/my/activity-certificate/[id]/page.tsx
  packages/web/src/app/my/activity-certificate/page.tsx
  packages/web/src/app/my/common-space/[id]/page.tsx
  packages/web/src/app/my/common-space/page.tsx
  packages/web/src/app/my/printing-business/[id]/page.tsx
  packages/web/src/app/my/printing-business/page.tsx
  packages/web/src/app/my/rental-business/[id]/page.tsx
  packages/web/src/app/my/rental-business/page.tsx
  packages/web/src/app/printing-business/page.tsx
  packages/web/src/app/rental-business/page.tsx
  packages/web/src/features/manage-club/frames/ManageClubFrame.tsx
Labels: front-end

#977 executive register club detail problems
  packages/web/src/common/components/ListItem.tsx
  packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
Labels: bug, front-end

#976 fix: act002 act014 ac015 response type
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/interface/src/api/activity/endpoint/apiAct002.ts
  packages/interface/src/api/activity/endpoint/apiAct003.ts
  packages/interface/src/api/activity/endpoint/apiAct014.ts
  packages/interface/src/api/activity/endpoint/apiAct015.ts
  packages/web/src/app/manage-club/activity-report/[id]/page.tsx
  packages/web/src/features/manage-club/activity-report/_mock/mock.ts
  packages/web/src/features/manage-club/activity-report/services/useGetActivityReport.tsx
  packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
Labels: back-end

#981 fix: usr002
  packages/api/src/feature/user/controller/user.controller.ts
  packages/interface/src/api/user/endpoint/apiUsr002.ts
Labels: back-end

#972 feat: connect act004 act008
  packages/interface/src/api/activity/endpoint/apiAct008.ts
  packages/web/src/common/components/FileUpload.tsx
  packages/web/src/features/manage-club/activity-report/components/PastActivityReportList.tsx
  packages/web/src/features/manage-club/activity-report/services/useDeleteActivityReport.tsx
  packages/web/src/features/my/register-club/components/MyRegisterClubAcfTable.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
  packages/web/src/features/register-club/components/_atomic/ActivityReportForm.tsx
  packages/web/src/features/register-club/components/_atomic/EditActivityReportModal.tsx
  packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
  packages/web/src/features/register-club/services/usePutActivityReportForNewClub.ts
Labels: front-end, interface

#974 use usr002 to get phone number
  packages/web/src/app/my/page.tsx
  packages/web/src/common/services/getUserPhoneNumber.ts
  packages/web/src/features/my/frames/MyInfoFrame.tsx
  packages/web/src/features/my/frames/ProfessorMyClubFrame.tsx
Labels: bug, front-end

#993 Fix reg-014 total counting soft deletions
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
Labels: back-end

#947 fix: fix issue with localstorage
  package.json
  packages/web/src/assets/notImplementedChan.gif
  packages/web/src/common/components/Header/_atomic/Login.tsx
  packages/web/src/common/components/MyMenu/_atomic/ProfileList.tsx
  packages/web/src/common/providers/AuthContext.tsx
  packages/web/src/hooks/getFeatureFlag.ts
  packages/web/src/lib/_axios/axiosErrorInterceptor.ts
  packages/web/src/utils/localStorage.ts
Labels: bug

#994 fix: fix executive registration club table
  packages/web/src/features/executive/register-club/frames/ExecutiveRegistrationClubFrame.tsx
Labels: bug, front-end

#996 modify act detail for registration
  packages/web/src/common/providers/AuthContext.tsx
  packages/web/src/features/manage-club/activity-report/components/PastActivityReportList.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportEditFrame.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportMainFrame.tsx
  packages/web/src/features/manage-club/activity-report/services/useGetActivityReport.tsx
  packages/web/src/features/my/register-club/components/MyRegisterClubAcfTable.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubAcfFrame.tsx
  packages/web/src/features/register-club/components/ActivityReportFrame.tsx
  packages/web/src/features/register-club/components/_atomic/EditActivityReportModal.tsx
  packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
  packages/web/src/features/register-club/services/_atomic/actApiList.ts
  packages/web/src/features/register-club/services/getProvisionalActivities.ts
Labels: bug, front-end

#948 896 add channel talk
  packages/web/package.json
  packages/web/src/app/executive/register-club/[id]/page.tsx
  packages/web/src/app/executive/register-club/page.tsx
  packages/web/src/app/executive/register-member/[id]/page.tsx
  packages/web/src/app/executive/register-member/page.tsx
  packages/web/src/app/manage-club/members/page.tsx
  packages/web/src/app/manage-club/page.tsx
  packages/web/src/app/my/clubs/page.tsx
  packages/web/src/app/my/page.tsx
  packages/web/src/app/my/register-club/[id]/edit/page.tsx
  packages/web/src/app/my/register-club/[id]/page.tsx
  packages/web/src/app/register-club/promotional/page.tsx
  packages/web/src/app/register-club/provisional/page.tsx
  packages/web/src/app/register-club/renewal/page.tsx
  packages/web/src/common/components/Footer/index.tsx
  packages/web/src/common/components/Header/index.tsx
  packages/web/src/common/providers/AuthContext.tsx
  packages/web/src/features/register-club/components/ActivityReportFrame.tsx
  pnpm-lock.yaml
Labels: enhancement, front-end

#1004 Implement participants selection list generation (ACT-010)
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/api/src/feature/club/repository/club.club-student-t.repository.ts
  packages/api/src/feature/club/service/club.public.service.ts
  packages/interface/src/api/activity/endpoint/apiAct010.ts
Labels: back-end

#1003 fix: file import
  packages/api/src/feature/activity/activity.module.ts
Labels: back-end

#838 fix Table overflow
  packages/web/src/common/components/Table.tsx
  packages/web/src/features/register-club/components/ActivityReportFrame.tsx
Labels: front-end

#884 feat: download template
  packages/web/src/features/register-club/components/AdvancedInformFrame.tsx
  packages/web/src/features/register-club/components/SingleUploadWithTextAndTemplate.tsx
Labels: front-end

#1011 fix: professor login logic
  packages/api/src/feature/auth/repository/auth.repository.ts
Labels: back-end

#1012 fix several issues
  packages/interface/src/api/club/endpoint/apiClb004.ts
  packages/web/src/app/register-club/page.tsx
  packages/web/src/common/frames/NoRegisterClubForProfessor.tsx
  packages/web/src/features/manage-club/components/ChangeClubInfoCard.tsx
  packages/web/src/features/manage-club/services/getClubInfo.ts
  packages/web/src/features/my/frames/MyClubFrame.tsx
  packages/web/src/features/my/frames/ProfessorMyClubFrame.tsx
  packages/web/src/features/register-club/frames/RegisterClubFrame.tsx
Labels: enhancement, front-end

#1016 Add optional width prop to Modal
  packages/web/src/common/components/Modal/index.tsx
  packages/web/src/features/register-club/components/_atomic/CreateActivityReportModal.tsx
  packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
Labels: enhancement, front-end

#1018 Implement act-016 interface and api
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/interface/src/api/activity/endpoint/apiAct016.ts
Labels: back-end, interface

#1020 fix: reg019 interface
  packages/interface/src/api/registration/endpoint/apiReg019.ts
Labels: back-end

#1023 connect act016
  packages/web/src/features/executive/register-club/frames/ClubRegisterApproveFrame.tsx
  packages/web/src/features/executive/register-club/services/patchActivityExecutive.ts
  packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
Labels: enhancement, front-end

#1034 1032 fix reg activity report
  packages/api/src/feature/activity/activity.module.ts
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/club-registration/service/club-registration.public.service.ts
  packages/interface/src/api/registration/endpoint/apiReg001.ts
  packages/interface/src/api/registration/endpoint/apiReg009.ts
  packages/interface/src/api/registration/utils/registrationTypeEnumChecker.ts
Labels: back-end

#1036 fix: reg014 reg021
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
  packages/interface/src/api/registration/endpoint/apiReg012.ts
  packages/interface/src/api/registration/endpoint/apiReg014.ts
  packages/interface/src/api/registration/endpoint/apiReg021.ts
  packages/web/src/features/executive/register-club/services/_mock/mockRegisterClub.ts
  packages/web/src/features/my/components/MyClubProfTable.tsx
  packages/web/src/features/register-club/services/_mocks/mockMyRegistration.ts
Labels: bug, back-end

#1038 fix: act011
  packages/api/src/feature/activity/service/activity.service.ts
  packages/interface/src/api/activity/endpoint/apiAct011.ts
  packages/web/src/features/manage-club/activity-report/_mock/mock.ts
Labels: bug, back-end

#1039 merge dev into main
  package.json
  packages/api/package.json
  packages/api/src/feature/activity/activity.module.ts
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/club-registration/service/club-registration.public.service.ts
  packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
  packages/interface/src/api/activity/endpoint/apiAct011.ts
  packages/interface/src/api/activity/endpoint/apiAct017.ts
  packages/interface/src/api/registration/endpoint/apiReg001.ts
  packages/interface/src/api/registration/endpoint/apiReg009.ts
  packages/interface/src/api/registration/endpoint/apiReg012.ts
  packages/interface/src/api/registration/endpoint/apiReg014.ts
  packages/interface/src/api/registration/endpoint/apiReg021.ts
  packages/interface/src/api/registration/utils/registrationTypeEnumChecker.ts
  packages/web/package.json
  packages/web/src/common/components/Button.tsx
  packages/web/src/common/components/FileUpload.tsx
  packages/web/src/common/components/ListItem.tsx
  packages/web/src/common/providers/AuthContext.tsx
  packages/web/src/features/executive/register-club/frames/ClubRegisterApproveFrame.tsx
  packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
  packages/web/src/features/executive/register-club/services/_mock/mockRegisterClub.ts
  packages/web/src/features/executive/register-club/services/patchActivityExecutive.ts
  packages/web/src/features/executive/register-club/services/patchActivityExecutiveSendBack.ts
  packages/web/src/features/executive/register-club/services/useGetRegisterClub.ts
  packages/web/src/features/manage-club/activity-report/_mock/mock.ts
  packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
  packages/web/src/features/manage-club/funding/components/TransportEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/types/funding.ts
  packages/web/src/features/my/components/MyClubProfTable.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
  packages/web/src/features/register-club/components/ActivityReportFrame.tsx
  packages/web/src/features/register-club/components/BasicInformFrame.tsx
  packages/web/src/features/register-club/components/ProvisionalBasicInformFrame.tsx
  packages/web/src/features/register-club/components/_atomic/ActivityReportForm.tsx
  packages/web/src/features/register-club/components/_atomic/ClubNameField.tsx
  packages/web/src/features/register-club/components/_atomic/CreateActivityReportModal.tsx
  packages/web/src/features/register-club/components/_atomic/EditActivityReportModal.tsx
  packages/web/src/features/register-club/components/_atomic/MonthSelect.tsx
  packages/web/src/features/register-club/components/_atomic/ParticipantSection.tsx
  packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
  packages/web/src/features/register-club/components/_atomic/YearSelect.tsx
  packages/web/src/features/register-club/services/_mocks/mockMyRegistration.ts
  packages/web/src/features/register-club/types/registerClub.ts
  packages/web/src/features/register-club/utils/registrationType.ts
  packages/web/src/utils/Date/formatDate.ts
Labels: release

#1046 fix: db schema and club permannent logic
  packages/api/src/drizzle/schema/division.schema.ts
  packages/api/src/feature/club/repository/club.repository.ts
  packages/api/src/feature/registration/member-registration/repository/member-registration.repository.ts
Labels: bug, back-end

#1047 merge dev into main
  packages/api/src/drizzle/schema/division.schema.ts
  packages/api/src/feature/club/repository/club.repository.ts
  packages/api/src/feature/registration/member-registration/repository/member-registration.repository.ts
  packages/web/src/app/manage-club/page.tsx
  packages/web/src/common/frames/NoManageClubForProfessor.tsx
  packages/web/src/constants/tableTagList.ts
  packages/web/src/features/manage-club/activity-report/components/PastActivityReportList.tsx
  packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
  packages/web/src/features/manage-club/activity-report/services/useDeleteActivityReportProvisional.tsx
  packages/web/src/features/my/register-club/components/MyRegisterClubActTable.tsx
  packages/web/src/features/register-club/components/ActivityReportFrame.tsx
  packages/web/src/features/register-club/components/_atomic/ActivityReportForm.tsx
  packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
Labels: release

#1051 Implement Club member-registraiton dashboard for executives (REG-020)
  packages/api/src/feature/registration/member-registration/controller/member-registration.controller.ts
  packages/api/src/feature/registration/member-registration/repository/member-registration.repository.ts
  packages/api/src/feature/registration/member-registration/service/member-registration.service.ts
  packages/interface/src/api/registration/endpoint/apiReg020.ts
Labels: back-end, interface

#1014 Connect backend for /executive/register-member
  packages/web/src/common/components/RegisterMemberTable.tsx
  packages/web/src/features/executive/register-member/_mock/mockMemberRegistration.tsx
  packages/web/src/features/executive/register-member/frames/ExecutiveRegisterMemberFrame.tsx
  packages/web/src/features/executive/register-member/services/getMemberRegistration.ts
Labels: enhancement, front-end

#1052 Connect backend for /executive/register-member/[id]
  packages/web/src/features/executive/register-member/[id]/_mock/mockClubMemberRegister.tsx
  packages/web/src/features/executive/register-member/[id]/services/calcRegisterInfo.tsx
  packages/web/src/features/executive/register-member/[id]/services/getRegisterMemberDetail.tsx
  packages/web/src/features/executive/register-member/components/RegisterInfoTable.tsx
  packages/web/src/features/executive/register-member/components/StatusInfoFrame.tsx
  packages/web/src/features/executive/register-member/components/TotalInfoFrame.tsx
  packages/web/src/features/executive/register-member/frames/ExecutiveRegisterMemberDetailFrame.tsx
  packages/web/src/features/executive/register-member/services/getMemberRegistration.ts
Labels: enhancement, front-end

#1058 Merge dev into main
  packages/api/src/feature/club/controller/club-delegate.controller.ts
  packages/api/src/feature/registration/member-registration/controller/member-registration.controller.ts
  packages/api/src/feature/registration/member-registration/repository/member-registration.repository.ts
  packages/api/src/feature/registration/member-registration/service/member-registration.service.ts
  packages/interface/src/api/registration/endpoint/apiReg019.ts
  packages/interface/src/api/registration/endpoint/apiReg020.ts
  packages/interface/src/api/registration/utils/registrationTypeEnumChecker.ts
  packages/web/src/common/components/FileUpload.tsx
  packages/web/src/common/components/RegisterMemberTable.tsx
  packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
  packages/web/src/features/executive/register-member/[id]/_mock/mockClubMemberRegister.tsx
  packages/web/src/features/executive/register-member/[id]/services/calcRegisterInfo.tsx
  packages/web/src/features/executive/register-member/[id]/services/getRegisterMemberDetail.tsx
  packages/web/src/features/executive/register-member/_mock/mockMemberRegistration.tsx
  packages/web/src/features/executive/register-member/components/RegisterInfoTable.tsx
  packages/web/src/features/executive/register-member/components/StatusInfoFrame.tsx
  packages/web/src/features/executive/register-member/components/TotalInfoFrame.tsx
  packages/web/src/features/executive/register-member/frames/ExecutiveRegisterMemberDetailFrame.tsx
  packages/web/src/features/executive/register-member/frames/ExecutiveRegisterMemberFrame.tsx
  packages/web/src/features/executive/register-member/services/getMemberRegistration.ts
  packages/web/src/features/register-club/components/AdvancedInformFrame.tsx
  packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
Labels: release

#1061 Merge dev into main
  packages/api/src/drizzle/schema/user.schema.ts
  packages/api/src/feature/auth/repository/auth.repository.ts
  packages/api/src/feature/auth/service/auth.service.ts
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
Labels: release

#1057 fix: /credits layout fix
  packages/web/src/app/credits/page.tsx
  packages/web/src/features/credits/credits.ts
Labels: bug, front-end

#1063 Merge dev into main
  packages/web/src/app/credits/page.tsx
  packages/web/src/common/components/File/ThumbnailPreview.tsx
  packages/web/src/common/components/File/ThumbnailPreviewList.tsx
  packages/web/src/common/components/File/_atomic/UnsupportedPreview.tsx
  packages/web/src/common/components/File/attachment.ts
  packages/web/src/common/components/FileUpload.tsx
  packages/web/src/common/components/FormController.tsx
  packages/web/src/features/credits/credits.ts
  packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailFrame.tsx
  packages/web/src/features/manage-club/funding/detail/components/BasicEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/components/FixtureEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/components/OtherEvidenceList.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
  packages/web/src/features/register-club/components/BasicInformFrame.tsx
  packages/web/src/features/register-club/components/ProvisionalBasicInformFrame.tsx
  packages/web/src/features/register-club/components/SingleUploadWithTextAndTemplate.tsx
  packages/web/src/features/register-club/components/_atomic/ActivityReportForm.tsx
  packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
  packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
  packages/web/src/features/register-club/utils/computeErrorMessage.ts
  packages/web/src/utils/validator.ts
Labels: release

#1080 Merge dev into main
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/interface/src/api/activity/endpoint/apiAct002.ts
  packages/web/src/common/components/FileUpload.tsx
  packages/web/src/common/components/RejectReasonToast.tsx
  packages/web/src/features/clubs/services/useGetClubsList.ts
  packages/web/src/features/manage-club/activity-report/_mock/mock.ts
  packages/web/src/features/manage-club/activity-report/components/PastActivityReportList.tsx
  packages/web/src/features/manage-club/activity-report/services/useGetActivityReport.tsx
  packages/web/src/features/register-club/components/_atomic/EditActivityReportModal.tsx
  packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
Labels: release

#1077 [Member Registration] Apply REG-006 API response data to MyMemberRegisterFrame
  packages/web/src/features/clubDetails/services/getMyMemberRegistration.ts
  packages/web/src/features/my/components/MyMemberTable.tsx
  packages/web/src/features/my/frames/_atomic/MyMemberRegisterFrame.tsx
  packages/web/src/features/my/services/_mock/mockMyRegister.ts
Labels: enhancement, front-end

#1054 fix mobile layout issues at club detail page
  packages/web/src/features/clubDetails/components/ClubInfoItem.tsx
  packages/web/src/features/clubDetails/components/PersonInfoCard.tsx
Labels: bug, front-end

#1085 Merge dev into main
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/interface/src/api/file/apiFil001.ts
  packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
Labels: release

#1088 Fix MemberRegistration Error in MembersManageTable
  packages/web/src/features/clubDetails/services/getClubDetail.ts
  packages/web/src/features/manage-club/components/MembersTable.tsx
  packages/web/src/features/manage-club/frames/MembersManageFrame.tsx
  packages/web/src/features/manage-club/members/components/RegisterMemberList.tsx
  packages/web/src/features/manage-club/members/services/getClubMemberRegistration.ts
  packages/web/src/features/manage-club/members/services/patchClubMemberRegistration.ts
Labels: bug, front-end

#1104 Merge dev into main
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/club/club.module.ts
  packages/api/src/feature/club/delegate/delegate.controller.ts
  packages/api/src/feature/club/delegate/delegate.service.ts
  packages/api/src/feature/club/repository/club.club-delegate-d.repository.ts
  packages/api/src/feature/club/repository/club.club-student-t.repository.ts
  packages/api/src/feature/club/service/club.public.service.ts
  packages/api/src/feature/registration/member-registration/service/member-registration.service.ts
  packages/web/src/common/components/Modal/AgreeModal.tsx
  packages/web/src/features/clubDetails/services/getClubDetail.ts
  packages/web/src/features/manage-club/components/MembersTable.tsx
  packages/web/src/features/manage-club/frames/MembersManageFrame.tsx
  packages/web/src/features/manage-club/members/components/RegisterMemberList.tsx
  packages/web/src/features/manage-club/members/frames/RegisterMemberListFrame.tsx
  packages/web/src/features/manage-club/members/services/getClubMemberRegistration.ts
  packages/web/src/features/manage-club/members/services/patchClubMemberRegistration.ts
Labels: release

#1082 feat: display executive pages for member registration period
  packages/web/src/app/executive/register-member/[id]/page.tsx
  packages/web/src/app/executive/register-member/page.tsx
  packages/web/src/features/executive/register-member/services/getMemberRegistration.ts
Labels: enhancement, front-end

#1105 Merge dev into main
  packages/web/src/app/executive/register-member/[id]/page.tsx
  packages/web/src/app/executive/register-member/page.tsx
  packages/web/src/features/clubDetails/services/getMyMemberRegistration.ts
  packages/web/src/features/executive/register-member/components/RegisterInfoTable.tsx
  packages/web/src/features/executive/register-member/services/getMemberRegistration.ts
  packages/web/src/features/manage-club/members/services/getClubMemberRegistration.ts
  packages/web/src/features/my/frames/MyRegisterFrame.tsx
Labels: release

#1114 Merge dev into main
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/member-registration/service/member-registration.service.ts
Labels: release

#1117 Add new member to contributor page
  packages/web/src/features/credits/credits.ts
Labels: front-end

#560 impl create meeting announcement page
  packages/web/src/app/credits/page.tsx
  packages/web/src/app/meeting/announcement/create/page.tsx
  packages/web/src/common/components/ProgressCheckSection/_atomic/Progress.tsx
  packages/web/src/common/components/Select/index.tsx
  packages/web/src/common/components/Timetable/_atomic/TimetableDateList.tsx
  packages/web/src/features/manage-club/funding/detail/components/FundingInfoList.tsx
  packages/web/src/features/meeting/components/MeetingAnnouncementFrame.tsx
  packages/web/src/features/meeting/components/MeetingInformationFrame.tsx
  packages/web/src/features/meeting/constants/getEnumType.ts
  packages/web/src/features/meeting/constants/meetingTemplate.ts
  packages/web/src/features/meeting/services/_mock/mockupMeetingDetail.ts
  packages/web/src/features/meeting/types/meeting.ts
  packages/web/src/utils/Date/formatDate.ts
  packages/web/src/utils/Date/parseDate.ts
  packages/web/src/utils/getSemester.ts
Labels: front-end

#1109 update meeting detail page, connect apiMee002, apiMee004, apiMee005
  packages/web/src/app/meeting/[id]/page.tsx
  packages/web/src/features/meeting/components/MeetingAnnouncementFrame.tsx
  packages/web/src/features/meeting/constants/getEnumType.ts
  packages/web/src/features/meeting/constants/meetingTemplate.ts
  packages/web/src/features/meeting/services/_mock/mockupMeetingDetail.ts
  packages/web/src/features/meeting/services/useDeleteMeeting.ts
  packages/web/src/features/meeting/services/useGetMeetingDegree.ts
  packages/web/src/features/meeting/services/useGetMeetingDetail.ts
  packages/web/src/utils/Date/formatDate.ts
Labels: front-end

#1112 impl meeting edit page
  packages/web/src/app/meeting/[id]/edit/page.tsx
  packages/web/src/features/meeting/components/MeetingAnnouncementFrame.tsx
  packages/web/src/features/meeting/components/MeetingInformationFrame.tsx
  packages/web/src/features/meeting/services/_mock/mockupMeetingDetail.ts
  packages/web/src/features/meeting/services/useUpdateMeeting.ts
Labels: front-end
