Repository sparcs-kaist/clubs, pull requests merged in 2024-05, with the labels that each got.

#73 54 impl activity certificate page
  packages/web/src/app/activity-certificate/page.tsx
  packages/web/src/common/components/Forms/DateRangeInput.tsx
  packages/web/src/common/components/Forms/IconButton.tsx
  packages/web/src/common/components/Forms/ItemNumberInput.tsx
  packages/web/src/common/components/Forms/_atomic/ErrorMessage.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoFirstFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoSecondFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoThirdFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/index.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateMainFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateNoticeFrame.tsx
  packages/web/src/features/activity-certificate/services/_mock/mockupUserInfo.ts
  packages/web/src/features/activity-certificate/services/useGetUserInfo.tsx
  packages/web/src/features/activity-certificate/types/activityCertificate.ts
Labels: enhancement, front-end

#105 55 impl common space page
  .eslintrc
  .prettierrc
  package.json
  packages/web/package.json
  packages/web/src/app/common-space/page.tsx
  packages/web/src/common/components/Card.tsx
  packages/web/src/common/components/Timetable/_atomic/TimetableCell.tsx
  packages/web/src/common/components/Timetable/_atomic/TimetableDateList.tsx
  packages/web/src/common/components/Timetable/_atomic/TimetableTable.tsx
  packages/web/src/common/components/Timetable/_atomic/TimetableTimeList.tsx
  packages/web/src/common/components/Timetable/_atomic/WeekNavigator.tsx
  packages/web/src/common/components/Timetable/index.tsx
  packages/web/src/common/components/Typography.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoFirstFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoSecondFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoThirdFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/index.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/mockCommonSpaceList.ts
  packages/web/src/features/common-space/frames/CommonSpaceMainFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceNoticeFrame.tsx
  packages/web/src/features/common-space/types/commonSpace.ts
  pnpm-lock.yaml
Labels: front-end

#91 53 impl printing business page
  packages/interface/src/api/promotional-printing/endpoint/apiPrt002.ts
  packages/interface/src/common/type/phoneNumber.type.ts
  packages/web/src/app/printing-business/page.tsx
  packages/web/src/common/components/Button.tsx
  packages/web/src/common/components/Checkbox.tsx
  packages/web/src/common/components/Icon.tsx
  packages/web/src/constants/printingBusiness.ts
  packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/DesiredPickUpTimeSelection.tsx
  packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/_atomic/SingleDateSelectionCalendar.tsx
  packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/_atomic/TimeSlotList.tsx
  packages/web/src/features/printing-business/component/FileUpload.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormFirst.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormSecond.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormThird.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/_atomic/BinaryRadio.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/_atomic/FormCheck.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/index.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessNotice.tsx
  packages/web/src/features/printing-business/frame/PrintingBusinessMainFrame.tsx
  packages/web/src/features/printing-business/service/_mock/mockupUserProfile.ts
  packages/web/src/features/printing-business/service/getUserProfile.ts
  packages/web/src/features/printing-business/service/postBusinessPrintingOrder.ts
Labels: front-end

#138 137 impl printing business page - enhancement
  packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/_atomic/TimeSlotList.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormThird.tsx
  packages/web/src/features/printing-business/frame/PrintingBusinessMainFrame.tsx
Labels: enhancement, front-end

#76 68 My Club Page - Club Type Error
  packages/interface/src/api/club/endpoint/apiClb002.ts
  packages/interface/src/api/club/endpoint/apiClb003.ts
  packages/web/src/app/my/page.tsx
  packages/web/src/features/my/frames/MyPageMainFrame.tsx
  packages/web/src/features/my/service/_mock/mockMyClubList.ts
  packages/web/src/features/my/service/useGetMyClub.ts
  packages/web/src/features/my/types/mockMyClubList.ts
  packages/web/src/types/myClubs.types.ts
Labels: front-end

#126 Typography support custom styles and awesome types
  packages/web/src/common/components/Typography.tsx
Labels: front-end

#145 117 Impl Manage Club > Funding List Page
  packages/web/src/app/manage-club/funding/page.tsx
  packages/web/src/common/components/Table/TableCell.tsx
  packages/web/src/constants/manageClubFunding.ts
  packages/web/src/features/manage-club/funding/component/NewFundingListSection.tsx
  packages/web/src/features/manage-club/funding/component/PastFundingListSection.tsx
  packages/web/src/features/manage-club/funding/component/_atomic/FoldableSectionTitle.tsx
  packages/web/src/features/manage-club/funding/component/_atomic/NewFundingListTable.tsx
  packages/web/src/features/manage-club/funding/component/_atomic/PastFundingListTable.tsx
  packages/web/src/features/manage-club/funding/component/_atomic/PastSingleSemesterFundingListSection.tsx
  packages/web/src/features/manage-club/funding/frame/ManageClubFundingMainFrame.tsx
Labels: front-end

#120 119 add RNT003, PRT001, ACF003, CMS006 and matched Enums
  packages/interface/src/api/activity-certificate/endpoint/apiAcf003.ts
  packages/interface/src/api/common-space/endpoint/apiCms006.ts
  packages/interface/src/api/promotional-printing/endpoint/apiPrt001.ts
  packages/interface/src/api/rental/endpoint/apiRnt003.ts
  packages/interface/src/common/enum/activityCertificate.enum.ts
  packages/interface/src/common/enum/commonSpace.enum.ts
  packages/interface/src/common/enum/promotionalPrinting.enum.ts
  packages/interface/src/common/enum/rental.enum.ts
Labels: back-end

#134 Impl api Clb009 Clb010 interface
  packages/interface/src/api/club/endpoint/apiClb009.ts
  packages/interface/src/api/club/endpoint/apiClb010.ts
  packages/interface/src/api/club/index.ts
Labels: back-end

#121 feat: impl clb-002
  packages/api/src/common/repository/club.club-student-t.repository.ts
  packages/api/src/common/repository/club.repository.ts
  packages/api/src/common/repository/user.repository.ts
  packages/api/src/common/util/util.ts
  packages/api/src/drizzle/schema/club.schema.ts
  packages/api/src/feature/club/club.module.ts
  packages/api/src/feature/club/controller/club.controller.ts
  packages/api/src/feature/club/repository/club.club-representative-d.repository.ts
  packages/api/src/feature/club/repository/club.club-room-t.repository.ts
  packages/api/src/feature/club/repository/club.repository.ts
  packages/api/src/feature/club/service/club.service.ts
  packages/api/src/feature/user/controller/user.controller.ts
  packages/api/src/feature/user/user.module.ts
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoSecondFrame.tsx
Labels: back-end

#153 Card Component Refactoring
  packages/web/src/common/components/Card.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoFirstFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoSecondFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoThirdFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateNoticeFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoFirstFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoSecondFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoThirdFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceNoticeFrame.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormFirst.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormSecond.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormThird.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessNotice.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoFirstFrame.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoSecondFrame.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoThirdFrame.tsx
  packages/web/src/features/rental-business/frames/RentalNoticeFrame.tsx
Labels: front-end

#171 170 Fix PRT001 parameters and attributes
  packages/interface/src/api/promotional-printing/endpoint/apiPrt001.ts
Labels: interface

#166 feat: impl Rental Schema and RNT-001
  packages/api/src/app.module.ts
  packages/api/src/drizzle/schema/rental.schema.ts
  packages/api/src/feature/rental/controller/rental.controller.ts
  packages/api/src/feature/rental/dto/rental.dto.ts
  packages/api/src/feature/rental/rental.module.ts
  packages/api/src/feature/rental/repository/rental.rental-object.repository.ts
  packages/api/src/feature/rental/service/rental.service.ts
Labels: back-end, interface

#146 Impl cms001 on progress
  packages/api/src/app.module.ts
  packages/api/src/drizzle/schema/common-space.schema.ts
  packages/api/src/feature/commonspace/common-space.module.ts
  packages/api/src/feature/commonspace/controller/common-space.controller.ts
  packages/api/src/feature/commonspace/repository/common-space.repository.ts
  packages/api/src/feature/commonspace/service/common-space.service.ts
Labels: back-end

#163 162 Implement PromotionalPrinting Schema and PRT-001
  packages/api/src/app.module.ts
  packages/api/src/drizzle/drizzle.provider.ts
  packages/api/src/drizzle/schema/promotional-printing.schema.ts
  packages/api/src/feature/promotional-printing/controller/promotional-printing.controller.ts
  packages/api/src/feature/promotional-printing/dto/promotional-printing.dto.ts
  packages/api/src/feature/promotional-printing/promotional-printing.exception.ts
  packages/api/src/feature/promotional-printing/promotional-printing.module.ts
  packages/api/src/feature/promotional-printing/repository/promotional-printing-order-size.repository.ts
  packages/api/src/feature/promotional-printing/repository/promotional-printing-order.repository.ts
  packages/api/src/feature/promotional-printing/service/promotional-printing.service.ts
Labels: back-end

#184 fix: fix acf001 phoneNumber
  packages/interface/src/api/activity-certificate/endpoint/apiAcf001.ts
Labels: interface

#181 124 Add log level into backend
  packages/api/src/common/util/logger.ts
  packages/api/src/feature/notice/controller/notice.controller.ts
Labels: back-end

#135 feat: impl MobileNavMenu
  packages/web/src/common/components/Header/index.tsx
  packages/web/src/common/components/NavTools/MobileNavItem.tsx
  packages/web/src/common/components/NavTools/MobileNavMenu.tsx
Labels: front-end

#180 feat: zod pipe
  packages/api/src/common/pipes/zod-pipe.ts
  packages/api/src/feature/rental/controller/rental.controller.ts
  packages/interface/src/api/rental/endpoint/apiRnt001.ts
Labels: back-end

#186 impl acf 001 api
  packages/api/src/app.module.ts
  packages/api/src/drizzle/drizzle.provider.ts
  packages/api/src/drizzle/schema/activity-certificate.schema.ts
  packages/api/src/feature/activity-certificate/activity-certificate.module.ts
  packages/api/src/feature/activity-certificate/controller/activity-certificate.controller.ts
  packages/api/src/feature/activity-certificate/repository/activity-certificate.repository.ts
  packages/api/src/feature/activity-certificate/service/activity-certificate.service.ts
  packages/interface/src/api/activity-certificate/endpoint/apiAcf001.ts
Labels: back-end

#203 remove foldableSectionTitle in club
  packages/web/src/features/clubs/components/FoldableSectionTitle.tsx
  packages/web/src/features/clubs/frames/ClubsSectionFrame.tsx
Labels: front-end

#172 StyledCard Refactoring
  packages/web/src/common/components/Card.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoFirstFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoSecondFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoThirdFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateNoticeFrame.tsx
  packages/web/src/features/clubDetails/components/ClubDetailCard.tsx
  packages/web/src/features/clubDetails/components/ClubInfoCard.tsx
  packages/web/src/features/clubDetails/components/PersonInfoCard.tsx
  packages/web/src/features/clubs/components/ClubCard.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoFirstFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoSecondFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoThirdFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceNoticeFrame.tsx
  packages/web/src/features/landing/components/ServiceCard.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormFirst.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormSecond.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormThird.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessNotice.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoFirstFrame.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoSecondFrame.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoThirdFrame.tsx
  packages/web/src/features/rental-business/frames/RentalNoticeFrame.tsx
Labels: front-end

#185 175 impl manage club page
  packages/web/src/app/manage-club/funding/page.tsx
  packages/web/src/app/manage-club/page.tsx
  packages/web/src/common/components/Table/TableWrapper.tsx
  packages/web/src/features/manage-club/component/ActivityCertificateTable.tsx
  packages/web/src/features/manage-club/component/ActivityReportTable.tsx
  packages/web/src/features/manage-club/component/CommonSpaceTable.tsx
  packages/web/src/features/manage-club/component/FundingTable.tsx
  packages/web/src/features/manage-club/component/ManageFrameWrapper.tsx
  packages/web/src/features/manage-club/component/MembersTable.tsx
  packages/web/src/features/manage-club/component/MoreDetailTitle.tsx
  packages/web/src/features/manage-club/component/PrintingTable.tsx
  packages/web/src/features/manage-club/component/RentalTable.tsx
  packages/web/src/features/manage-club/frame/ManageClubMainFrame.tsx
  packages/web/src/features/manage-club/frame/_atomic/ActivityManageFrame.tsx
  packages/web/src/features/manage-club/frame/_atomic/InfoManageFrame.tsx
  packages/web/src/features/manage-club/frame/_atomic/MembersManageFrame.tsx
  packages/web/src/features/manage-club/frame/_atomic/ServiceManageFrame.tsx
  packages/web/src/features/manage-club/service/_mock/mockManageClub.ts
  packages/web/src/utils/Date/formateDate.ts
Labels: front-end

#191 fix: clb-001 test complete
  packages/api/src/common/repository/club.repository.ts
Labels: back-end

#238 impl progress state checker
  packages/web/src/common/components/ProgressCheckSection/_atomic/Progress.tsx
  packages/web/src/common/components/ProgressCheckSection/_atomic/ProgressDot.tsx
  packages/web/src/common/components/ProgressCheckSection/_atomic/ProgressLine.tsx
  packages/web/src/common/components/ProgressCheckSection/index.tsx
  packages/web/src/common/components/Typography.tsx
  packages/web/src/utils/Date/formateDate.ts
Labels: enhancement, front-end

#201 impl acf 002 api
  packages/api/src/common/repository/club.repository.ts
  packages/api/src/feature/activity-certificate/activity-certificate.module.ts
  packages/api/src/feature/activity-certificate/controller/activity-certificate.controller.ts
  packages/api/src/feature/activity-certificate/service/activity-certificate.service.ts
  packages/interface/src/api/activity-certificate/endpoint/apiAcf002.ts
Labels: back-end, interface

#244 impl login profile selection
  packages/web/src/app/layout.tsx
  packages/web/src/common/components/Header/_atomic/Login.tsx
  packages/web/src/common/components/MyMenu/_atomic/Profile.tsx
  packages/web/src/common/components/MyMenu/_atomic/ProfileList.tsx
  packages/web/src/common/components/MyMenu/index.tsx
  packages/web/src/common/components/NavTools/MobileNavMenu.tsx
  packages/web/src/common/providers/AuthContext.tsx
Labels: front-end

#250 feat: impl nav close
  packages/web/src/common/components/NavTools/MobileNavMenu.tsx
Labels: enhancement, front-end

#275 Fix notice bugs and add onlClick event
  packages/web/src/app/page.tsx
  packages/web/src/constants/mainPage.ts
  packages/web/src/features/landing/components/NoticeCard.tsx
  packages/web/src/features/landing/frames/MainPageMainFrame.tsx
  packages/web/src/features/landing/frames/NoticeSectionFrame.tsx
  packages/web/src/features/notice/types/mockupNoticeList.ts
  packages/web/src/features/notice/types/notice.type.ts
  packages/web/src/features/notices/components/NoticeList.tsx
  packages/web/src/features/notices/frames/NoticeListAndPaginationFrame.tsx
Labels: front-end

#277 feat: impl mymenu onclose
  packages/web/src/common/components/Header/_atomic/Login.tsx
  packages/web/src/common/components/MyMenu/_atomic/ProfileList.tsx
  packages/web/src/common/components/MyMenu/index.tsx
Labels: front-end

#283 Fix dom element prop console error
  packages/web/next.config.mjs
  packages/web/package.json
  packages/web/src/common/components/Calendar/_atomic/CalendarDate.tsx
  packages/web/src/common/components/Card.tsx
  packages/web/src/common/components/Filter/_atomic/FilterButton.tsx
  packages/web/src/common/components/FoldableSection.tsx
  packages/web/src/common/components/Forms/ItemNumberInput.tsx
  packages/web/src/common/components/Forms/Select.tsx
  packages/web/src/common/components/Icon.tsx
  packages/web/src/common/components/NavTools/NavItem.tsx
  packages/web/src/common/components/Radio/index.tsx
  packages/web/src/common/components/Timetable/_atomic/TimetableDateList.tsx
  packages/web/src/common/components/Timetable/_atomic/TimetableTable.tsx
  packages/web/src/common/components/Toggle.tsx
  packages/web/src/common/components/Typography.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoThirdFrame.tsx
  packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/DesiredPickUpTimeSelection.tsx
  packages/web/src/features/printing-business/component/DesiredPickUpTimeSelection/_atomic/TimeSlotList.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/_atomic/BinaryRadio.tsx
  packages/web/src/features/rental-business/components/ItemButton.tsx
  packages/web/src/features/rental-business/components/RentalList.tsx
  pnpm-lock.yaml
Labels: front-end

#281 feat: add bread crumb to notice page
  packages/web/src/features/activity-certificate/frames/ActivityCertificateMainFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceMainFrame.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportCreateFrame.tsx
  packages/web/src/features/notices/frames/NoticePageMainFrame.tsx
  packages/web/src/features/printing-business/frame/PrintingBusinessMainFrame.tsx
  packages/web/src/features/rental-business/frames/RentalMainFrame.tsx
Labels: front-end

#285 refactor pageheadwrapper
  packages/web/src/app/clubs/page.tsx
  packages/web/src/app/manage-club/activity-certificate/page.tsx
  packages/web/src/app/manage-club/common-space/page.tsx
  packages/web/src/app/manage-club/funding/page.tsx
  packages/web/src/app/manage-club/members/page.tsx
  packages/web/src/app/manage-club/printing-business/page.tsx
  packages/web/src/app/manage-club/rental-business/page.tsx
  packages/web/src/common/components/PageHead/_atomic/BreadCrumb.tsx
  packages/web/src/common/components/PageHead/_atomic/BreadCrumbItem.tsx
  packages/web/src/common/components/PageHead/_atomic/PageTitle.tsx
  packages/web/src/common/components/PageHead/index.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateMainFrame.tsx
  packages/web/src/features/clubDetails/frames/ClubDetailMainFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceMainFrame.tsx
  packages/web/src/features/landing/frames/MainPageMainFrame.tsx
  packages/web/src/features/manage-club/activity-certificate/frame/ManageCertificateDetailFrame.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportCreateFrame.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportMainFrame.tsx
  packages/web/src/features/manage-club/common-space/frame/ManageCommonSpaceDetailFrame.tsx
  packages/web/src/features/manage-club/frame/ManageClubMainFrame.tsx
  packages/web/src/features/manage-club/printing/frame/ManagePringtingDetailFrame.tsx
  packages/web/src/features/manage-club/rental/frame/ManageRentalDetailFrame.tsx
  packages/web/src/features/my/clubs/frames/MyClubsMainFrame.tsx
  packages/web/src/features/my/frame/MyPageMainFrame.tsx
  packages/web/src/features/notices/frames/NoticePageMainFrame.tsx
  packages/web/src/features/printing-business/frame/PrintingBusinessMainFrame.tsx
  packages/web/src/features/rental-business/frames/RentalMainFrame.tsx
Labels: enhancement, front-end
