Repository sparcs-kaist/clubs, pull requests merged in 2024-06, with the labels that each got.

#287 fix: fix blur error in safari
  packages/web/src/common/components/Header/index.tsx
Labels: bug, front-end

#158 144 impl services for rental business
  packages/api/src/feature/rental/repository/rental.rental-object.repository.ts
  packages/interface/src/api/rental/endpoint/apiRnt001.ts
  packages/web/src/common/components/Forms/ItemNumberInput.tsx
  packages/web/src/common/components/Radio/RadioOption.tsx
  packages/web/src/features/manage-club/component/ActivityReportTable.tsx
  packages/web/src/features/manage-club/component/CommonSpaceTable.tsx
  packages/web/src/features/manage-club/component/RentalTable.tsx
  packages/web/src/features/my/component/MyActivityCertificateTable.tsx
  packages/web/src/features/my/component/MyCommonSpaceTable.tsx
  packages/web/src/features/rental-business/components/Rentals/Easel.tsx
  packages/web/src/features/rental-business/components/Rentals/HandCart.tsx
  packages/web/src/features/rental-business/components/Rentals/Mat.tsx
  packages/web/src/features/rental-business/components/Rentals/Tool.tsx
  packages/web/src/features/rental-business/components/Rentals/Vacuum.tsx
  packages/web/src/features/rental-business/components/SelectRangeCalendar/SelectRangeCalendar.tsx
  packages/web/src/features/rental-business/components/SelectRangeCalendar/_atomic/RangeCalendar.tsx
  packages/web/src/features/rental-business/components/SelectRangeCalendar/_atomic/SelectRange.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoFirstFrame.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoSecondFrame.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoThirdFrame.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/index.tsx
  packages/web/src/features/rental-business/frames/RentalNoticeFrame.tsx
  packages/web/src/features/rental-business/service/_mock/mockAvailableRental.ts
  packages/web/src/features/rental-business/service/postRentalOrder.ts
  packages/web/src/features/rental-business/types/rental.ts
Labels: front-end, interface

#294 impl credits page
  packages/web/src/app/credits/page.tsx
  packages/web/src/assets/sparcs-orange.svg
  packages/web/src/features/credits/components/MemberCard.tsx
  packages/web/src/features/credits/credits.ts
  packages/web/src/features/credits/frames/CreditsMainFrame.tsx
  packages/web/src/styles/themes/colors.ts
  packages/web/src/styles/themes/fonts.ts
Labels: enhancement, front-end

#297 impl flexwrapper
  packages/web/src/app/manage-club/members/page.tsx
  packages/web/src/app/manage-club/printing-business/[id]/page.tsx
  packages/web/src/common/components/FlexWrapper.tsx
  packages/web/src/common/components/Modal/CancellableModalContent.tsx
  packages/web/src/common/components/Modal/ConfirmModalContent.tsx
  packages/web/src/common/components/ProgressCheckSection/ProgressCheckSectionWrapper.tsx
  packages/web/src/common/components/Table/TableButtonCell.tsx
  packages/web/src/features/clubDetails/components/ClubDetailCard.tsx
  packages/web/src/features/clubDetails/frames/ClubDetailMainFrame.tsx
  packages/web/src/features/clubs/components/ClubCard.tsx
  packages/web/src/features/clubs/frames/ClubsPageMainFrame.tsx
  packages/web/src/features/clubs/frames/ClubsSectionFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/index.tsx
  packages/web/src/features/common-space/frames/CommonSpaceMainFrame.tsx
  packages/web/src/features/landing/frames/MainPageMainFrame.tsx
  packages/web/src/features/manage-club/activity-certificate/frame/ManageCertificateDetailFrame.tsx
  packages/web/src/features/manage-club/common-space/frame/ManageCommonSpaceDetailFrame.tsx
  packages/web/src/features/manage-club/component/ManageFrameWrapper.tsx
  packages/web/src/features/manage-club/frame/ManageClubMainFrame.tsx
  packages/web/src/features/manage-club/frame/_atomic/ActivityManageFrame.tsx
  packages/web/src/features/manage-club/frame/_atomic/InfoManageFrame.tsx
  packages/web/src/features/manage-club/frame/_atomic/MembersManageFrame.tsx
  packages/web/src/features/manage-club/frame/_atomic/ServiceManageFrame.tsx
  packages/web/src/features/manage-club/members/components/AllMemberList.tsx
  packages/web/src/features/manage-club/members/components/MemberSearchAndFilter.tsx
  packages/web/src/features/manage-club/members/components/RegisterMemberList.tsx
  packages/web/src/features/manage-club/members/frames/AllMemberListFrame.tsx
  packages/web/src/features/manage-club/members/frames/RegisterMemberListFrame.tsx
  packages/web/src/features/manage-club/printing/frame/ManagePrintingDetailFrame.tsx
  packages/web/src/features/manage-club/rental/frame/ManageRentalDetailFrame.tsx
  packages/web/src/features/my/clubs/frames/MyClubsMainFrame.tsx
  packages/web/src/features/my/frame/MyPageMainFrame.tsx
  packages/web/src/features/my/frame/_atomic/MyClubFrame.tsx
  packages/web/src/features/my/frame/_atomic/MyInfoFrame.tsx
  packages/web/src/features/my/frame/_atomic/MyServiceFrame.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/index.tsx
  packages/web/src/features/printing-business/frame/PrintingBusinessMainFrame.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoThirdFrame.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/index.tsx
  packages/web/src/features/rental-business/frames/RentalMainFrame.tsx
Labels: enhancement, front-end

#292 select refactoring
  packages/web/src/common/components/Filter/_atomic/FilterDropdown.tsx
  packages/web/src/common/components/FormError.tsx
  packages/web/src/common/components/FormLabel.tsx
  packages/web/src/common/components/Forms/DateRangeInput.tsx
  packages/web/src/common/components/Forms/ItemNumberInput.tsx
  packages/web/src/common/components/Forms/TextInput.tsx
  packages/web/src/common/components/Select/Dropdown.tsx
  packages/web/src/common/components/Select/SelectOption.tsx
  packages/web/src/common/components/Select/_atomic/NoOption.tsx
  packages/web/src/common/components/Select/index.tsx
  packages/web/src/common/components/SelectedItem.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoFirstFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoFirstFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoSecondFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/mockCommonSpaceList.ts
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportCreateFrame.tsx
  packages/web/src/features/manage-club/frame/_atomic/InfoManageFrame.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormFirst.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoFirstFrame.tsx
Labels: front-end

#302 295 add fonts
  packages/web/src/app/layout.tsx
  packages/web/src/features/credits/components/MemberCard.tsx
  packages/web/src/styles/fonts/googleFonts.ts
  packages/web/src/styles/fonts/local/NanumSquare-ExtraBold.woff2
  packages/web/src/styles/fonts/local/RalewayVariable.woff2
  packages/web/src/styles/themes/fonts.ts
Labels: front-end

#293 impl interface acf 004 007
  packages/interface/src/api/activity-certificate/endpoint/apiAcf004.ts
  packages/interface/src/api/activity-certificate/endpoint/apiAcf007.ts
Labels: enhancement, interface

#189 179 Implement PRT-002
  .eslintrc
  packages/api/src/common/repository/club.repository.ts
  packages/api/src/drizzle/schema/promotional-printing.schema.ts
  packages/api/src/feature/promotional-printing/controller/promotional-printing.controller.ts
  packages/api/src/feature/promotional-printing/dto/promotional-printing.dto.ts
  packages/api/src/feature/promotional-printing/promotional-printing.module.ts
  packages/api/src/feature/promotional-printing/repository/promotional-printing-order.repository.ts
  packages/api/src/feature/promotional-printing/service/promotional-printing.service.ts
  packages/interface/src/api/promotional-printing/endpoint/apiPrt002.ts
  packages/interface/src/common/enum/promotionalPrinting.enum.ts
Labels: back-end

#307 Implement PRT-005 interface and API
  packages/api/src/feature/promotional-printing/controller/promotional-printing.controller.ts
  packages/api/src/feature/promotional-printing/dto/promotional-printing.dto.ts
  packages/api/src/feature/promotional-printing/repository/promotional-printing-order-size.repository.ts
  packages/api/src/feature/promotional-printing/repository/promotional-printing-order.repository.ts
  packages/api/src/feature/promotional-printing/service/promotional-printing.service.ts
  packages/interface/src/api/promotional-printing/endpoint/apiPrt005.ts
  packages/interface/src/api/promotional-printing/index.ts
Labels: enhancement, back-end, interface

#330 pagination component refactoring
  packages/web/src/common/components/Pagination.tsx
  packages/web/src/features/manage-club/members/components/RegisterMemberList.tsx
  packages/web/src/features/manageClubTable/frames/ManageClubTableMainFrame.tsx
  packages/web/src/features/notices/frames/NoticeListAndPaginationFrame.tsx
Labels: front-end
