Repository sparcs-kaist/clubs, pull requests merged in 2024-12, with the labels that each got.

#1241 Merge dev into main
  packages/api/src/feature/club/club.module.ts
  packages/api/src/feature/club/delegate/delegate.module.ts
Labels: release

#1240 update return value of selectExecutiveMeetingNextDegree function
  packages/api/src/feature/meeting/meeting.repository.ts
Labels: back-end

#1247 create story for radio and checkbox
  packages/web/package.json
  packages/web/src/stories/Checkbox.stories.tsx
  packages/web/src/stories/Radio.stories.tsx
  packages/web/src/stories/RadioOption.stories.tsx
  pnpm-lock.yaml
Labels: enhancement, front-end

#1213 1211 add select component for react hook form
  packages/web/src/app/meeting/[id]/edit/page.tsx
  packages/web/src/app/meeting/announcement/create/page.tsx
  packages/web/src/common/components/FormController.tsx
  packages/web/src/common/components/Select/Form/index.tsx
  packages/web/src/features/meeting/components/MeetingAnnouncementForm.tsx
  packages/web/src/features/meeting/components/MeetingInformationFrame.tsx
  packages/web/src/features/meeting/types/meeting.ts
Labels: front-end

#1236 add apiMee012
  packages/api/src/feature/meeting/announcement/announcement.controller.ts
  packages/api/src/feature/meeting/announcement/announcement.service.ts
  packages/api/src/feature/meeting/meeting.repository.ts
  packages/interface/src/api/meeting/apiMee012.ts
  packages/interface/src/common/enum/meeting.enum.ts
Labels: back-end

#1251 fix layout for change representative
  packages/web/src/features/manage-club/components/ChangeClubInfoCard.tsx
  packages/web/src/features/manage-club/frames/InfoManageFrame.tsx
Labels: bug, front-end

#1237 1221 apply apiMee012
  packages/web/src/app/meeting/[id]/page.tsx
  packages/web/src/app/meeting/page.tsx
  packages/web/src/constants/paths.ts
  packages/web/src/features/meeting/components/MeetingInformationFrame.tsx
  packages/web/src/features/meeting/components/MeetingNoticeItem.tsx
  packages/web/src/features/meeting/constants/getEnumType.ts
  packages/web/src/features/meeting/constants/index.tsx
  packages/web/src/features/meeting/services/_mock/mockupMeetingNotice.ts
  packages/web/src/features/meeting/services/_mock/mockupMeetings.ts
  packages/web/src/features/meeting/services/useGetMeetings.ts
  packages/web/src/features/meeting/types/meeting.ts
Labels: front-end

#1203 impl status change for changing representative delegate
  packages/api/src/feature/club/delegate/club.club-delegate-d.repository.ts
  packages/api/src/feature/club/delegate/delegate.service.ts
  packages/interface/src/api/club/endpoint/apiClb013.ts
  packages/web/src/app/my/page.tsx
  packages/web/src/features/manage-club/components/ChangeRepresentativeCard.tsx
  packages/web/src/features/manage-club/components/ChangeRepresentativeCardV1.tsx
  packages/web/src/features/manage-club/components/ChangeRepresentativeInfo.tsx
  packages/web/src/features/manage-club/frames/_atomic/RepresentativeLoadFrame.tsx
  packages/web/src/features/my/components/ChangeDivisionPresidentModalContent.tsx
  packages/web/src/features/my/components/ChangeRepresentativeModalContent.tsx
  packages/web/src/features/my/components/MyChangeRepresentative.tsx
  packages/web/src/features/my/frames/MyChangesFrame.tsx
  packages/web/src/features/my/services/_mock/mockMyDelegateChange.ts
Labels: enhancement, front-end

#1256 modify delegate change logic
  packages/api/src/feature/club/delegate/delegate.service.ts
  packages/api/src/feature/user/controller/user.controller.ts
  packages/api/src/feature/user/repository/student.repository.ts
  packages/api/src/feature/user/service/user.public.service.ts
  packages/api/src/feature/user/service/user.service.ts
  packages/interface/src/api/club/endpoint/apiClb011.ts
  packages/interface/src/api/club/endpoint/apiClb013.ts
  packages/web/src/features/manage-club/components/ChangeRepresentativeCard.tsx
  packages/web/src/features/manage-club/services/_mock/mockDelegate.ts
  packages/web/src/features/my/frames/MyChangesFrame.tsx
  packages/web/src/features/my/services/_mock/mockMyDelegateChange.ts
Labels: enhancement, back-end

#1259 fix change representative
  packages/api/src/feature/club/delegate/club.club-delegate-d.repository.ts
  packages/api/src/feature/club/delegate/delegate.service.ts
  packages/web/src/features/manage-club/components/ChangeRepresentativeCard.tsx
  packages/web/src/features/my/components/ChangeRepresentativeModalContent.tsx
  packages/web/src/features/my/components/MyChangeRepresentative.tsx
Labels: bug, front-end, back-end

#1255 connect apiAct005, apiAct006
  packages/api/src/feature/activity/controller/activity.activity-term.controller.ts
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/service/activity.activity-term.service.ts
  packages/interface/src/api/activity/endpoint/apiAct005.ts
  packages/interface/src/api/activity/endpoint/apiAct006.ts
  packages/interface/src/api/activity/endpoint/apiAct009.ts
  packages/web/src/features/manage-club/activity-report/components/NewActivityReportList.tsx
  packages/web/src/features/manage-club/activity-report/components/PastActivityReportList.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportMainFrame.tsx
  packages/web/src/features/manage-club/activity-report/services/useGetActivityTerms.tsx
  packages/web/src/features/manage-club/activity-report/services/useGetNewActivityReportList.tsx
  packages/web/src/features/manage-club/activity-report/services/useGetPastActivityReportList.tsx
  packages/web/src/features/manage-club/activity-report/types/activityReport.ts
  packages/web/src/features/register-club/components/ActivityReportFrame.tsx
  packages/web/src/features/register-club/components/ActivityReportList.tsx
  packages/web/src/features/register-club/types/registerClub.ts
Labels: front-end

#1271 Fix refetch problem with activity report
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportCreateFrame.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailFrame.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportEditFrame.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportMainFrame.tsx
Labels: enhancement, front-end

#1285 connect apiFnd005
  packages/api/src/feature/funding/funding.controller.ts
  packages/api/src/feature/funding/funding.service.ts
  packages/interface/src/api/funding/endpoint/apiFnd005.ts
  packages/web/src/app/manage-club/funding/page.tsx
  packages/web/src/constants/tableTagList.ts
  packages/web/src/features/manage-club/funding/components/NewFundingListSection.tsx
  packages/web/src/features/manage-club/funding/components/_atomic/NewFundingListTable.tsx
  packages/web/src/features/manage-club/funding/services/useGetNewFundingList.ts
  packages/web/src/features/manage-club/funding/types/funding.ts
  packages/web/src/features/manage-club/services/_mock/mockManageClub.ts
Labels: front-end

#605 fix fnd api
  packages/api/src/feature/file/service/file.public.service.ts
  packages/api/src/feature/funding/funding.controller.ts
  packages/api/src/feature/funding/funding.repository.ts
  packages/api/src/feature/funding/funding.service.ts
  packages/interface/src/api/funding/apiFnd001.ts
  packages/interface/src/api/funding/apiFnd002.ts
  packages/interface/src/api/funding/apiFnd003.ts
  packages/interface/src/api/funding/apiFnd004.ts
  packages/interface/src/api/funding/apiFnd005.ts
  packages/interface/src/api/funding/apiFnd006.ts
  packages/interface/src/api/funding/index.ts
  packages/web/src/features/manage-club/funding/services/useGetNewFundingList.ts
  packages/web/src/features/manage-club/services/_mock/mockFundingDetail.ts
Labels: bug, back-end
