Repository sparcs-kaist/clubs, pull requests merged in 2024-08, with the labels that each got.

#502 connect backend for changing representative delegate
  packages/interface/src/api/club/endpoint/apiClb008.ts
  packages/interface/src/api/club/endpoint/apiClb009.ts
  packages/interface/src/api/club/endpoint/apiClb010.ts
  packages/interface/src/api/club/endpoint/apiClb011.ts
  packages/interface/src/api/club/endpoint/apiClb012.ts
  packages/web/src/app/manage-club/funding/[id]/edit/page.tsx
  packages/web/src/app/my/activity-certificate/page.tsx
  packages/web/src/app/my/common-space/page.tsx
  packages/web/src/app/my/page.tsx
  packages/web/src/app/my/printing-business/page.tsx
  packages/web/src/app/my/rental-business/page.tsx
  packages/web/src/common/components/Select/index.tsx
  packages/web/src/common/components/Table/TableButton.tsx
  packages/web/src/constants/tableTagList.ts
  packages/web/src/features/manage-club/components/ActivityReportTable.tsx
  packages/web/src/features/manage-club/components/ChangeRepresentative.tsx
  packages/web/src/features/manage-club/components/ChangeRepresentativeCard.tsx
  packages/web/src/features/manage-club/components/FundingTable.tsx
  packages/web/src/features/manage-club/components/MembersTable.tsx
  packages/web/src/features/manage-club/frames/ActivityManageFrame.tsx
  packages/web/src/features/manage-club/frames/InfoManageFrame.tsx
  packages/web/src/features/manage-club/frames/MembersManageFrame.tsx
  packages/web/src/features/manage-club/frames/ServiceManageFrame.tsx
  packages/web/src/features/manage-club/funding/components/_atomic/NewFundingListTable.tsx
  packages/web/src/features/manage-club/funding/components/_atomic/PastFundingListTable.tsx
  packages/web/src/features/manage-club/funding/detail/components/FixtureEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/components/FundingInfoList.tsx
  packages/web/src/features/manage-club/funding/detail/components/NonCorpEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/components/TransportationEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
  packages/web/src/features/manage-club/services/_mock/mockDelegate.ts
  packages/web/src/features/manage-club/services/_mock/mockFundingDetail.ts
  packages/web/src/features/manage-club/services/_mock/mockManageClub.ts
  packages/web/src/features/manage-club/services/deleteChangeDelegateRequest.ts
  packages/web/src/features/manage-club/services/getChangeDelegateRequests.ts
  packages/web/src/features/manage-club/services/getClubDelegate.ts
  packages/web/src/features/manage-club/services/getDelegateCandidates.ts
  packages/web/src/features/manage-club/services/updateClubDelegate.ts
  packages/web/src/features/my/component/ChangeRepresentativeModalContent.tsx
  packages/web/src/features/my/component/MyChangeRepresentative.tsx
  packages/web/src/features/my/frame/MyServiceFrame.tsx
  packages/web/src/features/my/services/_mock/mockMyClub.ts
  packages/web/src/features/my/services/_mock/mockMyDelegateChange.ts
  packages/web/src/features/my/services/getMyActivityCertificate.ts
  packages/web/src/features/my/services/getMyCommonSpace.ts
  packages/web/src/features/my/services/getMyDelegateRequest.ts
  packages/web/src/features/my/services/getMyPrinting.ts
  packages/web/src/features/my/services/getMyRentals.ts
  packages/web/src/features/my/services/patchMyDelegateRequest.ts
Labels: enhancement, front-end

#528 Impl manage division > division information
  packages/web/src/app/manage-division/page.tsx
  packages/web/src/features/manage-division/components/ChangeDivisionPresident.tsx
  packages/web/src/features/manage-division/components/ChangeDivisionPresidentCard.tsx
  packages/web/src/features/manage-division/components/DivisionInformationCard.tsx
  packages/web/src/features/manage-division/frames/DivisionInfoFrame.tsx
Labels: enhancement, good first issue, front-end

#523 add mock profile token
  packages/web/src/common/services/_mock/mockAccessToken.ts
Labels: enhancement, front-end

#538 Change division president ui
  packages/web/src/app/my/page.tsx
  packages/web/src/common/components/Buttons/TextButton.tsx
  packages/web/src/common/components/NotificationCard.tsx
  packages/web/src/constants/changeDivisionPresident.ts
  packages/web/src/features/manage-division/components/ChangeDivisionPresident.tsx
  packages/web/src/features/manage-division/components/ChangeDivisionPresidentCard.tsx
  packages/web/src/features/manage-division/components/DivisionInformationCard.tsx
  packages/web/src/features/manage-division/components/_atomic/DivisionCard.tsx
  packages/web/src/features/manage-division/frames/DivisionInfoFrame.tsx
  packages/web/src/features/my/component/ChangeDivisionPresidentModalContent.tsx
  packages/web/src/features/my/component/MyChangeDivisionPresident.tsx
Labels: enhancement, good first issue, front-end

#540 Implement Division module and DIV-001 interface + API
  packages/api/src/app.module.ts
  packages/api/src/feature/division/division.controller.ts
  packages/api/src/feature/division/division.module.ts
  packages/api/src/feature/division/division.repository.ts
  packages/api/src/feature/division/division.service.ts
  packages/interface/src/api/division/apiDiv001.ts
Labels: enhancement, back-end

#515 add react-hook-form
  packages/web/package.json
  packages/web/src/app/register-club/promotional/page.tsx
  packages/web/src/app/register-club/provisional/page.tsx
  packages/web/src/app/register-club/renewal/page.tsx
  packages/web/src/common/components/Button.tsx
  packages/web/src/common/components/FormController.tsx
  packages/web/src/common/components/Forms/IconButton.tsx
  packages/web/src/common/components/Forms/PhoneInput.tsx
  packages/web/src/common/components/Forms/TextInput.tsx
  packages/web/src/common/components/Select/index.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoFirstFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoFirstFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoSecondFrame.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportCreateFrame.tsx
  packages/web/src/features/manage-club/components/ChangeRepresentativeCard.tsx
  packages/web/src/features/manage-club/funding/components/FixtureEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/components/TransportEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/frames/FundingInfoFrame.tsx
  packages/web/src/features/manage-division/components/ChangeDivisionPresidentCard.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormFirst.tsx
  packages/web/src/features/register-club/components/AdvancedInformFrame.tsx
  packages/web/src/features/register-club/components/BasicInformFrame.tsx
  packages/web/src/features/register-club/components/ClubRegulationsComplianceSection.tsx
  packages/web/src/features/register-club/components/ProfessorInformFrame.tsx
  packages/web/src/features/register-club/components/_atomic/CreateActivityReportModal.tsx
  packages/web/src/features/register-club/components/_atomic/DivisionSelect.tsx
  packages/web/src/features/register-club/components/_atomic/MonthSelect.tsx
  packages/web/src/features/register-club/components/_atomic/YearSelect.tsx
  packages/web/src/features/register-club/frame/RegisterClubMainFrame.tsx
  packages/web/src/features/register-club/service/registerClub.ts
  packages/web/src/features/register-club/types/registerClub.ts
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoFirstFrame.tsx
  packages/web/src/utils/validator.ts
  pnpm-lock.yaml
Labels: front-end

#500 impl fnd 001 002 003 api
  packages/api/src/drizzle/schema/funding.schema.ts
  packages/api/src/feature/file/controller/file.controller.ts
  packages/api/src/feature/file/service/file.public.service.ts
  packages/api/src/feature/file/service/file.service.ts
  packages/api/src/feature/funding/controller/funding.controller.ts
  packages/api/src/feature/funding/funding.module.ts
  packages/api/src/feature/funding/repository/funding.repository.ts
  packages/api/src/feature/funding/service/funding.service.ts
  packages/api/src/feature/user/repository/student.repository.ts
  packages/api/src/feature/user/service/user.public.service.ts
  packages/interface/src/api/funding/endpoint/apiFnd001.ts
  packages/interface/src/api/funding/endpoint/apiFnd002.ts
  packages/interface/src/api/funding/endpoint/apiFnd003.ts
  packages/web/src/features/manage-club/funding/types/funding.ts
  packages/web/src/features/manage-club/services/_mock/mockFundingDetail.ts
Labels: enhancement, back-end

#545 modify clubdelegateenum
  packages/api/src/feature/club/service/club-delegate.service.ts
  packages/interface/src/api/club/endpoint/apiClb008.ts
  packages/interface/src/common/enum/club.enum.ts
  packages/web/src/features/manage-club/components/ChangeRepresentativeCard.tsx
  packages/web/src/features/manage-club/services/_mock/mockDelegate.ts
Labels: bug

#484 fix participant list
  packages/web/src/app/manage-club/funding/[id]/edit/page.tsx
  packages/web/src/app/manage-club/funding/create/page.tsx
  packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
  packages/web/src/features/manage-club/funding/component/NewFundingListSection.tsx
  packages/web/src/features/manage-club/funding/components/TransportEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/types/funding.ts
  packages/web/src/features/manage-club/services/_mock/mockFundingDetail.ts
Labels: bug, front-end

#520 feat: impl meeting detail page
  packages/web/src/app/meeting/[id]/page.tsx
  packages/web/src/features/meeting/services/_mock/mockupMeetingDetail.ts
  packages/web/src/features/meeting/types/meeting.ts
Labels: enhancement, front-end

#543 impl login change for clubs/id
  packages/web/src/app/clubs/[id]/page.tsx
  packages/web/src/features/clubDetails/frames/ClubDetailMainFrame.tsx
Labels: enhancement, front-end

#512 Impl modals for club member registration
  packages/web/src/features/clubs/components/ClubCard.tsx
Labels: enhancement, good first issue, front-end

#521 impl components for meeting announcement pages
  packages/web/src/common/components/Forms/DateInput.tsx
  packages/web/src/features/meeting/components/MeetingAnnouncementFrame.tsx
  packages/web/src/features/meeting/components/MeetingInformationFrame.tsx
  packages/web/src/features/meeting/constants/meetingTemplate.ts
  packages/web/src/features/meeting/types/meeting.ts
  packages/web/src/utils/getSemester.ts
Labels: front-end

#461 Add state save
  packages/web/src/common/components/Timetable/index.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoFirstFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoSecondFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoThirdFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/index.tsx
  packages/web/src/features/common-space/frames/CommonSpaceMainFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceNoticeFrame.tsx
  packages/web/src/features/common-space/service/getCommonSpaceUsageOrders.ts
  packages/web/src/features/common-space/service/getCommonSpaces.ts
  packages/web/src/features/common-space/types/commonSpace.ts
Labels: bug, front-end

#552 Impl division change flow
  packages/web/src/app/manage-division/page.tsx
  packages/web/src/app/my/page.tsx
  packages/web/src/common/components/Buttons/TextButton.tsx
  packages/web/src/common/components/FoldableSection.tsx
  packages/web/src/common/components/FoldableSectionTitle.tsx
  packages/web/src/common/components/NotificationCard.tsx
  packages/web/src/constants/changeDivisionPresident.ts
  packages/web/src/features/manage-club/funding/components/EvidenceBlockTitle.tsx
  packages/web/src/features/manage-club/funding/components/_atomic/PastSingleSemesterFundingListSection.tsx
  packages/web/src/features/manage-club/members/components/AllMemberList.tsx
  packages/web/src/features/manage-division/components/ChangeDivisionPresidentCard.tsx
  packages/web/src/features/my/components/ChangeDivisionPresidentModalContent.tsx
  packages/web/src/features/my/components/MyChangeDivisionPresident.tsx
  packages/web/src/features/my/components/MyChangeRepresentative.tsx
Labels: enhancement, good first issue, front-end

#562 Add TODO comments
  packages/web/src/app/manage-division/page.tsx
  packages/web/src/app/my/page.tsx
  packages/web/src/features/manage-division/components/ChangeDivisionPresidentCard.tsx
Labels: enhancement, good first issue, front-end

#564 Use Enum type for status && MoreInfo common component
  packages/web/src/app/my/page.tsx
  packages/web/src/common/components/Buttons/FoldUnfoldButton.tsx
  packages/web/src/common/components/Buttons/TextButton.tsx
  packages/web/src/constants/changeDivisionPresident.ts
  packages/web/src/features/manage-club/frames/ActivityManageFrame.tsx
  packages/web/src/features/manage-club/frames/InfoManageFrame.tsx
  packages/web/src/features/manage-club/frames/MembersManageFrame.tsx
  packages/web/src/features/manage-club/frames/ServiceManageFrame.tsx
  packages/web/src/features/manage-club/funding/components/NewFundingListSection.tsx
  packages/web/src/features/manage-club/funding/components/PastFundingListSection.tsx
  packages/web/src/features/manage-club/funding/components/_atomic/PastSingleSemesterFundingListSection.tsx
  packages/web/src/features/manage-club/funding/frames/AddEvidenceFrame.tsx
  packages/web/src/features/manage-club/funding/frames/BasicEvidenceFrame.tsx
  packages/web/src/features/manage-club/funding/frames/FundingInfoFrame.tsx
  packages/web/src/features/manage-club/members/components/AllMemberList.tsx
  packages/web/src/features/manage-club/members/frames/AllMemberListFrame.tsx
  packages/web/src/features/manage-club/members/frames/RegisterMemberListFrame.tsx
  packages/web/src/features/manage-division/components/ChangeDivisionPresident.tsx
  packages/web/src/features/manage-division/components/ChangeDivisionPresidentCard.tsx
  packages/web/src/features/my/components/ChangeDivisionPresidentModalContent.tsx
  packages/web/src/features/my/components/MyChangeDivisionPresident.tsx
  packages/web/src/features/my/frames/MyClubFrame.tsx
  packages/web/src/features/my/frames/MyInfoFrame.tsx
  packages/web/src/features/my/frames/MyServiceFrame.tsx
Labels: enhancement, good first issue, front-end

#563 fix profile list selection
  packages/web/src/common/components/Header/_atomic/Login.tsx
  packages/web/src/common/components/MyMenu/_atomic/ProfileList.tsx
  packages/web/src/common/components/MyMenu/index.tsx
Labels: front-end

#530 Impl /executive/rental-business page
  packages/web/src/app/executive/rental-business/page.tsx
  packages/web/src/features/executive/rental-business/_mock/mockMyExeRnt.ts
Labels: enhancement, good first issue, front-end

#583 Impl /meeting MeetingNoticeItem.tsx component
  packages/web/src/app/meeting/page.tsx
  packages/web/src/features/meeting/components/MeetingNoticeItem.tsx
  packages/web/src/features/meeting/services/_mock/mockupMeetingNotice.ts
Labels: enhancement, good first issue, front-end

#580 impl executive > printing business page
  packages/web/src/app/executive/printing-business/page.tsx
  packages/web/src/common/components/ExecutivePrintingTable.tsx
  packages/web/src/common/components/Pagination.tsx
  packages/web/src/features/printing-business/service/_mock/mockPrinting.ts
Labels: enhancement, front-end

#586 Impl /meeting Page MeetingNoticeList with Pagination
  packages/web/src/app/meeting/page.tsx
  packages/web/src/features/meeting/components/MeetingNoticeItem.tsx
  packages/web/src/features/meeting/services/_mock/mockupMeetingNotice.ts
Labels: enhancement, good first issue, front-end

#571 fix: remove unnecessary useEffect dependency
  packages/web/src/common/components/Forms/TextInput.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoFirstFrame.tsx
  packages/web/src/features/common-space/service/getCommonSpaceUsageOrders.ts
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoFirstFrame.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoThirdFrame.tsx
Labels: bug, front-end

#591 Impl executive acf page
  packages/web/src/app/executive/activity-certificate/page.tsx
  packages/web/src/features/executive/_mock/mockExecutiveAcf.ts
  packages/web/src/features/executive/activity-certificate/components/ExecutiveAcfTable.tsx
Labels: enhancement, good first issue, front-end

#551 [UI] impl: manage-club/activity-report detailed page
  packages/web/src/app/manage-club/activity-report/[id]/page.tsx
  packages/web/src/features/manage-club/activity-report/components/AdvisorProfessorApprovalTag.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailFrame.tsx
Labels: front-end

#578 impl meet 001 005 api
  packages/api/src/app.module.ts
  packages/api/src/drizzle/schema/meeting.schema.ts
  packages/api/src/feature/meeting/meeting.controller.ts
  packages/api/src/feature/meeting/meeting.module.ts
  packages/api/src/feature/meeting/meeting.repository.ts
  packages/api/src/feature/meeting/meeting.service.ts
  packages/api/src/feature/user/repository/executive.repository.ts
  packages/api/src/feature/user/service/user.public.service.ts
  packages/interface/src/api/meeting/endpoint/apiMee001.ts
  packages/interface/src/api/meeting/endpoint/apiMee002.ts
  packages/interface/src/api/meeting/endpoint/apiMee003.ts
  packages/interface/src/api/meeting/endpoint/apiMee004.ts
  packages/interface/src/api/meeting/endpoint/apiMee005.ts
  packages/interface/src/api/meeting/index.ts
Labels: enhancement, back-end

#599 Fix Pagination empty page added last
  packages/web/src/common/components/Pagination.tsx
  packages/web/src/features/meeting/services/_mock/mockupMeetingNotice.ts
Labels: bug, good first issue, front-end

#546 impl fnd 004 005 006 api
  packages/api/src/app.module.ts
  packages/api/src/feature/activity/activity.module.ts
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/activity/service/activity.public.service.ts
  packages/api/src/feature/funding/funding.controller.ts
  packages/api/src/feature/funding/funding.module.ts
  packages/api/src/feature/funding/funding.repository.ts
  packages/api/src/feature/funding/funding.service.ts
  packages/api/src/feature/meeting/meeting.module.ts
  packages/interface/src/api/funding/endpoint/apiFnd005.ts
  packages/interface/src/api/funding/endpoint/apiFnd006.ts
Labels: enhancement, back-end

#612 add public decorator
  packages/api/src/feature/club/controller/club.controller.ts
  packages/api/src/feature/common-space/controller/common-space.controller.ts
Labels: bug, back-end

#607 zod for missing field in request body
  packages/api/src/feature/meeting/meeting.controller.ts
  packages/api/src/feature/meeting/meeting.service.ts
  packages/interface/src/api/meeting/apiMee001.ts
  packages/interface/src/api/meeting/apiMee002.ts
  packages/interface/src/api/meeting/apiMee003.ts
  packages/interface/src/api/meeting/apiMee004.ts
  packages/interface/src/api/meeting/apiMee005.ts
  packages/interface/src/api/meeting/index.ts
Labels: bug, back-end, interface

#587 connect-api-to-register-club-subpages
  packages/web/src/app/register-club/promotional/page.tsx
  packages/web/src/app/register-club/provisional/page.tsx
  packages/web/src/app/register-club/renewal/page.tsx
  packages/web/src/features/register-club/components/BasicInformFrame.tsx
  packages/web/src/features/register-club/frame/RegisterClubMainFrame.tsx
  packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
  packages/web/src/features/register-club/service/registerClub.ts
  packages/web/src/features/register-club/service/useGetClubsForPromotional.ts
  packages/web/src/features/register-club/service/useGetClubsForRenewal.ts
  packages/web/src/features/register-club/service/useRegisterClub.ts
Labels: front-end

#620 Fix reg-003 url typo
  packages/interface/src/api/registration/endpoint/apiReg003.ts
Labels: interface

#624 fix: club detail page for no advisor
  packages/web/src/features/clubDetails/components/PersonInfoCard.tsx
  packages/web/src/features/clubDetails/services/getClubDetail.ts
  packages/web/src/features/clubs/components/ClubCard.tsx
  packages/web/src/features/clubs/services/useGetClubsList.ts
Labels: bug, good first issue, front-end

#622 impl responsive design at manage-club
  packages/web/src/features/manage-club/frames/InfoManageFrame.tsx
Labels: enhancement, good first issue, front-end

#619 Impl Table horizontal scroll
  packages/web/src/common/components/Table.tsx
Labels: enhancement, good first issue, front-end

#636 Add search for /clubs
  packages/web/src/app/clubs/page.tsx
Labels: enhancement, front-end

#637 Impl registration frame in my
  packages/web/src/app/my/page.tsx
  packages/web/src/constants/tableTagList.ts
  packages/web/src/features/executive/activity-certificate/components/ExecutiveAcfTable.tsx
  packages/web/src/features/my/components/MyClubTable.tsx
  packages/web/src/features/my/components/MyMemberTable.tsx
  packages/web/src/features/my/frames/MyRegisterFrame.tsx
  packages/web/src/features/my/services/_mock/mockMyRegister.ts
Labels: enhancement, good first issue, front-end

#628 feat: impl responsive for components
  packages/web/src/app/clubs/page.tsx
  packages/web/src/common/components/Buttons/TextButton.tsx
  packages/web/src/common/components/CheckboxOption.tsx
  packages/web/src/common/components/Info.tsx
  packages/web/src/common/components/PageHead/_atomic/BreadCrumb.tsx
  packages/web/src/common/components/PageHead/_atomic/BreadCrumbItem.tsx
  packages/web/src/common/components/PageHead/_atomic/PageTitle.tsx
  packages/web/src/common/components/PageHead/index.tsx
  packages/web/src/common/components/SectionTitle.tsx
Labels: enhancement, good first issue, front-end

#633 627 impl responsive mainslogan fix bug on font weight
  packages/web/src/features/landing/frames/MainPageMainFrame.tsx
Labels: good first issue, front-end

#635 refactor club name into Korean/English
  packages/api/src/drizzle/schema/club.schema.ts
  packages/api/src/feature/club/repository/club.club-student-t.repository.ts
  packages/api/src/feature/club/repository/club.repository.ts
  packages/api/src/feature/club/service/club.service.ts
  packages/api/src/feature/rental/repository/rental.rental-order.repository.ts
Labels: back-end

#650 feat: impl executive/register-member page
  packages/web/src/app/executive/register-member/page.tsx
  packages/web/src/common/components/RegisterMemberTable.tsx
  packages/web/src/features/executive/_mock/mockMemberRegistration.ts
Labels: enhancement, front-end

#647 delete event link
  packages/web/src/app/credits/page.tsx
  packages/web/src/features/credits/components/MemberCard.tsx
  packages/web/src/features/credits/frames/CreditsMainFrame.tsx
Labels: enhancement, front-end

#665 Add placeholder to register table in /my
  packages/web/src/common/components/Table.tsx
  packages/web/src/features/my/components/MyClubTable.tsx
  packages/web/src/features/my/components/MyMemberTable.tsx
Labels: enhancement, front-end

#673 Impl row link for Table component
  packages/web/src/common/components/Table.tsx
  packages/web/src/features/my/components/MyClubTable.tsx
  packages/web/src/features/my/components/MyMemberTable.tsx
Labels: enhancement, front-end

#667 fix: reg006
  packages/api/src/feature/registration/member-registration/controller/member-registration.controller.ts
  packages/api/src/feature/registration/member-registration/service/member-registration.service.ts
  packages/interface/src/api/registration/endpoint/apiReg006.ts
Labels: back-end

#688 Fix location regarding info and search in /clubs
  packages/web/src/app/clubs/page.tsx
Labels: enhancement, front-end

#689 Fix AxiosClient to AxiosClientWithAuth in services
  packages/web/src/common/services/getUserProfile.ts
  packages/web/src/features/activity-certificate/services/getUserClubs.ts
  packages/web/src/features/activity-certificate/services/useGetUserInfo.tsx
  packages/web/src/features/clubDetails/services/getClubDetail.ts
  packages/web/src/features/clubs/services/useGetClubsList.ts
  packages/web/src/features/common-space/service/postCommonSpaceUsageOrder.ts
  packages/web/src/features/manage-club/activity-report/services/useGetActivityReport.tsx
  packages/web/src/features/manage-club/activity-report/services/usePutActivityReport.tsx
  packages/web/src/features/manage-club/services/deleteChangeDelegateRequest.ts
  packages/web/src/features/manage-club/services/getChangeDelegateRequests.ts
  packages/web/src/features/manage-club/services/getClubDelegate.ts
  packages/web/src/features/manage-club/services/getDelegateCandidates.ts
  packages/web/src/features/manage-club/services/updateClubDelegate.ts
  packages/web/src/features/my/clubs/service/useGetMyClub.ts
  packages/web/src/features/my/services/getMyActivityCertificate.ts
  packages/web/src/features/my/services/getMyCommonSpace.ts
  packages/web/src/features/my/services/getMyDelegateRequest.ts
  packages/web/src/features/my/services/getMyPrinting.ts
  packages/web/src/features/my/services/getMyRentals.ts
  packages/web/src/features/my/services/patchMyDelegateRequest.ts
  packages/web/src/features/printing-business/service/postBusinessPrintingOrder.ts
  packages/web/src/features/rental-business/service/getAvailableRentals.ts
  packages/web/src/features/rental-business/service/postRentalOrder.ts
Labels: bug, front-end

#671 add callback to ClubRulesFrame
  packages/web/src/common/components/Modal/index.tsx
  packages/web/src/features/register-club/components/ClubRulesFrame.tsx
  packages/web/src/features/register-club/constants/registerClub.ts
Labels: front-end

#681 feat: impl row link to register member table
  packages/web/src/common/components/RegisterMemberTable.tsx
Labels: enhancement, front-end

#698 Impl prof mypage (/my)
  packages/web/src/app/my/page.tsx
  packages/web/src/features/my/components/MyClubProfTable.tsx
  packages/web/src/features/my/frames/MyRegisterFrame.tsx
  packages/web/src/features/my/services/_mock/mockMyRegister.ts
Labels: enhancement, front-end

#690 Fix responsive design on main
  packages/web/src/features/landing/components/NoticeCard.tsx
  packages/web/src/features/landing/components/ServiceCard.tsx
  packages/web/src/features/landing/frames/NoticeSectionFrame.tsx
  packages/web/src/features/landing/frames/ServiceSectionFrame.tsx
Labels: enhancement, front-end

#697 connect act007 to ActivityReportFrame
  .vscode/typescriptreact.code-snippets
  packages/interface/src/api/activity/endpoint/apiAct007.ts
  packages/web/src/app/register-club/promotional/page.tsx
  packages/web/src/app/register-club/renewal/page.tsx
  packages/web/src/features/manage-club/activity-report/components/SelectParticipant.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailFrame.tsx
  packages/web/src/features/register-club/components/ActivityReportFrame.tsx
  packages/web/src/features/register-club/components/_atomic/CreateActivityReportModal.tsx
  packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
  packages/web/src/features/register-club/services/useGetClubsForPromotional.ts
  packages/web/src/features/register-club/services/useGetClubsForRenewal.ts
  packages/web/src/features/register-club/services/usePostActivityReportForNewClub.ts
  packages/web/src/features/register-club/services/useRegisterClub.ts
Labels: front-end

#610 feat: connect backend for memeber registration
  packages/web/src/app/clubs/[id]/page.tsx
  packages/web/src/features/clubDetails/frames/ClubDetailMainFrame.tsx
  packages/web/src/features/clubDetails/services/_mock/mockupClubDetail.ts
  packages/web/src/features/clubDetails/services/_mock/mockupEvent.ts
  packages/web/src/features/clubDetails/services/_mock/mockupRegistraion.ts
  packages/web/src/features/clubDetails/services/getClubDetail.ts
  packages/web/src/features/clubDetails/services/getEvent.ts
  packages/web/src/features/clubDetails/services/getMyClub.ts
  packages/web/src/features/clubDetails/services/registerClub.ts
  packages/web/src/features/clubs/services/useGetClubsList.ts
  packages/web/src/hooks/checkResisteringPeriod.ts
  packages/web/src/hooks/isInClub.ts
Labels: enhancement, front-end

#696 Impl /manage-club for delegate
  packages/web/src/app/manage-club/page.tsx
  packages/web/src/features/manage-club/components/ChangeClubInfoCard.tsx
  packages/web/src/features/manage-club/frames/InfoManageFrame.tsx
Labels: enhancement, front-end

#699 Add no description default to club detail page (/clubs/[id])
  packages/web/src/features/clubDetails/components/ClubDetailCard.tsx
  packages/web/src/features/clubDetails/frames/ClubDetailMainFrame.tsx
Labels: enhancement, front-end

#704 Open new link at notice click
  packages/web/src/features/landing/frames/NoticeSectionFrame.tsx
  packages/web/src/features/notices/components/NoticeList.tsx
Labels: enhancement, front-end

#644 Impl Mobile ClubCard component
  packages/web/src/features/clubs/components/MobileClubCard.tsx
  packages/web/src/features/clubs/services/clubTypeControl.ts
Labels: good first issue, front-end

#700 Fix Bug for search on /clubs
  packages/web/src/app/clubs/page.tsx
Labels: bug, front-end

#708 Remove change division president display on /my
  packages/web/src/app/my/page.tsx
Labels: enhancement, front-end

#706 Add max height and scrollable to Select
  packages/web/src/common/components/Select/Dropdown.tsx
Labels: enhancement, front-end

#710 Add register club detail for professor
  packages/web/src/app/my/register-club/[id]/page.tsx
Labels: enhancement, front-end

#694 fix: adjust gap from 60px to 40px when vw between 721 to 960px
  packages/web/src/app/clubs/page.tsx
  packages/web/src/app/my/page.tsx
  packages/web/src/features/landing/frames/MainPageMainFrame.tsx
  packages/web/src/features/notices/frames/NoticePageMainFrame.tsx
Labels: front-end

#654 Impl file preview UI
  packages/web/package.json
  packages/web/src/assets/no-preview.png
  packages/web/src/common/components/File/ThumbnailPreview.tsx
  packages/web/src/common/components/File/ThumbnailPreviewList.tsx
  packages/web/src/common/components/File/_atomic/ImagePreview.tsx
  packages/web/src/common/components/File/_atomic/UnsupportedPreview.tsx
  packages/web/src/common/components/File/attachment.ts
  packages/web/src/lib/viewerjs/viewerjs.d.ts
  packages/web/src/styles/globals.css
  pnpm-lock.yaml
Labels: enhancement, good first issue, front-end

#609 impl mock data on manage-club/activity-report detail page
  packages/web/src/app/manage-club/activity-report/[id]/page.tsx
  packages/web/src/features/manage-club/activity-report/_mock/mock.ts
Labels: enhancement, front-end

#672 feat: impl executive/register-club with mock data
  packages/web/src/app/executive/register-club/page.tsx
  packages/web/src/common/components/ExecutiveRegistrationTable.tsx
  packages/web/src/common/components/RegisterMemberTable.tsx
  packages/web/src/common/components/Tag.tsx
  packages/web/src/constants/tableTagList.ts
  packages/web/src/features/register-club/service/_mock/mockRegisterClub.ts
  packages/web/src/types/clubdetail.types.ts
  packages/web/src/types/divisions.types.ts
Labels: front-end

#715 impl clb015 interface
  packages/api/src/feature/club/controller/club-delegate.controller.ts
  packages/api/src/feature/club/service/club-delegate.service.ts
  packages/interface/src/api/club/endpoint/apiClb015.ts
  packages/interface/src/api/club/index.ts
Labels: enhancement, back-end

#729 handle existing club registration case (Mock Data)
  packages/web/src/app/register-club/page.tsx
  packages/web/src/features/register-club/service/_mock/mockMyRegistration.ts
Labels: front-end

#733 page permission setting
  packages/web/src/app/executive/register-club/page.tsx
  packages/web/src/app/executive/register-member/page.tsx
  packages/web/src/app/manage-club/page.tsx
  packages/web/src/app/my/page.tsx
  packages/web/src/app/my/register-club/[id]/page.tsx
  packages/web/src/common/components/MyMenu/_atomic/ProfileList.tsx
  packages/web/src/common/frames/NoManageClub.tsx
  packages/web/src/features/manage-club/services/getMyManageClub.ts
  packages/web/src/features/my/frames/MyRegisterFrame.tsx
  packages/web/src/hooks/checkManageClub.ts
  packages/web/src/hooks/getProfileNow.ts
Labels: enhancement, front-end

#741 Fix clubs detail layout to accept long name
  packages/web/src/features/clubDetails/components/ClubDetailCard.tsx
  packages/web/src/features/clubDetails/components/PersonInfoCard.tsx
  packages/web/src/features/clubDetails/components/PersonInfoItem.tsx
  packages/web/src/features/clubDetails/frames/ClubDetailMainFrame.tsx
Labels: enhancement, front-end

#739 Impl responsive view for mobile in /clubs
  packages/web/src/features/clubs/components/ClubListGrid.tsx
Labels: enhancement, front-end

#750 Remove right padding at /clubs
  packages/web/src/features/clubs/components/ClubListGrid.tsx
Labels: bug, front-end

#752 Use ThumbnailPreviewList for all kind of file previews
  packages/web/src/app/manage-club/activity-report/[id]/page.tsx
  packages/web/src/common/components/File/ThumbnailPreviewList.tsx
  packages/web/src/common/components/File/attachment.ts
  packages/web/src/common/components/FileUpload.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailFrame.tsx
  packages/web/src/features/manage-club/funding/detail/components/BasicEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/components/FixtureEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/components/OtherEvidenceList.tsx
Labels: enhancement, good first issue, front-end

#745 Impl /executive/register-club/[id]
  packages/web/src/app/executive/register-club/[id]/page.tsx
  packages/web/src/app/manage-club/activity-report/[id]/page.tsx
  packages/web/src/common/components/ProgressCheckSection/_atomic/Progress.tsx
  packages/web/src/common/components/ProgressCheckSection/_atomic/ProgressDot.tsx
  packages/web/src/common/components/ProgressCheckSection/_atomic/ProgressLine.tsx
  packages/web/src/common/components/ProgressCheckSection/index.tsx
  packages/web/src/common/components/ProgressCheckSection/progressCheckStationStatus.ts
  packages/web/src/constants/manageClubProgress.ts
  packages/web/src/features/executive/register-club/constants/registerClubType.ts
  packages/web/src/features/executive/register-club/frames/ClubRegisterApproveFrame.tsx
  packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
  packages/web/src/features/executive/register-club/services/_mock/mockActivityList.ts
  packages/web/src/features/executive/register-club/services/_mock/mockClubRegisterDetail.ts
  packages/web/src/features/manage-club/activity-report/components/PastActivityReportList.tsx
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportDetailFrame.tsx
  packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
Labels: enhancement, good first issue, front-end

#746 Impl notice page for mobile
  packages/web/src/features/landing/components/NoticeCard.tsx
  packages/web/src/features/notices/components/NoticeList.tsx
  packages/web/src/features/notices/components/NoticeListItem.tsx
  packages/web/src/features/notices/frames/NoticeListAndPaginationFrame.tsx
  packages/web/src/utils/Date/formatDate.ts
Labels: enhancement, front-end

#758 Update /club regis term info
  packages/web/src/app/clubs/page.tsx
  packages/web/src/features/clubs/services/_mock/mockupRegisTermData.ts
  packages/web/src/features/clubs/services/useGetRegisTerm.ts
Labels: enhancement, front-end

#651 Connect backend for /manage-club ClubInfo
  packages/api/src/feature/club/controller/club.controller.ts
  packages/api/src/feature/club/service/club.service.ts
  packages/interface/src/api/club/endpoint/apiClb004.ts
  packages/interface/src/api/club/endpoint/apiClb005.ts
  packages/web/src/features/manage-club/components/ChangeClubInfoCard.tsx
  packages/web/src/features/manage-club/services/getClubInfo.ts
  packages/web/src/features/manage-club/services/updateClubInfo.ts
  packages/web/src/features/my/components/MyClubTable.tsx
Labels: enhancement, front-end

#757 720 Organize Header For Register Prod Release
  packages/web/src/common/components/Header/index.tsx
  packages/web/src/common/components/NavTools/MobileNavItem.tsx
  packages/web/src/common/components/NavTools/NavSubItem.tsx
  packages/web/src/constants/nav.ts
  packages/web/src/constants/paths.ts
  packages/web/src/features/landing/frames/MainPageMainFrame.tsx
  packages/web/src/features/landing/frames/ServiceSectionFrame.tsx
  packages/web/src/features/manageClubTable/frames/ManageClubTableMainFrame.tsx
Labels: enhancement, front-end

#781 Connect registration api to /clubs
  packages/web/src/features/clubDetails/services/unregisterClub.ts
  packages/web/src/features/clubs/components/ClubCard.tsx
Labels: enhancement, front-end

#786 Connect link to footer sparcs logo
  packages/web/src/common/components/Footer/_atomic/SPARCSLogo.tsx
Labels: enhancement, front-end

#793 Fix unintentional horizontal scroll
  packages/web/src/common/components/FoldableSectionTitle.tsx
  packages/web/src/styles/globals.css
Labels: bug, front-end

#789 Connect registration delete api to /clubs/[id]
  packages/web/src/app/clubs/[id]/page.tsx
  packages/web/src/app/clubs/page.tsx
  packages/web/src/features/clubDetails/frames/ClubDetailMainFrame.tsx
  packages/web/src/features/clubDetails/services/_mock/mockupEvent.ts
  packages/web/src/features/clubs/services/useGetRegisTerm.ts
  packages/web/src/features/clubs/services/useGetRegistrationTerm.ts
  packages/web/src/hooks/checkResisteringPeriod.ts
Labels: enhancement, front-end

#795 Fix placeholder of phone number in /my
  packages/web/src/features/my/frames/MyInfoFrame.tsx
Labels: enhancement, front-end

#677 feat: impl /executive/register-member/[id] page
  packages/web/src/app/executive/register-member/[id]/page.tsx
  packages/web/src/app/executive/register-member/page.tsx
  packages/web/src/common/components/RegisterMemberTable.tsx
  packages/web/src/constants/tableTagList.ts
  packages/web/src/features/executive/_mock/mockupMemberRegistration.ts
  packages/web/src/features/executive/register-member/[id]/_mock/mockClubMemberRegister.tsx
  packages/web/src/features/executive/register-member/[id]/services/calcRegisterInfo.tsx
  packages/web/src/features/executive/register-member/_mock/mockMemberRegistration.tsx
  packages/web/src/features/executive/register-member/components/RegisterInfoTable.tsx
  packages/web/src/features/executive/register-member/components/StatusInfoFrame.tsx
  packages/web/src/features/executive/register-member/components/TotalInfoFrame.tsx
Labels: enhancement, front-end

#797 Remove unnecessary stuff from /manage-club
  packages/web/src/features/manage-club/frames/MembersManageFrame.tsx
  packages/web/src/features/manage-club/members/frames/AllMemberListFrame.tsx
Labels: enhancement, front-end

#792 Connect backend for /executive/register-club
  packages/interface/src/api/registration/endpoint/apiReg014.ts
  packages/web/src/app/executive/register-club/[id]/page.tsx
  packages/web/src/app/executive/register-club/page.tsx
  packages/web/src/common/components/ExecutiveRegistrationTable.tsx
  packages/web/src/features/executive/register-club/services/_mock/mockClubRegisterDetail.ts
  packages/web/src/features/executive/register-club/services/_mock/mockRegisterClub.ts
  packages/web/src/features/executive/register-club/services/useGetRegisterClub.ts
  packages/web/src/features/register-club/service/_mock/mockRegisterClub.ts
Labels: enhancement, front-end, interface

#807 fix: checkbox & button layout
  packages/web/src/common/components/Button.tsx
  packages/web/src/common/components/Buttons/TextButton.tsx
  packages/web/src/common/components/Checkbox.tsx
  packages/web/src/common/components/CheckboxOption.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateNoticeFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceNoticeFrame.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessNotice.tsx
  packages/web/src/features/rental-business/frames/RentalNoticeFrame.tsx
Labels: enhancement, front-end

#798 login page permission
  packages/web/src/app/executive/register-club/[id]/page.tsx
  packages/web/src/app/executive/register-club/page.tsx
  packages/web/src/app/executive/register-member/[id]/page.tsx
  packages/web/src/app/executive/register-member/page.tsx
  packages/web/src/app/manage-club/members/page.tsx
  packages/web/src/app/manage-club/page.tsx
  packages/web/src/app/my/clubs/page.tsx
  packages/web/src/app/my/page.tsx
  packages/web/src/app/my/register-club/[id]/page.tsx
  packages/web/src/common/frames/LoginRequired.tsx
  packages/web/src/common/frames/NoManageClub.tsx
  packages/web/src/common/providers/AuthContext.tsx
  packages/web/src/constants/noLoginList.ts
  packages/web/src/features/executive/register-club/frames/ExecutiveRegistrationClubFrame.tsx
  packages/web/src/features/executive/register-member/frames/ExecutiveRegisterMemberDetailFrame.tsx
  packages/web/src/features/executive/register-member/frames/ExecutiveRegisterMemberFrame.tsx
  packages/web/src/features/manage-club/components/ChangeRepresentativeCard.tsx
  packages/web/src/features/manage-club/frames/ManageClubFrame.tsx
  packages/web/src/features/manage-club/members/frames/ManageClubMembersFrame.tsx
  packages/web/src/features/my/clubs/frames/MyClubsMainFrame.tsx
  packages/web/src/features/my/frames/MyChangesFrame.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/lib/_axios/axiosErrorInterceptor.ts
Labels: enhancement, front-end

#804 Add bullet points to /register-club explanation
  packages/web/src/app/register-club/page.tsx
  packages/web/src/features/register-club/components/ClubButton.tsx
Labels: enhancement, front-end

#815 Fix align at /my club table
  packages/web/src/features/my/frames/MyClubFrame.tsx
Labels: bug, front-end

#731 Implement component for modifying activity term
  packages/web/src/features/register-club/components/SelectActivityTerm.tsx
  packages/web/src/features/register-club/components/_atomic/ActivityTermRow.tsx
  packages/web/src/features/register-club/components/_atomic/EditActivityTermModal.tsx
Labels: enhancement, front-end

#839 /executive/register-club connect backend and page redirection
  packages/web/src/common/components/ExecutiveRegistrationTable.tsx
  packages/web/src/features/executive/register-club/frames/ExecutiveRegistrationClubFrame.tsx
  packages/web/src/features/executive/register-club/services/useGetRegisterClub.ts
Labels: enhancement, front-end

#846 modify reg008 api
  packages/api/src/feature/registration/member-registration/repository/member-registration.repository.ts
  packages/interface/src/api/registration/endpoint/apiReg008.ts
Labels: enhancement, back-end

#847 Impl Approve / Reject Modal for /manage-club/members
  packages/web/src/features/manage-club/components/MembersTable.tsx
  packages/web/src/features/manage-club/frames/MembersManageFrame.tsx
  packages/web/src/features/manage-club/members/components/RegisterMemberList.tsx
Labels: enhancement, front-end

#842 824 impl UI for myregister clubidedit
  packages/web/src/app/my/register-club/[id]/edit/page.tsx
  packages/web/src/app/register-club/page.tsx
  packages/web/src/common/components/NotificationCard.tsx
  packages/web/src/common/components/WarningInfo.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
  packages/web/src/features/my/services/_mock/mockMyClubRegisterDetail.ts
  packages/web/src/features/my/services/useGetClubRegistration.ts
  packages/web/src/features/my/services/usePutClubRegistration.ts
  packages/web/src/features/my/types/myClubRegistration.ts
  packages/web/src/features/register-club/components/BasicInformFrame.tsx
  packages/web/src/features/register-club/components/ProvisionalBasicInformFrame.tsx
  packages/web/src/features/register-club/components/_atomic/ClubNameField.tsx
  packages/web/src/features/register-club/components/_atomic/MonthSelect.tsx
  packages/web/src/features/register-club/components/_atomic/YearSelect.tsx
  packages/web/src/features/register-club/services/_mocks/mockMyRegistration.ts
Labels: front-end

#857 fix: change default node_env from development to local
  .env.example
  packages/api/src/env.ts
  packages/api/src/feature/auth/service/auth.service.ts
  packages/api/src/feature/meeting/meeting.gateway.ts
  packages/api/src/main.ts
Labels: back-end

#859 Implement club-registration brief for professors(REG-021)
  packages/api/src/feature/registration/club-registration/controller/club-registration.controller.ts
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
  packages/interface/src/api/registration/endpoint/apiReg021.ts
Labels: back-end, interface

#862 fix: fix logout
  packages/web/src/common/providers/AuthContext.tsx
Labels: bug, front-end

#863 connect backend for register frame for professor
  packages/interface/src/api/registration/endpoint/apiReg021.ts
  packages/web/src/common/components/Table.tsx
  packages/web/src/features/clubs/services/_mock/mockupRegisTermData.ts
  packages/web/src/features/my/components/MyClubProfTable.tsx
  packages/web/src/features/my/frames/MyRegisterFrame.tsx
  packages/web/src/features/my/frames/_atomic/MyClubRegisterFrame.tsx
  packages/web/src/features/my/frames/_atomic/RegisterClubProfFrame.tsx
  packages/web/src/features/my/services/_mock/mockMyRegister.ts
  packages/web/src/features/my/services/getProfClubRegisterList.ts
Labels: enhancement, front-end

#866 feat: agree policy modal
  packages/web/src/common/components/Header/_atomic/Login.tsx
  packages/web/src/common/components/Modal/AgreeModal.tsx
Labels: enhancement, front-end

#860 849 fix reg006 reg012 api
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/member-registration/repository/member-registration.repository.ts
  packages/interface/src/api/registration/endpoint/apiReg006.ts
  packages/interface/src/api/registration/endpoint/apiReg012.ts
  packages/web/src/features/clubDetails/services/_mock/mockupRegistraion.ts
  packages/web/src/features/register-club/services/_mocks/mockMyRegistration.ts
Labels: back-end

#879 Impl professor clubs my
  packages/api/src/feature/club/controller/club.controller.ts
  packages/api/src/feature/club/repository/club.club-t.repository.ts
  packages/api/src/feature/club/service/club.service.ts
  packages/interface/src/api/club/endpoint/apiClb016.ts
Labels: back-end

#867 page permission setting
  packages/web/src/app/my/register-club/[id]/edit/page.tsx
  packages/web/src/app/register-club/provisional/page.tsx
  packages/web/src/app/register-club/renewal/page.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
  packages/web/src/features/my/services/useGetClubRegistration.ts
  packages/web/src/features/register-club/frames/RegisterClubAuthFrame.tsx
Labels: enhancement, front-end

#848 Connect backend for /manage-club/members
  packages/web/src/features/manage-club/components/MembersTable.tsx
  packages/web/src/features/manage-club/frames/MembersManageFrame.tsx
  packages/web/src/features/manage-club/members/components/RegisterMemberList.tsx
  packages/web/src/features/manage-club/members/frames/_mock/mockMembers.ts
  packages/web/src/features/manage-club/members/services/getClubMemberRegistration.ts
  packages/web/src/features/manage-club/members/services/patchClubMemberRegistration.ts
  packages/web/src/features/manage-club/services/_mock/mockManageClub.ts
Labels: enhancement, front-end

#878 connect backend for register frame in my
  packages/api/src/feature/registration/club-registration/controller/club-registration.controller.ts
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
  packages/interface/src/api/registration/endpoint/apiReg012.ts
  packages/interface/src/api/registration/endpoint/apiReg021.ts
  packages/web/src/features/my/clubs/service/useGetMyClub.ts
  packages/web/src/features/my/components/MyClubProfTable.tsx
  packages/web/src/features/my/components/MyClubTable.tsx
  packages/web/src/features/my/frames/MyRegisterFrame.tsx
  packages/web/src/features/my/frames/_atomic/RegisterClubFrame.tsx
  packages/web/src/features/my/services/_mock/mockMyRegister.ts
  packages/web/src/features/register-club/services/_mocks/mockMyRegistration.ts
Labels: enhancement, front-end

#883 fix: reg002 reg003 duplication issue
  packages/api/src/feature/club/repository/club.repository.ts
Labels: back-end

#887 fix: reg001 when student already has club registration
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
Labels: back-end

#889 a bunch of file stuff
  packages/web/src/common/components/File/ThumbnailPreview.tsx
  packages/web/src/common/components/File/ThumbnailPreviewList.tsx
  packages/web/src/common/components/File/_atomic/UnsupportedPreview.tsx
  packages/web/src/common/components/FileUpload.tsx
  packages/web/src/common/components/FlexWrapper.tsx
  packages/web/src/features/executive/register-club/services/_mock/mockClubRegisterDetail.ts
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportMainFrame.tsx
  packages/web/src/features/register-club/components/_atomic/CreateActivityReportModal.tsx
Labels: front-end

#891 feat: helper function for date issue
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/features/my/services/getMyClubRegistration.ts
  packages/web/src/features/register-club/components/_atomic/MonthSelect.tsx
  packages/web/src/features/register-club/components/_atomic/YearSelect.tsx
  packages/web/src/utils/Date/extractDate.ts
Labels: front-end

#893 fix: reg011 reg015
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
  packages/interface/src/api/registration/endpoint/apiReg011.ts
  packages/interface/src/api/registration/endpoint/apiReg015.ts
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
Labels: back-end

#895 Connect be to phone number edit at /my
  packages/web/src/app/my/page.tsx
  packages/web/src/features/my/frames/MyInfoFrame.tsx
  packages/web/src/features/my/services/usePatchMyPhoneNumber.ts
Labels: enhancement, front-end

#902 kr phonenumber validation
  packages/web/src/app/my/page.tsx
  packages/web/src/common/components/Forms/PhoneInput.tsx
  packages/web/src/features/manage-club/frames/InfoManageFrame.tsx
  packages/web/src/features/my/frames/MyInfoFrame.tsx
  packages/web/src/features/register-club/components/BasicInformFrame.tsx
  packages/web/src/features/register-club/components/ProvisionalBasicInformFrame.tsx
Labels: bug, front-end

#903 fix: reg011, reg015 logic in club-registration repository
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
Labels: back-end

#899 Implement Registration apply check for professors(REG-022)
  packages/api/src/feature/registration/club-registration/controller/club-registration.controller.ts
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
  packages/interface/src/api/registration/endpoint/apiReg022.ts
Labels: back-end, interface

#905 feat: hasClubRegistration page
  packages/web/src/app/register-club/promotional/page.tsx
  packages/web/src/app/register-club/provisional/page.tsx
  packages/web/src/common/frames/HasClubRegistration.tsx
  packages/web/src/features/register-club/frames/RegisterClubAuthFrame.tsx
Labels: front-end

#897 connect backend for executive register clubid
  packages/interface/src/api/registration/endpoint/apiReg015.ts
  packages/interface/src/api/registration/endpoint/apiReg016.ts
  packages/interface/src/api/registration/endpoint/apiReg017.ts
  packages/web/src/app/executive/register-club/[id]/page.tsx
  packages/web/src/constants/tableTagList.ts
  packages/web/src/features/executive/register-club/constants/registerClubType.ts
  packages/web/src/features/executive/register-club/frames/ClubRegisterApproveFrame.tsx
  packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
  packages/web/src/features/executive/register-club/services/_mock/mockClubRegisterDetail.ts
  packages/web/src/features/executive/register-club/services/getRegisterClubDetail.ts
  packages/web/src/features/executive/register-club/services/patchClubRegistrationExecutive.ts
  packages/web/src/features/executive/register-club/services/postClubRegistrationSendBack.ts
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/utils/getUserType.ts
Labels: enhancement, front-end

#910 feat: impl act007 act008
  packages/api/src/feature/activity/activity.module.ts
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/interface/src/api/activity/endpoint/apiAct007.ts
  packages/interface/src/api/activity/endpoint/apiAct008.ts
Labels: back-end

#908 fix progress status for club registrations
  packages/web/src/common/providers/AuthContext.tsx
  packages/web/src/features/executive/register-club/frames/ClubRegisterApproveFrame.tsx
  packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
  packages/web/src/features/executive/register-club/services/getRegisterClubDetail.ts
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/features/register-club/constants/registerClubProgress.ts
Labels: bug, front-end

#914 fix: fix provisional access
  packages/web/src/features/register-club/frames/RegisterClubAuthFrame.tsx
Labels: bug, front-end

#916 911 newprovisional unavailable error
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
Labels: back-end

#919 feat: no professor
  packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
Labels: bug, front-end

#921 fix: phoneInput validation
  packages/web/src/features/register-club/components/BasicInformFrame.tsx
  packages/web/src/features/register-club/components/ProvisionalBasicInformFrame.tsx
Labels: bug, front-end

#927 Implement GET activity list for Promotional club registration(ACT-011)
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/interface/src/api/activity/endpoint/apiAct011.ts
  packages/interface/src/api/activity/endpoint/apiAct012.ts
  packages/interface/src/api/activity/endpoint/apiAct013.ts
Labels: back-end, interface

#932 feat: act014 act015
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/interface/src/api/activity/endpoint/apiAct010.ts
  packages/interface/src/api/activity/endpoint/apiAct014.ts
  packages/interface/src/api/activity/endpoint/apiAct015.ts
  packages/web/src/features/register-club/services/useGetClubsForPromotional.ts
  packages/web/src/features/register-club/services/useGetClubsForRenewal.ts
Labels: back-end

#934 fix: reg012
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
Labels: back-end

#926 feat: use registration date for info
  packages/web/src/app/clubs/page.tsx
  packages/web/src/app/register-club/page.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
  packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
Labels: enhancement, front-end

#937 Merge v2.0.0-RC2
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/interface/src/api/activity/endpoint/apiAct010.ts
  packages/interface/src/api/activity/endpoint/apiAct014.ts
  packages/interface/src/api/activity/endpoint/apiAct015.ts
  packages/web/src/app/clubs/page.tsx
  packages/web/src/app/register-club/page.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
  packages/web/src/features/register-club/components/BasicInformFrame.tsx
  packages/web/src/features/register-club/components/ProvisionalBasicInformFrame.tsx
  packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
  packages/web/src/features/register-club/services/useGetClubsForPromotional.ts
  packages/web/src/features/register-club/services/useGetClubsForRenewal.ts
Labels: release

#920 connect unlinked buttons
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/features/my/services/deleteMyClubRegistration.ts
Labels: enhancement, front-end

#940 fix: several apis
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
  packages/interface/src/api/registration/endpoint/apiReg011.ts
  packages/interface/src/api/registration/endpoint/apiReg015.ts
  packages/interface/src/api/registration/endpoint/apiReg022.ts
Labels: back-end

#939 connect missing things for my register clubid
  packages/web/src/common/components/PageHead/_atomic/BreadCrumb.tsx
  packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
Labels: enhancement, front-end

#942 941 fix reg012
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/interface/src/api/registration/endpoint/apiReg012.ts
  packages/web/src/features/register-club/services/_mocks/mockMyRegistration.ts
Labels: back-end

#945 connect backend for activity list in register club
  packages/api/src/feature/activity/service/activity.service.ts
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/interface/src/api/activity/endpoint/apiAct011.ts
  packages/web/src/app/my/register-club/[id]/page.tsx
  packages/web/src/constants/tableTagList.ts
  packages/web/src/features/manage-club/activity-report/frames/ActivityReportEditFrame.tsx
  packages/web/src/features/manage-club/services/_mock/mockManageClub.ts
  packages/web/src/features/my/register-club/components/MyRegisterClubAcfTable.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubAcfFrame.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/features/my/register-club/frames/ProfessorRegisterClubDetailFrame.tsx
  packages/web/src/features/my/register-club/frames/StudentRegisterClubDetailFrame.tsx
  packages/web/src/features/my/services/_mock/mockMyClubRegisterDetail.ts
  packages/web/src/features/my/services/getProfessorClubRegistration.ts
  packages/web/src/features/register-club/components/_atomic/CreateActivityReportModal.tsx
  packages/web/src/features/register-club/services/_atomic/actApiList.ts
  packages/web/src/features/register-club/services/getProvisionalActivities.ts
Labels: enhancement, front-end

#949 Fix REG-006 typo
  packages/api/src/feature/activity/controller/activity.activity-term.controller.ts
Labels: bug, back-end

#952 Fix reg009 professor field error
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/club-registration/service/club-registration.public.service.ts
Labels: bug

#956 fix: reg001 usr001
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/api/src/feature/user/repository/user.repository.ts
  packages/api/src/feature/user/service/user.service.ts
  packages/interface/src/api/registration/endpoint/apiReg001.ts
  packages/interface/src/api/user/endpoint/apiUsr001.ts
  packages/web/src/common/services/_mock/mockupUserProfile.ts
Labels: back-end

#958 feat: connect reg 023
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/features/my/register-club/frames/ProfessorRegisterClubDetailFrame.tsx
  packages/web/src/features/my/register-club/frames/StudentRegisterClubDetailFrame.tsx
  packages/web/src/features/my/services/patchClubRegProfessorApprove.tsx
Labels: enhancement, front-end

#961 feat: executive register club acf table
  packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
Labels: enhancement, front-end

#962 Fix reg-022 professor sign check to check null
  packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
Labels: back-end

#964 Implement GET club delegate cnadidates(REG-008)
  packages/api/src/feature/club/controller/club-delegate.controller.ts
  packages/api/src/feature/club/repository/club.club-delegate-d.repository.ts
  packages/api/src/feature/club/service/club-delegate.service.ts
  packages/interface/src/api/club/endpoint/apiClb008.ts
Labels: back-end
