Repository sparcs-kaist/clubs, pull requests merged in 2025-09, with the labels that each got.

#1693 Version 0.0.91
  packages/web/src/constants/patchNote.ts
  packages/web/src/constants/paths.ts
Labels: release

#1695 Version 0.0.92
  packages/api/src/feature/auth/dto/sparcs-sso.dto.ts
  packages/api/src/feature/auth/repository/auth.repository.ts
  packages/api/src/feature/auth/service/auth.service.ts
  packages/api/src/feature/auth/util/user-info-extractor.ts
  packages/api/test/unit/auth/user-info-extractor.spec.ts
  packages/web/src/constants/patchNote.ts
Labels: release

#1696 Version 0.0.93
  packages/interface/src/api/registration/utils/registrationTypeEnumChecker.ts
  packages/web/src/app/clubs/page.tsx
  packages/web/src/app/operating-committee/activity-report/[id]/page.tsx
  packages/web/src/app/operating-committee/funding/[id]/page.tsx
  packages/web/src/app/operating-committee/page.tsx
  packages/web/src/constants/patchNote.ts
  packages/web/src/features/clubs/frames/ClubsListFrame.tsx
  packages/web/src/features/executive/components/SecretKey/OperationCommitteeSecretManager.tsx
  packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
  packages/web/src/features/manage-club/funding/services/useGetFunding.ts
  turbo.json
Labels: release

#1700 [TU-315] edge credit
  packages/web/src/features/credits/credits.ts
Labels: front-end

#1699 [TU-314] ava credit
  packages/web/src/features/credits/credits.ts
Labels: front-end

#1706 [TU-237] 신규 동아리등록 무한 리렌더링 버그 수정
  packages/web/src/features/register-club/components/activity-report/ActivityReportFrame.tsx
  packages/web/src/features/register-club/components/activity-report/ActivityReportList.tsx
  packages/web/src/features/register-club/components/activity-report/_atomic/SelectActivityTerm.tsx
  packages/web/src/features/register-club/services/useGetActivityReportsForPromotional.tsx
Labels: bug, front-end

#1707 Version 0.0.95
  packages/web/src/app/clubs/page.tsx
  packages/web/src/common/components/FoldableSectionTitle.tsx
  packages/web/src/common/components/PageHead/_atomic/BreadCrumb.tsx
  packages/web/src/constants/patchNote.ts
  packages/web/src/features/clubs/components/ClubCard.tsx
  packages/web/src/features/clubs/components/ClubDetailCard.tsx
  packages/web/src/features/clubs/components/ClubInfoCard/index.tsx
  packages/web/src/features/clubs/components/ClubMemberCard.tsx
  packages/web/src/features/clubs/components/RegisterInfo.tsx
  packages/web/src/features/clubs/frames/ClubsListFrame.tsx
  packages/web/src/features/clubs/frames/detail/ClubDetailInfoFrame.tsx
  packages/web/src/features/clubs/frames/detail/ClubDetailPublicFrame.tsx
  packages/web/src/features/clubs/frames/detail/ClubDetailStudentFrame.tsx
  packages/web/src/features/credits/credits.ts
  packages/web/src/features/executive/register-club/frames/ExecutiveRegistrationClubFrame.tsx
  packages/web/src/features/executive/register-member/frames/ExecutiveRegisterMemberFrame.tsx
  packages/web/src/features/register-club/components/activity-report/ActivityReportFrame.tsx
  packages/web/src/features/register-club/components/activity-report/ActivityReportList.tsx
  packages/web/src/features/register-club/components/activity-report/_atomic/SelectActivityTerm.tsx
  packages/web/src/features/register-club/components/basic-info/_atomic/ClubNameField.tsx
  packages/web/src/features/register-club/services/useGetActivityReportsForPromotional.tsx
  packages/web/src/i18n/hooks/useLanguage.ts
  packages/web/src/i18n/messages/en/club.json
  packages/web/src/i18n/messages/en/common.json
  packages/web/src/i18n/messages/ko/club.json
  packages/web/src/i18n/messages/ko/common.json
  packages/web/src/i18n/request.ts
Labels: release

#1709 [TU-324] 동아리/회원 등록기간에만 상단바 메뉴 보이게 만들기
  packages/web/src/common/providers/store/useFeatureFlagStore.ts
Labels: front-end
