Repository sparcs-kaist/clubs, pull requests merged in 2025-03, with the labels that each got.

#1500 [TU-84] fix find professor
  packages/api/src/feature/user/repository/professor.repository.ts
Labels: bug, back-end

#1501 2025-03-03 19:30 지도교수 find 로직 버그 수정
  packages/api/src/feature/user/repository/professor.repository.ts
Labels: back-end, release

#1513 [TU-93] 동아리 등록, 회원 등록 신청 내역 테이블 pagination 수정
  packages/web/src/features/executive/register-club/frames/ExecutiveRegistrationClubFrame.tsx
  packages/web/src/features/executive/register-member/frames/ExecutiveRegisterMemberFrame.tsx
Labels: bug, front-end

#1502 [TU-73] Refactor ProgressStatus
  packages/web/src/common/components/ProgressStatus/_atomic/Progress.tsx
  packages/web/src/common/components/ProgressStatus/_atomic/ProgressCheckSection.tsx
  packages/web/src/common/components/ProgressStatus/_atomic/ProgressDot.tsx
  packages/web/src/common/components/ProgressStatus/_atomic/ProgressLine.tsx
  packages/web/src/common/components/ProgressStatus/_atomic/progressCheckStationStatus.ts
  packages/web/src/common/components/ProgressStatus/index.tsx
  packages/web/src/constants/manageClubProgress.ts
  packages/web/src/features/activity-report/constants/activityReportProgress.ts
  packages/web/src/features/executive/register-club/services/_mock/mockClubRegisterDetail.ts
  packages/web/src/features/manage-club/funding/constants/fundingProgressStatus.ts
  packages/web/src/features/permanent/register-club/frames/ClubRegisterDetailFrame.tsx
  packages/web/src/features/register-club/constants/registerClubProgress.ts
Labels: front-end

#1515 [TU-57] gb credit
  packages/web/src/features/credits/credits.ts
Labels: front-end

#1519 [TU-23]
  .vscode/settings.json
  packages/web/src/app/not-found.tsx
  packages/web/src/common/components/ErrorMessage.tsx
  packages/web/src/common/components/RegisterMemberTable.tsx
  packages/web/src/common/components/withAuthorization.tsx
  packages/web/src/common/frames/HasClubRegistration.tsx
  packages/web/src/common/frames/LoginRequired.tsx
  packages/web/src/common/frames/NoManageClub.tsx
  packages/web/src/common/frames/NoManageClubForExecutive.tsx
  packages/web/src/common/frames/NoManageClubForProfessor.tsx
  packages/web/src/common/frames/NoRegisterClubForProfessor.tsx
  packages/web/src/common/frames/NotClubRegistrationPeriod.tsx
  packages/web/src/common/frames/NotForExecutive.tsx
  packages/web/src/features/executive/components/DashboardButton.tsx
Labels: front-end

#1522 [TU-112] add semester id for registration member
  packages/api/src/drizzle/schema/registration.schema.ts
Labels: back-end

#1511 [TU-88] Implement Take functions
  packages/api/src/common/util/util.ts
  packages/api/src/feature/auth/repository/auth.repository.ts
  packages/api/src/feature/club/delegate/club.club-delegate-d.repository.ts
  packages/api/src/feature/club/repository/club.club-room-t.repository.ts
  packages/api/src/feature/club/repository/club.club-student-t.repository.ts
  packages/api/src/feature/club/repository/club.club-t.repository.ts
  packages/api/src/feature/club/repository/club.get-student-club-brief.ts
  packages/api/src/feature/club/repository/club.repository.ts
  packages/api/src/feature/club/repository/club.semester-d.repository.ts
  packages/api/src/feature/club/service/club.public.service.ts
  packages/api/src/feature/common-space/repository/common-space-usage-order-d.repository.ts
  packages/api/src/feature/division/repository/division.repository.ts
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/member-registration/repository/member-registration.repository.ts
  packages/api/src/feature/registration/repository/registration.repository.ts
  packages/api/src/feature/user/repository/executive.repository.ts
  packages/api/src/feature/user/repository/professor.repository.ts
  packages/api/src/feature/user/repository/student.repository.ts
  packages/api/src/feature/user/repository/user.repository.ts
Labels: back-end

#1523 [TU-49] 전체 회원 명단 개선
  packages/web/src/features/manage-club/members/components/AllMemberList.tsx
  packages/web/src/features/manage-club/members/components/MemberSearchAndFilter.tsx
Labels: front-end

#1520 [TU-92] 회원등록 관련 분과 정렬 수정
  packages/api/src/feature/club/repository/club.repository.ts
  packages/api/src/feature/club/service/club.service.ts
Labels: back-end

#1531 [TU-109] ms credit
  packages/web/src/features/credits/credits.ts
Labels: front-end

#1526 [TU-99] Refactoring Manage Member
  packages/web/src/common/components/Table/TableButton.tsx
  packages/web/src/features/manage-club/components/MembersTable.tsx
  packages/web/src/features/manage-club/frames/MemberManageFrame.tsx
  packages/web/src/features/manage-club/frames/RegistrationManageFrame.tsx
  packages/web/src/features/manage-club/members/components/AllMemberList.tsx
  packages/web/src/features/manage-club/members/components/RegisterMemberList.tsx
  packages/web/src/features/manage-club/members/frames/AllMemberListFrame.tsx
  packages/web/src/features/manage-club/members/frames/ManageClubMembersFrame.tsx
  packages/web/src/features/manage-club/members/frames/RegisterMemberListFrame.tsx
  packages/web/src/features/manage-club/members/hooks/useFilteredMembers.ts
  packages/web/src/features/manage-club/members/services/_mock/mockMembers.ts
  packages/web/src/features/manage-club/members/services/patchClubMemberRegistration.ts
  packages/web/src/features/manage-club/members/services/useGetClubMemberRegistration.ts
  packages/web/src/features/manage-club/members/services/useGetClubMembers.ts
  packages/web/src/features/manage-club/members/services/useGetClubSemesters.ts
  packages/web/src/features/manage-club/members/services/usePatchClubMemberRegistration.ts
  packages/web/src/features/manage-club/members/types/semesterList.ts
Labels: front-end

#1533 fix: exeuctive dashboard for member registration and query faster
  packages/api/src/feature/division/service/division.public.service.ts
  packages/api/src/feature/registration/member-registration/repository/member-registration.repository.ts
  packages/api/src/feature/registration/member-registration/service/member-registration.service.ts
  packages/api/src/feature/user/repository/student.repository.ts
  packages/api/src/feature/user/service/user.public.service.ts
Labels: bug, back-end

#1534 [TU-130] change registration and club name eng length to 100
  packages/api/src/drizzle/schema/club.schema.ts
  packages/api/src/drizzle/schema/registration.schema.ts
Labels: bug, back-end

#1528 [TU-98] 마이페이지 회원등록 리팩토링
  packages/web/src/common/components/ExecutiveRegistrationTable.tsx
  packages/web/src/common/components/Table.tsx
  packages/web/src/features/clubs/components/ClubRegistrationButton.tsx
  packages/web/src/features/clubs/components/RegisterInfo.tsx
  packages/web/src/features/clubs/hooks/useGetMemberRegistrationPeriod.ts
  packages/web/src/features/clubs/services/useGetMemberRegistrationCount.ts
  packages/web/src/features/clubs/services/useGetRegistrationTerm.ts
  packages/web/src/features/clubs/services/useRegisterClub.ts
  packages/web/src/features/clubs/services/useUnregisterClub.ts
  packages/web/src/features/manage-club/frames/ManageClubFrame.tsx
  packages/web/src/features/manage-club/services/getMyManageClub.ts
  packages/web/src/features/my/components/MyMemberTable.tsx
  packages/web/src/features/my/frames/MyRegisterFrame.tsx
  packages/web/src/features/my/frames/_atomic/MyMemberRegisterFrame.tsx
  packages/web/src/features/register-club/hooks/useGetClubRegistrationPeriod.ts
Labels: front-end

#1537 [TU-133] 회원등록 프론트 남은 이슈 수정
  packages/api/src/feature/registration/controller/registration.controller.ts
  packages/api/src/feature/registration/repository/registration.repository.ts
  packages/api/src/feature/registration/service/registration.service.ts
  packages/interface/src/api/registration/endpoint/apiReg004.ts
  packages/interface/src/api/registration/endpoint/apiReg028.ts
  packages/web/src/features/clubs/constants/index.ts
  packages/web/src/features/clubs/frames/ClubsStudentFrame.tsx
  packages/web/src/features/clubs/frames/detail/ClubDetailStudentFrame.tsx
  packages/web/src/features/clubs/hooks/useGetMemberRegistrationPeriod.ts
  packages/web/src/features/clubs/services/_mock/mockupRegisTermData.ts
  packages/web/src/features/clubs/services/useGetClubRegistrationDeadline.ts
  packages/web/src/features/clubs/services/useGetMemberRegistrationDeadline.ts
  packages/web/src/features/clubs/services/useGetRegistrationTerm.ts
  packages/web/src/features/manage-club/frames/ManageClubFrame.tsx
  packages/web/src/features/manage-club/members/frames/RegisterMemberListFrame.tsx
  packages/web/src/features/my/frames/MyRegisterFrame.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
  packages/web/src/features/register-club/constants/index.ts
  packages/web/src/features/register-club/frames/RegisterClubAuthFrame.tsx
  packages/web/src/features/register-club/frames/RegisterClubFrame.tsx
  packages/web/src/features/register-club/hooks/useGetClubRegistrationPeriod.ts
Labels: front-end

#1539 [TU-137] 테이블 정렬 이슈 및 집행부원 회원등록 통계 데이터 버그 수정
  packages/web/src/common/components/Table.tsx
  packages/web/src/common/components/Table/TableCell.tsx
  packages/web/src/features/executive/register-member/components/RegisterInfoTable.tsx
  packages/web/src/features/executive/register-member/frames/ExecutiveRegisterMemberDetailFrame.tsx
  packages/web/src/features/manage-club/frames/MemberManageFrame.tsx
  packages/web/src/features/manage-club/members/components/AllMemberList.tsx
Labels: bug, front-end

#1540 [TU-138] 동아리 상세 페이지 성격 정렬 개선
  packages/web/src/features/clubs/components/ClubInfoCard/ClubInfoItem.tsx
Labels: bug, front-end

#1524 [TU-75] ClubRegisterDetailFrame 리팩토링
  packages/web/src/app/executive/register-club/[id]/page.tsx
  packages/web/src/app/manage-club/permanent/register-club/[id]/page.tsx
  packages/web/src/app/my/register-club/[id]/edit/page.tsx
  packages/web/src/app/my/register-club/[id]/page.tsx
  packages/web/src/features/executive/register-club/frames/ClubRegisterApproveFrame.tsx
  packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
  packages/web/src/features/executive/register-club/services/getRegisterClubDetail.ts
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/features/my/register-club/frames/ProfessorRegisterClubDetailButton.tsx
  packages/web/src/features/my/register-club/frames/ProfessorRegisterClubDetailFrame.tsx
  packages/web/src/features/my/register-club/frames/StudentRegisterClubDetailButton.tsx
  packages/web/src/features/my/register-club/frames/StudentRegisterClubDetailFrame.tsx
  packages/web/src/features/my/services/getProfessorClubRegistration.ts
  packages/web/src/features/my/services/useGetClubRegistration.ts
  packages/web/src/features/permanent/register-club/frames/ClubRegisterApproveFrame.tsx
  packages/web/src/features/permanent/register-club/services/getRegisterClubDetail.ts
  packages/web/src/features/register-club/frames/RegisterClubDetailFrame.tsx
  packages/web/src/features/register-club/services/_atomic/registerClubApiList.ts
  packages/web/src/features/register-club/services/useGetRegisterClubDetail.ts
Labels: front-end

#1553 [TU-128] Add swagger to member-registration
  packages/api/src/feature/funding/controller/funding.controller.ts
  packages/api/src/feature/registration/member-registration/controller/member-registration.controller.ts
  packages/api/src/main.ts
  packages/interface/src/api/club/type/club.type.ts
  packages/interface/src/api/funding/index.ts
  packages/interface/src/api/registration/endpoint/apiReg005.ts
  packages/interface/src/api/registration/endpoint/apiReg006.ts
  packages/interface/src/api/registration/endpoint/apiReg007.ts
  packages/interface/src/api/registration/endpoint/apiReg008.ts
  packages/interface/src/api/registration/endpoint/apiReg013.ts
  packages/interface/src/api/registration/endpoint/apiReg019.ts
  packages/interface/src/api/registration/endpoint/apiReg020.ts
  packages/interface/src/api/registration/endpoint/apiReg026.ts
  packages/interface/src/api/registration/endpoint/apiReg028.ts
  packages/interface/src/api/registration/index.ts
  packages/interface/src/api/registration/type/member.registration.type.ts
  packages/interface/src/open-api.ts
Labels: back-end, interface

#1564 [TU-162]
  packages/api/src/feature/auth/controller/auth.controller.ts
  packages/api/src/feature/auth/service/auth.service.ts
  packages/web/src/app/errors/not-iam-login/page.tsx
  packages/web/src/app/errors/page.tsx
Labels: bug, front-end, back-end

#1563 이것저것 버그수정
  .vscode/settings.json
  packages/web/src/common/components/NavTools/MobileNavItem.tsx
  packages/web/src/common/components/NavTools/MobileNavMenu.tsx
  packages/web/src/features/landing/components/MoreSectionTitle.tsx
  packages/web/src/features/landing/frames/NoticeSectionFrame.tsx
  packages/web/src/features/landing/frames/ServiceSectionFrame.tsx
Labels: bug, front-end
