Repository sparcs-kaist/clubs, pull requests merged in 2025-02, with the labels that each got.

#1367 impl executive activity report charged page
  packages/web/src/app/executive/activity-report/charged/[id]/page.tsx
  packages/web/src/features/executive/activity-report/components/ActivityReportChargedClubTable.tsx
  packages/web/src/features/executive/activity-report/components/ActivityReportChargedOtherTable.tsx
  packages/web/src/features/executive/activity-report/components/ActivityReportChargedStatistic.tsx
  packages/web/src/features/executive/activity-report/components/ActivityReportClubStatistic.tsx
  packages/web/src/features/executive/activity-report/components/ActivityReportStatistic.tsx
  packages/web/src/features/executive/activity-report/components/ExecutiveActivityChargedTable.tsx
  packages/web/src/features/executive/activity-report/components/ExecutiveClubActivitiesTable.tsx
  packages/web/src/features/executive/activity-report/components/_atomic/ActivityReportStatisticContent.tsx
  packages/web/src/features/executive/activity-report/frames/ExecutiveActivityReportChargedFrame.tsx
  packages/web/src/features/executive/activity-report/frames/ExecutiveActivityReportFrame.tsx
  packages/web/src/features/executive/activity-report/services/useGetExecutiveChargedActivities.tsx
  packages/web/src/features/executive/activity-report/utils/sortActivities.ts
Labels: new feature, front-end

#1394 Fix minor issues for executive activity
  packages/web/src/app/executive/activity-report/[id]/page.tsx
  packages/web/src/app/manage-club/activity-report/[id]/page.tsx
  packages/web/src/features/activity-report/components/ExecutiveActivityReportApprovalSection.tsx
  packages/web/src/features/activity-report/constants/activityReportProgress.ts
  packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
  packages/web/src/features/activity-report/hooks/useExecutiveApproveActivityReport.ts
  packages/web/src/features/activity-report/hooks/useExecutiveRejectActivityReport.ts
  packages/web/src/features/activity-report/hooks/useGetActivityReportDetail.ts
  packages/web/src/features/activity-report/types/activityReport.ts
  packages/web/src/features/activity-report/utils/filterComment.ts
  packages/web/src/features/executive/activity-report/components/ChargedActivityModalTable.tsx
  packages/web/src/features/executive/activity-report/components/ExecutiveActivityChargedTable.tsx
  packages/web/src/features/executive/activity-report/components/ExecutiveClubActivitiesTable.tsx
  packages/web/src/features/my/register-club/components/MyRegisterClubActTable.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubActFrame.tsx
  packages/web/src/features/register-club/components/ActivityReportFrame.tsx
  packages/web/src/features/register-club/components/ActivityReportList.tsx
  packages/web/src/features/register-club/components/_atomic/EditActivityReportModal.tsx
  packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
Labels: bug, front-end

#1414 [Delegate] 대표자 변경 요청이 만료되지 않는 오류
  packages/api/src/feature/club/delegate/club.club-delegate-d.repository.ts
  packages/api/src/feature/club/delegate/delegate.service.ts
  packages/web/src/features/manage-club/components/ChangeRepresentativeCard.tsx
  packages/web/src/features/manage-club/frames/_atomic/RepresentativeLoadFrame.tsx
Labels: bug, front-end, back-end

#1423 fix: update delegate service response status to FORBIDDEN for empty results
  packages/api/src/feature/club/delegate/delegate.service.ts
Labels: back-end

#1421 feat: filter out specific club IDs from club list
  packages/api/src/feature/club/service/club.service.ts
Labels: back-end

#1432 1431 feat api014 015 016
  packages/api/src/feature/funding/controller/funding.controller.ts
  packages/api/src/feature/funding/repository/funding.repository.ts
  packages/api/src/feature/funding/service/funding.service.ts
  packages/interface/src/api/funding/endpoint/apiFnd014.ts
  packages/interface/src/api/funding/endpoint/apiFnd015.ts
  packages/interface/src/api/funding/endpoint/apiFnd016.ts
Labels: back-end

#1424 impl funding detail page for executive
  packages/api/src/feature/funding/service/funding.service.ts
  packages/interface/src/api/funding/endpoint/apiFnd013.ts
  packages/web/src/app/executive/funding/[id]/page.tsx
  packages/web/src/app/manage-club/funding/[id]/page.tsx
  packages/web/src/common/components/FlexWrapper.tsx
  packages/web/src/common/components/Forms/UnitInput.tsx
  packages/web/src/features/manage-club/funding/detail/components/ExecutiveFundingReviewSection.tsx
  packages/web/src/features/manage-club/funding/detail/components/FundingStatusSection.tsx
  packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
  packages/web/src/features/manage-club/funding/hooks/useGetInitialFundingForm.ts
  packages/web/src/features/manage-club/funding/hooks/useUpdateFunding.ts
  packages/web/src/features/manage-club/funding/services/_atomic/fndApiList.ts
  packages/web/src/features/manage-club/funding/services/useExecutiveReviewFunding.ts
  packages/web/src/features/manage-club/funding/services/useGetFunding.ts
  packages/web/src/features/manage-club/funding/services/usePostFundingReview.ts
Labels: new feature, front-end

#1437 add file upload field in NonCorpEvidenceBlock
  packages/web/src/constants/manageClubFunding.ts
  packages/web/src/features/manage-club/funding/components/NonCorpEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/hooks/useCreateFunding.ts
  packages/web/src/features/manage-club/funding/hooks/useUpdateFunding.ts
  packages/web/src/utils/Date/formatDate.ts
Labels: bug, front-end

#1439 Merge dev into main
  packages/web/src/constants/manageClubFunding.ts
  packages/web/src/features/manage-club/funding/components/NonCorpEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/hooks/useCreateFunding.ts
  packages/web/src/features/manage-club/funding/hooks/useUpdateFunding.ts
  packages/web/src/utils/Date/formatDate.ts
Labels: release

#1440 add nonCorporateTransaction file data in NonCorpevidenceList
  packages/api/src/feature/club/delegate/delegate.service.ts
  packages/api/src/feature/funding/controller/funding.controller.ts
  packages/api/src/feature/funding/service/funding.service.ts
  packages/web/src/features/manage-club/funding/detail/components/NonCorpEvidenceList.tsx
Labels: bug

#1427 update github pr template
  .github/pull_request_template.md
Labels: documentation

#1444 Merge Production of Committee status button
  packages/web/src/common/components/ApproveReasonToast.tsx
  packages/web/src/common/components/RejectReasonToast.tsx
  packages/web/src/common/components/Toast/ApproveReasonToast.tsx
  packages/web/src/common/components/Toast/RejectReasonToast.tsx
  packages/web/src/common/components/Toast/index.tsx
  packages/web/src/features/activity-report/components/ActivityReportStatusSection.tsx
  packages/web/src/features/manage-club/funding/detail/components/ExecutiveFundingReviewSection.tsx
  packages/web/src/features/manage-club/funding/detail/components/FundingStatusSection.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/features/register-club/components/_atomic/EditActivityReportModal.tsx
  packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
Labels: release

#1447 fix funding detail layout
  packages/web/src/common/components/Toast/index.tsx
  packages/web/src/features/manage-club/funding/detail/components/ExecutiveFundingReviewSection.tsx
Labels: front-end

#1450 1449 fix api fnd 003 for put noncorp
  packages/api/src/feature/funding/repository/funding.repository.ts
  packages/web/src/features/manage-club/funding/detail/components/ExecutiveFundingReviewSection.tsx
Labels: bug, front-end, back-end

#1455 Merge to fix funding bugs
  packages/api/src/feature/funding/repository/funding.repository.ts
  packages/web/src/app/executive/activity-report/[id]/page.tsx
  packages/web/src/app/executive/activity-report/charged/[id]/page.tsx
  packages/web/src/app/executive/activity-report/club/[id]/page.tsx
  packages/web/src/app/executive/activity-report/page.tsx
  packages/web/src/app/executive/funding/[id]/page.tsx
  packages/web/src/app/executive/funding/charged/[id]/page.tsx
  packages/web/src/app/executive/funding/club/[id]/page.tsx
  packages/web/src/app/executive/funding/page.tsx
  packages/web/src/app/executive/register-club/[id]/page.tsx
  packages/web/src/app/executive/register-club/page.tsx
  packages/web/src/app/executive/register-member/[id]/page.tsx
  packages/web/src/app/executive/register-member/page.tsx
  packages/web/src/app/manage-club/activity-report/[id]/edit/page.tsx
  packages/web/src/app/manage-club/activity-report/create/page.tsx
  packages/web/src/app/manage-club/activity-report/page.tsx
  packages/web/src/app/manage-club/funding/[id]/edit/page.tsx
  packages/web/src/app/manage-club/funding/[id]/page.tsx
  packages/web/src/app/manage-club/funding/create/page.tsx
  packages/web/src/app/manage-club/members/page.tsx
  packages/web/src/app/manage-club/page.tsx
  packages/web/src/app/manage-club/permanent/register-club/[id]/page.tsx
  packages/web/src/app/manage-club/permanent/register-club/page.tsx
  packages/web/src/app/my/clubs/page.tsx
  packages/web/src/app/my/page.tsx
  packages/web/src/app/my/register-club/[id]/edit/page.tsx
  packages/web/src/app/my/register-club/[id]/page.tsx
  packages/web/src/app/register-club/page.tsx
  packages/web/src/app/register-club/promotional/page.tsx
  packages/web/src/app/register-club/provisional/page.tsx
  packages/web/src/app/register-club/renewal/page.tsx
  packages/web/src/common/components/Toast/index.tsx
  packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
  packages/web/src/features/activity-report/hooks/useExecutiveApproveActivityReport.ts
  packages/web/src/features/activity-report/hooks/useExecutiveRejectActivityReport.ts
  packages/web/src/features/activity-report/hooks/useGetActivityReportComments.ts
  packages/web/src/features/activity-report/hooks/useGetActivityReportDetail.ts
  packages/web/src/features/activity-report/hooks/useGetInitialActivityReportFormData.ts
  packages/web/src/features/activity-report/hooks/useProfessorApproveSingleActivityReport.ts
  packages/web/src/features/activity-report/hooks/useUpdateActivityReport.ts
  packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
  packages/web/src/features/manage-club/funding/detail/components/ExecutiveFundingReviewSection.tsx
  packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
  packages/web/src/features/manage-club/funding/hooks/useGetInitialFundingForm.ts
  packages/web/src/features/manage-club/funding/hooks/useUpdateFunding.ts
  packages/web/src/features/manage-club/funding/services/_atomic/fndApiList.ts
  packages/web/src/features/manage-club/funding/services/useExecutiveReviewFunding.ts
  packages/web/src/features/my/frames/MyRegisterFrame.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
  packages/web/src/features/register-club/services/_atomic/actApiList.ts
  packages/web/src/utils/isStudent.ts
Labels: release

#1456 fix funding minor issues
  packages/web/src/features/manage-club/funding/detail/components/TransportationEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
  packages/web/src/features/manage-club/funding/frames/AddEvidenceFrame.tsx
Labels: bug, front-end

#1453 1451 update toast common component
  packages/api/src/feature/division/repository/division.repository.ts
  packages/web/src/common/components/Toast/ApproveReasonToast.tsx
  packages/web/src/common/components/Toast/CommentToast.tsx
  packages/web/src/common/components/Toast/RejectReasonToast.tsx
  packages/web/src/features/activity-report/components/ActivityReportStatusSection.tsx
  packages/web/src/features/executive/funding/components/ChargedChangeFundingClubModalContent.tsx
  packages/web/src/features/executive/funding/components/ChargedChangeFundingModalContent.tsx
  packages/web/src/features/executive/funding/components/ChargedChangeFundingModalTable.tsx
  packages/web/src/features/executive/funding/components/ChargedFundingModalTable.tsx
  packages/web/src/features/executive/funding/components/ExecutiveClubFundingsTable.tsx
  packages/web/src/features/executive/funding/components/ExecutiveFundingChargedTable.tsx
  packages/web/src/features/executive/funding/components/ExecutiveFundingClubTable.tsx
  packages/web/src/features/executive/funding/components/FundingChargedClubTable.tsx
  packages/web/src/features/executive/funding/components/FundingChargedOtherTable.tsx
  packages/web/src/features/executive/funding/components/FundingChargedStatistic.tsx
  packages/web/src/features/executive/funding/components/FundingClubStatistic.tsx
  packages/web/src/features/executive/funding/frames/ExecutiveFundingChargedFrame.tsx
  packages/web/src/features/executive/funding/frames/ExecutiveFundingClubFrame.tsx
  packages/web/src/features/executive/funding/frames/ExecutiveFundingFrame.tsx
  packages/web/src/features/executive/funding/services/useGetChargedFundings.ts
  packages/web/src/features/executive/funding/services/useGetClubFundings.ts
  packages/web/src/features/executive/funding/services/useGetExecutiveFundings.tsx
  packages/web/src/features/executive/funding/services/useGetFundingClubChargeAvailableExecutives.ts
  packages/web/src/features/executive/funding/services/usePatchFundingChargedExecutive.ts
  packages/web/src/features/executive/funding/services/usePatchFundingStatus.ts
  packages/web/src/features/manage-club/funding/detail/components/FundingStatusSection.tsx
  packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/features/register-club/components/_atomic/EditActivityReportModal.tsx
  packages/web/src/features/register-club/components/_atomic/PastActivityReportModal.tsx
  packages/web/src/stories/CommentToast.stories.tsx
Labels: front-end

#1461 Add winter credits chacha
  packages/web/src/features/credits/credits.ts
Labels: front-end

#1463 add ava credit to 2025 winter
  packages/web/src/features/credits/credits.ts
  packages/web/src/features/my/frames/MyClubFrame.tsx
Labels: front-end

#1298 Impl Entity API (MEE013~027)
  .nvmrc
  packages/api/src/feature/meeting/entity/content/content.controller.ts
  packages/api/src/feature/meeting/entity/content/content.module.ts
  packages/api/src/feature/meeting/entity/content/content.repository.ts
  packages/api/src/feature/meeting/entity/content/content.service.ts
  packages/api/src/feature/meeting/entity/entity.controller.ts
  packages/api/src/feature/meeting/entity/entity.module.ts
  packages/api/src/feature/meeting/entity/entity.repository.ts
  packages/api/src/feature/meeting/entity/entity.service.ts
  packages/api/src/feature/meeting/entity/vote/vote.controller.ts
  packages/api/src/feature/meeting/entity/vote/vote.module.ts
  packages/api/src/feature/meeting/entity/vote/vote.repository.ts
  packages/api/src/feature/meeting/entity/vote/vote.service.ts
  packages/api/src/feature/meeting/meeting.module.ts
  packages/interface/src/api/meeting/apiMee008.ts
  packages/interface/src/api/meeting/apiMee013.ts
  packages/interface/src/api/meeting/apiMee014.ts
  packages/interface/src/api/meeting/apiMee015.ts
  packages/interface/src/api/meeting/apiMee016.ts
  packages/interface/src/api/meeting/apiMee017.ts
  packages/interface/src/api/meeting/apiMee018.ts
  packages/interface/src/api/meeting/apiMee019.ts
  packages/interface/src/api/meeting/apiMee020.ts
  packages/interface/src/api/meeting/apiMee021.ts
  packages/interface/src/api/meeting/apiMee022.ts
  packages/interface/src/api/meeting/apiMee023.ts
  packages/interface/src/api/meeting/apiMee024.ts
  packages/interface/src/api/meeting/apiMee027.ts
  packages/interface/src/common/enum/meeting.enum.ts
Labels: new feature, back-end

#1458 refactor rental business folders
  packages/web/src/app/executive/rental-business/page.tsx
  packages/web/src/app/manage-club/rental-business/[id]/page.tsx
  packages/web/src/app/my/rental-business/[id]/page.tsx
  packages/web/src/app/my/rental-business/page.tsx
  packages/web/src/features/manage-club/rental/frames/ManageRentalDetailFrame.tsx
  packages/web/src/features/my/frames/MyServiceFrame.tsx
  packages/web/src/features/my/rental-business/components/MyRentalProgress.tsx
  packages/web/src/features/my/rental-business/frames/MyRentalDetailFrame.tsx
  packages/web/src/features/printing-business/component/PrintingBusinessForm/PrintingBusinessFormThird.tsx
  packages/web/src/features/rental-business/components/MyRentalTable.tsx
  packages/web/src/features/rental-business/components/RentalProgress.tsx
  packages/web/src/features/rental-business/components/SelectRangeCalendar/index.tsx
  packages/web/src/features/rental-business/frames/RentalDetailFrame.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoSecondFrame.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoThirdFrame.tsx
  packages/web/src/features/rental-business/services/_mock/mockAvailableRental.ts
  packages/web/src/features/rental-business/services/_mock/mockExistDate.ts
  packages/web/src/features/rental-business/services/_mock/mockMyExeRnt.ts
  packages/web/src/features/rental-business/services/postRentalOrder.ts
  packages/web/src/features/rental-business/services/useGetAvailableRentals.ts
  packages/web/src/features/rental-business/services/useGetMyRentals.ts
Labels: front-end

#1385 feat: temporary storage feature for activity report creation using localstorage
  .npmrc
  packages/web/src/common/components/Modal/RestoreDraftModal.tsx
  packages/web/src/common/hooks/useTemporaryStorage.ts
  packages/web/src/common/services/localStorageUtil.ts
  packages/web/src/constants/localStorage.ts
  packages/web/src/features/activity-report/components/ActivityReportForm.tsx
  packages/web/src/features/activity-report/frames/ActivityReportCreateFrame.tsx
  packages/web/src/types/localStorageType.ts
  packages/web/src/utils/index.ts
Labels: front-end

#1469 [TU-22] 1454 refactoring register club frontend code
  packages/web/src/app/layout.tsx
  packages/web/src/app/register-club/page.tsx
  packages/web/src/common/components/Forms/PhoneInput.tsx
  packages/web/src/common/components/Info.tsx
  packages/web/src/common/components/Modal/RestoreDraftModal.tsx
  packages/web/src/common/frames/NoManageClubForExecutive.tsx
  packages/web/src/common/frames/NotClubRegistrationPeriod.tsx
  packages/web/src/features/activity-report/components/ActivityReportForm.tsx
  packages/web/src/features/activity-report/frames/ActivityReportCreateFrame.tsx
  packages/web/src/features/my/frames/MyRegisterFrame.tsx
  packages/web/src/features/my/register-club/components/MyRegisterClubActTable.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
  packages/web/src/features/register-club/components/AdvancedInformFrame.tsx
  packages/web/src/features/register-club/components/ClubButton.tsx
  packages/web/src/features/register-club/components/_atomic/ActivityReportForm.tsx
  packages/web/src/features/register-club/components/_atomic/ClubNameSelect.tsx
  packages/web/src/features/register-club/components/activity-report/ActivityReportFrame.tsx
  packages/web/src/features/register-club/components/activity-report/ActivityReportList.tsx
  packages/web/src/features/register-club/components/activity-report/CreateActivityReportModal.tsx
  packages/web/src/features/register-club/components/activity-report/EditActivityReportModal.tsx
  packages/web/src/features/register-club/components/activity-report/EditActivityTermModal.tsx
  packages/web/src/features/register-club/components/activity-report/PastActivityReportModal.tsx
  packages/web/src/features/register-club/components/activity-report/_atomic/ActivityReportForm.tsx
  packages/web/src/features/register-club/components/activity-report/_atomic/ActivityTermRow.tsx
  packages/web/src/features/register-club/components/activity-report/_atomic/SelectActivityTerm.tsx
  packages/web/src/features/register-club/components/advanced-info/AdvancedInformFrame.tsx
  packages/web/src/features/register-club/components/advanced-info/SingleUploadWithTextAndTemplate.tsx
  packages/web/src/features/register-club/components/basic-info/BasicInformFrame.tsx
  packages/web/src/features/register-club/components/basic-info/ProfessorInformFrame.tsx
  packages/web/src/features/register-club/components/basic-info/ProvisionalBasicInformFrame.tsx
  packages/web/src/features/register-club/components/basic-info/_atomic/ClubNameField.tsx
  packages/web/src/features/register-club/components/basic-info/_atomic/DivisionSelect.tsx
  packages/web/src/features/register-club/components/basic-info/_atomic/MonthSelect.tsx
  packages/web/src/features/register-club/components/basic-info/_atomic/YearSelect.tsx
  packages/web/src/features/register-club/components/compliance/ClubRegulationsComplianceSection.tsx
  packages/web/src/features/register-club/components/compliance/ClubRulesFrame.tsx
  packages/web/src/features/register-club/components/compliance/RulesButton.tsx
  packages/web/src/features/register-club/constants/index.ts
  packages/web/src/features/register-club/frames/RegisterClubAuthFrame.tsx
  packages/web/src/features/register-club/frames/RegisterClubFrame.tsx
  packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
  packages/web/src/features/register-club/hooks/useGetClubRegistrationPeriod.ts
  packages/web/src/features/register-club/model/CreateRegisterClub.ts
  packages/web/src/features/register-club/types/registerClub.ts
  packages/web/src/features/register-club/utils/computeErrorMessage.ts
  packages/web/src/types/semester.ts
Labels: front-end

#1472 [TU-26] refactoring my>register-club code
  packages/web/src/app/my/register-club/[id]/edit/page.tsx
  packages/web/src/app/my/register-club/[id]/page.tsx
  packages/web/src/features/my/components/MyClubTable.tsx
  packages/web/src/features/my/frames/MyRegisterFrame.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
  packages/web/src/features/my/register-club/frames/ProfessorRegisterClubDetailFrame.tsx
  packages/web/src/features/my/register-club/frames/StudentRegisterClubDetailFrame.tsx
  packages/web/src/features/my/services/patchClubRegProfessorApprove.tsx
  packages/web/src/features/my/services/usePatchClubRegProfessorApprove.tsx
  packages/web/src/features/register-club/components/basic-info/BasicInformFrame.tsx
  packages/web/src/features/register-club/components/basic-info/ProvisionalBasicInformFrame.tsx
  packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
Labels: front-end, refactor

#1473 [TU-27] refactoring executive > register-club code
  packages/interface/src/api/registration/endpoint/apiReg014.ts
  packages/interface/src/api/registration/endpoint/apiReg021.ts
  packages/interface/src/api/registration/endpoint/apiReg024.ts
  packages/web/src/common/components/ExecutiveRegistrationTable.tsx
  packages/web/src/features/executive/register-club/frames/ExecutiveRegistrationClubFrame.tsx
Labels: bug, front-end

#1475 [TU-62] delete change club name checkbox and add validation for clubNameEn
  packages/web/src/features/register-club/components/basic-info/BasicInformFrame.tsx
  packages/web/src/features/register-club/components/basic-info/ProvisionalBasicInformFrame.tsx
  packages/web/src/features/register-club/components/basic-info/_atomic/ClubNameField.tsx
  packages/web/src/features/register-club/constants/index.ts
Labels: front-end

#1476 [TU-24] add temporary storage to register club
  packages/web/src/common/components/Modal/RestoreDraftModal.tsx
  packages/web/src/constants/localStorage.ts
  packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
  packages/web/src/features/register-club/components/RegisterClubForm.tsx
  packages/web/src/features/register-club/components/activity-report/CreateActivityReportModal.tsx
  packages/web/src/features/register-club/components/activity-report/_atomic/ActivityReportForm.tsx
  packages/web/src/features/register-club/frames/RegisterClubMainFrame.tsx
Labels: front-end

#1477 [TU-65] api reg 025 for club registration availability
  packages/api/src/feature/club/club.module.ts
  packages/api/src/feature/club/service/club.public.service.ts
  packages/api/src/feature/division/service/division.public.service.ts
  packages/api/src/feature/registration/club-registration/controller/club-registration.controller.ts
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
  packages/interface/src/api/registration/endpoint/apiReg012.ts
  packages/interface/src/api/registration/endpoint/apiReg025.ts
  packages/web/src/features/my/components/MyClubTable.tsx
  packages/web/src/features/my/services/_mock/mockMyClubRegisterDetail.ts
  packages/web/src/features/register-club/services/_mocks/mockMyRegistration.ts
Labels: new feature, back-end, interface

#1480 [TU-70] Club Summary Fetch logic Fix
  packages/api/src/feature/club/repository/club.repository.ts
Labels: bug, back-end

#1479 동아리 등록 페이지 신청내역 관련하여 버튼 활성화 여부 수정
  packages/web/src/common/frames/HasClubRegistration.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/features/register-club/components/RegisterClubForm.tsx
  packages/web/src/features/register-club/components/basic-info/ProvisionalBasicInformFrame.tsx
  packages/web/src/features/register-club/constants/index.ts
  packages/web/src/features/register-club/frames/RegisterClubAuthFrame.tsx
  packages/web/src/features/register-club/frames/RegisterClubFrame.tsx
  packages/web/src/features/register-club/hooks/useGetAvailableRegistrationInfo.ts
  packages/web/src/features/register-club/services/useGetRegistrationAvailableClubs.ts
Labels: front-end

#1478 [TU-64] 생활문화분과 분리 및 분과 시스템 및 엔티티 정비
  packages/api/src/drizzle/schema/club.schema.ts
  packages/api/src/drizzle/schema/division.schema.ts
  packages/api/src/feature/division/controller/division.controller.ts
  packages/api/src/feature/division/model/district.model.ts
  packages/api/src/feature/division/model/division.model.ts
  packages/api/src/feature/division/model/division.summary.model.ts
  packages/api/src/feature/division/repository/division.repository.ts
  packages/api/src/feature/division/service/division.service.ts
  packages/interface/src/api/club/type/club.type.ts
  packages/interface/src/api/division/endpoint/apiDiv001.ts
  packages/interface/src/api/division/endpoint/apiDiv002.ts
  packages/interface/src/api/division/type/division.type.ts
  packages/web/src/common/components/ExecutiveRegistrationTable.tsx
  packages/web/src/common/hooks/useGetDivisionType.ts
  packages/web/src/common/services/getDivisions.ts
  packages/web/src/constants/tableTagList.ts
  packages/web/src/features/executive/_mock/mockupMemberRegistration.ts
  packages/web/src/features/executive/register-club/frames/ClubRegisterDetailFrame.tsx
  packages/web/src/features/executive/register-club/frames/ExecutiveRegistrationClubFrame.tsx
  packages/web/src/features/executive/register-club/services/_mock/mockRegisterClub.ts
  packages/web/src/features/executive/register-member/_mock/mockMemberRegistration.tsx
  packages/web/src/features/executive/register-member/frames/ExecutiveRegisterMemberFrame.tsx
  packages/web/src/features/my/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/features/permanent/register-club/components/ClubRegistrationTable.tsx
  packages/web/src/features/permanent/register-club/frames/ClubRegisterDetailFrame.tsx
  packages/web/src/features/permanent/register-club/frames/RegistrationClubFrame.tsx
  packages/web/src/features/register-club/components/basic-info/_atomic/DivisionSelect.tsx
  packages/web/src/types/divisions.types.ts
Labels: new feature, back-end, interface

#1481 [TU-71] refactor: fix mock for registration member
  packages/web/src/common/components/RegisterMemberTable.tsx
  packages/web/src/features/executive/_mock/mockupMemberRegistration.ts
  packages/web/src/features/executive/register-member/_mock/mockupMemberRegistration.ts
  packages/web/src/features/executive/register-member/services/getMemberRegistration.ts
Labels: front-end, refactor

#1486 [TU-79] gb credit
  packages/web/src/features/credits/credits.ts
Labels: good first issue

#1490 [TU-51] hama credit
  .gitignore
  packages/web/src/features/credits/credits.ts
Labels: front-end

#1489 [TU-80] fix reg 002, 003, 018, 025 for finding registrationable clubs with club entities
  packages/api/src/drizzle/schema/club.schema.ts
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/club/delegate/delegate.service.ts
  packages/api/src/feature/club/model/club.model.ts
  packages/api/src/feature/club/model/club.summary.model.ts
  packages/api/src/feature/club/repository/club.club-student-t.repository.ts
  packages/api/src/feature/club/repository/club.repository.ts
  packages/api/src/feature/club/repository/club.semester-d.repository.ts
  packages/api/src/feature/club/service/club.public.service.ts
  packages/api/src/feature/club/service/club.service.ts
  packages/api/src/feature/funding/service/funding.service.ts
  packages/api/src/feature/registration/club-registration/club-registration.module.ts
  packages/api/src/feature/registration/club-registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
  packages/api/src/feature/registration/member-registration/repository/member-registration.repository.ts
  packages/api/src/feature/rental/repository/rental.rental-order.repository.ts
  packages/api/src/feature/user/repository/professor.repository.ts
  packages/api/src/feature/user/service/user.public.service.ts
  packages/interface/src/api/activity-certificate/endpoint/apiAcf002.ts
  packages/interface/src/api/club/endpoint/apiClb001.ts
  packages/interface/src/api/club/endpoint/apiClb002.ts
  packages/interface/src/api/club/endpoint/apiClb003.ts
  packages/interface/src/api/club/endpoint/apiClb016.ts
  packages/interface/src/api/club/type/club.type.ts
  packages/interface/src/api/user/endpoint/apiUsr001.ts
  packages/interface/src/api/user/type/user.type.ts
  packages/interface/src/common/enum/club.enum.ts
  packages/web/src/app/executive/activity-report/club/[id]/page.tsx
  packages/web/src/app/executive/funding/club/[id]/page.tsx
  packages/web/src/common/services/_mock/mockupUserProfile.ts
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoFirstFrame.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoThirdFrame.tsx
  packages/web/src/features/activity-certificate/services/_mock/mockupUserClubs.ts
  packages/web/src/features/clubs/components/ClubCard.tsx
  packages/web/src/features/clubs/components/ClubListGrid.tsx
  packages/web/src/features/clubs/components/ClubRegistrationButton.tsx
  packages/web/src/features/clubs/components/RegisterInfo.tsx
  packages/web/src/features/clubs/frames/ClubDetailPublicFrame.tsx
  packages/web/src/features/clubs/frames/ClubDetailStudentFrame.tsx
  packages/web/src/features/clubs/frames/ClubsListFrame.tsx
  packages/web/src/features/clubs/services/_mock/mockupClubData.ts
  packages/web/src/features/clubs/services/_mock/mockupClubDetail.ts
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoFirstFrame.tsx
  packages/web/src/features/common-space/frames/CommonSpaceInfoFrame/CommonSpaceInfoThirdFrame.tsx
  packages/web/src/features/executive/funding/components/ExecutiveFundingClubTable.tsx
  packages/web/src/features/executive/funding/frames/ExecutiveFundingClubFrame.tsx
  packages/web/src/features/executive/register-member/frames/ExecutiveRegisterMemberDetailFrame.tsx
  packages/web/src/features/manage-club/frames/ProfessorManageClubFrame/index.tsx
  packages/web/src/features/manage-club/frames/RegistrationManageFrame.tsx
  packages/web/src/features/manage-club/frames/_atomic/RepresentativeLoadFrame.tsx
  packages/web/src/features/manage-club/members/components/RegisterMemberList.tsx
  packages/web/src/features/my/clubs/service/_mock/mockMyClubList.ts
  packages/web/src/features/printing-business/components/PrintingBusinessForm/PrintingBusinessFormFirst.tsx
  packages/web/src/features/printing-business/components/PrintingBusinessForm/PrintingBusinessFormThird.tsx
  packages/web/src/features/printing-business/components/PrintingBusinessForm/index.tsx
  packages/web/src/features/rental-business/frames/RentalInfoFrame/RentalInfoFirstFrame.tsx
Labels: bug, back-end

#1493 [TU-56] edge credit
  packages/web/src/features/credits/credits.ts
Labels: front-end

#1488 [TU-76] update register-club professor initial data trigger logic
  packages/web/src/features/my/register-club/frames/MyRegisterClubEditFrame.tsx
  packages/web/src/features/register-club/components/RegisterClubForm.tsx
  packages/web/src/features/register-club/components/basic-info/BasicInformFrame.tsx
  packages/web/src/features/register-club/components/basic-info/ProfessorInformFrame.tsx
  packages/web/src/features/register-club/components/basic-info/ProvisionalBasicInformFrame.tsx
Labels: bug, front-end

#1494 [TU-81] Add eslint rule for windows developers
  .vscode/settings.json
Labels: bug
