Repository sparcs-kaist/clubs, pull requests merged in 2025-07, with the labels that each got.

#1649 Version 0.0.78
  .env.example
  packages/api/src/feature/auth/dto/sparcs-sso.dto.ts
  packages/api/src/feature/auth/repository/auth.repository.ts
  packages/api/src/feature/auth/service/auth.service.ts
  packages/web/src/common/components/Header/_atomic/Login.tsx
  packages/web/src/common/components/Modal/AgreeModal.tsx
  packages/web/src/common/components/MyMenu/_atomic/Profile.tsx
  packages/web/src/constants/patchNote.ts
  packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
  packages/web/src/features/activity-report/hooks/useGetActivityReportDetail.ts
  packages/web/src/features/credits/credits.ts
  packages/web/src/features/landing/components/Banner.tsx
  packages/web/src/features/landing/components/MoreSectionTitle.tsx
  packages/web/src/features/landing/frames/MainPageMainFrame.tsx
  packages/web/src/features/landing/frames/NoticeSectionFrame.tsx
  packages/web/src/i18n/messages/en/agree.json
  packages/web/src/i18n/messages/en/common.json
  packages/web/src/i18n/messages/en/division.json
  packages/web/src/i18n/messages/en/main.json
  packages/web/src/i18n/messages/en/path.json
  packages/web/src/i18n/messages/ko/agree.json
  packages/web/src/i18n/messages/ko/common.json
  packages/web/src/i18n/messages/ko/division.json
  packages/web/src/i18n/messages/ko/main.json
  packages/web/src/i18n/messages/ko/path.json
  packages/web/src/i18n/request.ts
Labels: release

#1650 [TU-233] 집행부원 활보 동아리별 상세 조회 페이지 마진 수정
  packages/web/src/features/activity-report/components/executive/ExecutiveCurrentActivityReportSection.tsx
  packages/web/src/features/activity-report/components/executive/ExecutivePastActivityReportSection.tsx
Labels: front-end

#1654 [TU-271] i18n readme
  packages/web/src/i18n/README.md
Labels: documentation, front-end

#1655 [TU-276] Next가 500과 함께 서빙하는 문제 해결하기
  packages/web/src/common/providers/AuthContext.tsx
  packages/web/src/utils/localStorage.ts
Labels: front-end

#1656 [TU-277] Add club interface doc
  .zed/settings.json
  packages/api/src/feature/club/controller/club.controller.ts
  packages/api/src/feature/club/delegate/delegate.controller.ts
  packages/api/src/feature/club/delegate/delegate.service.ts
  packages/domain/package.json
  packages/domain/src/club/club-delegate.ts
  packages/domain/src/club/club.ts
  packages/interface/package.json
  packages/interface/src/api/club/endpoint/apiClb001.ts
  packages/interface/src/api/club/endpoint/apiClb002.ts
  packages/interface/src/api/club/endpoint/apiClb003.ts
  packages/interface/src/api/club/endpoint/apiClb004.ts
  packages/interface/src/api/club/endpoint/apiClb005.ts
  packages/interface/src/api/club/endpoint/apiClb006.ts
  packages/interface/src/api/club/endpoint/apiClb007.ts
  packages/interface/src/api/club/endpoint/apiClb008.ts
  packages/interface/src/api/club/endpoint/apiClb009.ts
  packages/interface/src/api/club/endpoint/apiClb010.ts
  packages/interface/src/api/club/endpoint/apiClb011.ts
  packages/interface/src/api/club/endpoint/apiClb012.ts
  packages/interface/src/api/club/endpoint/apiClb013.ts
  packages/interface/src/api/club/endpoint/apiClb014.ts
  packages/interface/src/api/club/endpoint/apiClb015.ts
  packages/interface/src/api/club/endpoint/apiClb016.ts
  packages/interface/src/api/club/index.ts
  packages/web/src/features/manage-club/services/_mock/mockDelegate.ts
  packages/web/src/features/manage-club/services/getChangeDelegateRequests.ts
  pnpm-lock.yaml
Labels: back-end

#1659 Version 0.0.81
  .zed/settings.json
  packages/api/src/common/util/util.ts
  packages/api/src/feature/club/controller/club.controller.ts
  packages/api/src/feature/club/delegate/club.club-delegate-d.repository.ts
  packages/api/src/feature/club/delegate/delegate.controller.ts
  packages/api/src/feature/club/delegate/delegate.service.ts
  packages/domain/package.json
  packages/domain/src/club/club-delegate.ts
  packages/domain/src/club/club.ts
  packages/interface/package.json
  packages/interface/src/api/club/endpoint/apiClb001.ts
  packages/interface/src/api/club/endpoint/apiClb002.ts
  packages/interface/src/api/club/endpoint/apiClb003.ts
  packages/interface/src/api/club/endpoint/apiClb004.ts
  packages/interface/src/api/club/endpoint/apiClb005.ts
  packages/interface/src/api/club/endpoint/apiClb006.ts
  packages/interface/src/api/club/endpoint/apiClb007.ts
  packages/interface/src/api/club/endpoint/apiClb008.ts
  packages/interface/src/api/club/endpoint/apiClb009.ts
  packages/interface/src/api/club/endpoint/apiClb010.ts
  packages/interface/src/api/club/endpoint/apiClb011.ts
  packages/interface/src/api/club/endpoint/apiClb012.ts
  packages/interface/src/api/club/endpoint/apiClb013.ts
  packages/interface/src/api/club/endpoint/apiClb014.ts
  packages/interface/src/api/club/endpoint/apiClb015.ts
  packages/interface/src/api/club/endpoint/apiClb016.ts
  packages/interface/src/api/club/index.ts
  packages/web/src/common/providers/AuthContext.tsx
  packages/web/src/constants/patchNote.ts
  packages/web/src/features/landing/frames/NoticeSectionFrame.tsx
  packages/web/src/features/manage-club/services/_mock/mockDelegate.ts
  packages/web/src/features/manage-club/services/getChangeDelegateRequests.ts
  packages/web/src/features/my/frames/MyChangesFrame.tsx
  packages/web/src/features/notices/services/useGetNotice.ts
  packages/web/src/i18n/README.md
  packages/web/src/utils/localStorage.ts
  pnpm-lock.yaml
Labels: release

#1660 Version 0.0.82
  packages/api/src/drizzle/schema/funding.schema.ts
  packages/api/src/drizzle/schema/user.schema.ts
  packages/api/src/feature/club/delegate/club.club-delegate-d.repository.ts
  packages/api/src/feature/club/delegate/delegate.service.ts
  packages/api/src/feature/club/repository-old/club.club-student-t.repository.ts
  packages/api/src/feature/overview/repository/overview.repository.ts
  packages/api/src/feature/registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/service/registration.service.ts
  packages/api/src/feature/user/repository/executive.repository.ts
  packages/api/src/feature/user/repository/old.professor.repository.ts
  packages/api/src/feature/user/repository/old.student.repository.ts
  packages/api/src/feature/user/repository/professor.repository.ts
  packages/api/src/feature/user/repository/student.repository.ts
  packages/api/src/feature/user/repository/user.repository.ts
  packages/web/src/constants/patchNote.ts
Labels: release

#1663 [TU-281] 교통비 지원금 studentT 혼용
  packages/api/src/drizzle/schema/funding.schema.ts
  packages/api/src/feature/funding/repository/funding.repository.ts
Labels: back-end

#1661 [TU-279] 동아리 대표자 변경, 활보, 지원금 마이너한 수정사항들
  packages/web/src/features/manage-club/components/ChangeRepresentativeInfo.tsx
  packages/web/src/features/manage-club/funding/frames/FundingInfoFrame.tsx
Labels: front-end

#1665 [TU-285] 집행부원 지원금 동아리 조회 페이지에 학기별 조회 기능 추가
  packages/api/src/feature/funding/controller/funding.controller.ts
  packages/api/src/feature/funding/service/funding.service.ts
  packages/interface/src/api/funding/endpoint/apiFnd009.ts
  packages/web/src/app/executive/funding/club/[id]/page.tsx
  packages/web/src/constants/patchNote.ts
  packages/web/src/features/executive/funding/components/ExecutiveClubFundingsTable.tsx
  packages/web/src/features/executive/funding/components/ExecutiveCurrentFundingSection.tsx
  packages/web/src/features/executive/funding/components/ExecutivePastFundingSection.tsx
  packages/web/src/features/executive/funding/frames/ExecutiveFundingClubFrame.tsx
  packages/web/src/features/executive/funding/hooks/useGetExecutiveClubFunding.ts
  packages/web/src/features/executive/funding/services/useGetClubFundings.ts
  packages/web/src/features/executive/funding/services/useGetExecutiveClubFundingForDuration.ts
  packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
Labels: front-end

#1668 Version 0.0.83
  packages/api/src/drizzle/schema/funding.schema.ts
  packages/api/src/drizzle/schema/semester.schema.ts
  packages/api/src/feature/funding/controller/funding.controller.ts
  packages/api/src/feature/funding/repository/funding.repository.ts
  packages/api/src/feature/funding/service/funding.service.ts
  packages/api/src/feature/semester/controller/semester.controller.ts
  packages/api/src/feature/semester/repository/semester.sql.repository.ts
  packages/api/src/feature/semester/semester.module.ts
  packages/api/src/feature/semester/service/semester.service.ts
  packages/api/src/feature/user/repository/old.student.repository.ts
  packages/eslint-config/base.mjs
  packages/eslint-config/custom_rules/eslint-plugin-zod-requestquery-array.mjs
  packages/interface/src/api/funding/endpoint/apiFnd009.ts
  packages/interface/src/api/funding/endpoint/apiFnd016.ts
  packages/interface/src/api/semester/apiSem002.ts
  packages/interface/src/api/semester/apiSem003.ts
  packages/interface/src/api/semester/apiSem004.ts
  packages/interface/src/api/semester/index.ts
  packages/web/src/app/executive/funding/club/[id]/page.tsx
  packages/web/src/constants/patchNote.ts
  packages/web/src/features/activity-report/components/executive/ExecutiveActivityChargedTable.tsx
  packages/web/src/features/activity-report/components/executive/ExecutiveActivityClubTable.tsx
  packages/web/src/features/activity-report/frames/executive/ExecutiveActivityReportFrame.tsx
  packages/web/src/features/executive/funding/components/ExecutiveClubFundingsTable.tsx
  packages/web/src/features/executive/funding/components/ExecutiveCurrentFundingSection.tsx
  packages/web/src/features/executive/funding/components/ExecutivePastFundingSection.tsx
  packages/web/src/features/executive/funding/frames/ExecutiveFundingClubFrame.tsx
  packages/web/src/features/executive/funding/hooks/useGetExecutiveClubFunding.ts
  packages/web/src/features/executive/funding/services/useGetClubFundings.ts
  packages/web/src/features/executive/funding/services/useGetExecutiveClubFundingForDuration.ts
  packages/web/src/features/manage-club/components/ChangeRepresentativeInfo.tsx
  packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
  packages/web/src/features/manage-club/funding/frames/FundingInfoFrame.tsx
Labels: release

#1670 Version 0.0.84
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/service/activity.service.new.ts
  packages/api/src/feature/funding/service/funding.service.ts
  packages/interface/src/api/activity/endpoint/apiAct002.ts
  packages/web/src/app/operating-committee/[id]/page.tsx
  packages/web/src/constants/patchNote.ts
  packages/web/src/constants/paths.ts
  packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
  packages/web/src/features/activity-report/hooks/useGetActivityReportDetail.ts
  packages/web/src/features/activity-report/services/useGetActivityReport.ts
Labels: release
