Repository sparcs-kaist/clubs, pull requests merged in 2025-08, with the labels that each got.

#1673 Version 0.0.86
  packages/web/src/constants/patchNote.ts
Labels: release

#1677 [TU-291] 학기 추가 기능 코멘트 추가
  packages/web/src/common/components/NavTools/NavItem.tsx
  packages/web/src/constants/paths.ts
  packages/web/src/features/executive/frames/ExecutiveDashboardFrame.tsx
  packages/web/src/features/executive/frames/ManageSemesterFrame.tsx
Labels: front-end

#1679 [TU-289] operation committee secret key CRD
  package.json
  packages/api/src/app.module.ts
  packages/api/src/drizzle/schema/operation-committee.schema.ts
  packages/api/src/feature/activity/activity.module.ts
  packages/api/src/feature/activity/service/activity.service.new.ts
  packages/api/src/feature/operation-committee/controller/operation-committee.controller.ts
  packages/api/src/feature/operation-committee/operation-committee.module.ts
  packages/api/src/feature/operation-committee/repository/operation-committee.repository.ts
  packages/api/src/feature/operation-committee/service/operation-committee.service.ts
  packages/domain/src/operation-committee/operation-committeekey.ts
  packages/interface/src/api/operation-committee/apiOpC001.ts
  packages/interface/src/api/operation-committee/apiOpC002.ts
  packages/interface/src/api/operation-committee/apiOpC003.ts
  packages/interface/src/api/operation-committee/index.ts
Labels: back-end, interface

#1687 [TU-305] 지원금 기간 관리 페이지 추가
  packages/web/src/app/executive/funding/deadline/page.tsx
  packages/web/src/features/executive/frames/ExecutiveDashboardFrame.tsx
  packages/web/src/features/executive/funding/components/FundingDeadlineFormModal.tsx
  packages/web/src/features/executive/funding/components/FundingDeadlineSection.tsx
  packages/web/src/features/executive/funding/components/FundingDeadlineSectionList.tsx
  packages/web/src/features/executive/funding/components/FundingDeadlineTable.tsx
  packages/web/src/features/executive/funding/hooks/useGetAllFundingDeadlines.ts
  packages/web/src/features/executive/funding/services/useCreateFundingDeadline.ts
  packages/web/src/features/executive/funding/services/useDeleteFundingDeadline.ts
  packages/web/src/features/executive/funding/services/useGetFundingDeadlines.ts
  packages/web/src/features/executive/services/useGetActivityDurations.ts
Labels: front-end

#1689 [TU-292] 활동보고서 신청 기간 조회/추가/제거 기능 구현하기
  packages/api/src/feature/semester/service/activity-duration.service.ts
  packages/interface/src/api/semester/apiSem007.ts
  packages/web/src/app/executive/activity-report/deadline/page.tsx
  packages/web/src/features/executive/components/ActivityDeadlineFormModal.tsx
  packages/web/src/features/executive/components/ActivityDeadlineSection.tsx
  packages/web/src/features/executive/components/ActivityDeadlineTable.tsx
  packages/web/src/features/executive/frames/ExecutiveDashboardFrame.tsx
  packages/web/src/features/executive/frames/ManageActivityDeadlineFrame.tsx
  packages/web/src/features/executive/hooks/useGroupActivityDeadlines.ts
  packages/web/src/features/executive/services/getActivityDeadlines.ts
  packages/web/src/features/executive/services/useCreateActivityDeadline.ts
  packages/web/src/features/executive/services/useDeleteActivityDeadline.ts
Labels: front-end

#1688 [TU-304] 운영위원 비밀키 관리 UI 구현
  packages/api/lagacy_source/feature/meeting/meeting.gateway.ts
  packages/typescript-config/dist/tsconfig.build.tsbuildinfo
  packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
  packages/web/src/features/executive/components/SecretKey/AccessLinkSection.tsx
  packages/web/src/features/executive/components/SecretKey/ErrorMessage.tsx
  packages/web/src/features/executive/components/SecretKey/HeaderButtons.tsx
  packages/web/src/features/executive/components/SecretKey/OperationCommitteeSecretManager.tsx
  packages/web/src/features/executive/components/SecretKey/SecretKeySection.tsx
  packages/web/src/features/executive/components/SecretKey/index.ts
  packages/web/src/features/executive/components/SecretKey/types.ts
  packages/web/src/features/executive/frames/ExecutiveDashboardFrame.tsx
  packages/web/src/features/executive/hooks/useOperationCommitteeSecret.ts
  packages/web/src/features/executive/services/operationCommitteeSecret.ts
Labels: front-end
