Repository sparcs-kaist/clubs, pull requests merged in 2025-01, with the labels that each got.

#1290 Implement activity check features for executives (ACT-024, ACT-025)
  packages/api/src/drizzle/schema/activity.schema.ts
  packages/api/src/feature/activity/activity.module.ts
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/repository/activity.activity-club-charged-executive.repository.ts
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/interface/src/api/activity/endpoint/apiAct024.ts
  packages/interface/src/common/type/id.type.ts
Labels: back-end, interface

#1291 Act-025
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/api/src/feature/user/repository/executive.repository.ts
  packages/api/src/feature/user/service/user.public.service.ts
  packages/interface/src/api/activity/endpoint/apiAct025.ts
Labels: back-end, interface

#1293 지도교수 없을 경우 승인 여부 UI
  packages/web/src/features/activity-report/components/CurrentActivityReportTable.tsx
  packages/web/src/features/activity-report/components/tables/ProfessorActivityReportTable.tsx
  packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
  packages/web/src/features/activity-report/hooks/useGetActivityReportDetail.ts
  packages/web/src/features/activity-report/hooks/useGetCurrentActivityReportList.ts
  packages/web/src/features/activity-report/hooks/useGetProfessorActivityReportList.ts
  packages/web/src/features/activity-report/types/activityReport.ts
  packages/web/src/features/activity-report/types/table.ts
  packages/web/src/features/clubs/hooks/useHasAdvisor.ts
Labels: front-end

#1294 refactor /clubs
  packages/web/src/app/clubs/[id]/page.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoThirdFrame.tsx
  packages/web/src/features/clubs/components/ClubDetailCard.tsx
  packages/web/src/features/clubs/components/ClubInfoCard/ClubInfoItem.tsx
  packages/web/src/features/clubs/components/ClubInfoCard/index.tsx
  packages/web/src/features/clubs/components/ClubMemberCard.tsx
  packages/web/src/features/clubs/components/ClubRegistrationButton.tsx
  packages/web/src/features/clubs/components/RegisterInfo.tsx
  packages/web/src/features/clubs/components/_atomic/ClubRegistrationButtonWrapper.tsx
  packages/web/src/features/clubs/frames/ClubDetailInfoFrame.tsx
  packages/web/src/features/clubs/frames/ClubDetailPublicFrame.tsx
  packages/web/src/features/clubs/frames/ClubDetailStudentFrame.tsx
  packages/web/src/features/clubs/hooks/useHasAdvisor.ts
  packages/web/src/features/clubs/services/_mock/mockupClubDetail.ts
  packages/web/src/features/clubs/services/_mock/mockupRegistraion.ts
  packages/web/src/features/clubs/services/getClubDetail.ts
  packages/web/src/features/clubs/services/getMyMemberRegistration.ts
  packages/web/src/features/clubs/services/registerClub.ts
  packages/web/src/features/clubs/services/unregisterClub.ts
  packages/web/src/features/executive/register-member/frames/ExecutiveRegisterMemberDetailFrame.tsx
  packages/web/src/features/manage-club/frames/MemberManageFrame.tsx
  packages/web/src/features/manage-club/frames/ProfessorManageClubFrame/ClubInfoSection.tsx
  packages/web/src/features/manage-club/frames/RegistrationManageFrame.tsx
  packages/web/src/features/manage-club/frames/_atomic/RepresentativeLoadFrame.tsx
  packages/web/src/features/manage-club/members/components/RegisterMemberList.tsx
  packages/web/src/features/my/frames/_atomic/MyMemberRegisterFrame.tsx
Labels: front-end

#1295 Implement act 026
  packages/api/src/drizzle/schema/activity.schema.ts
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/repository/activity.activity-club-charged-executive.repository.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/interface/src/api/activity/endpoint/apiAct026.ts
Labels: back-end, interface

#1296 Merge dev into main
  packages/api/src/drizzle/schema/activity.schema.ts
  packages/api/src/feature/activity/activity.module.ts
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/repository/activity.activity-club-charged-executive.repository.ts
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/api/src/feature/file/service/file.public.service.ts
  packages/api/src/feature/funding/funding.controller.ts
  packages/api/src/feature/funding/funding.repository.ts
  packages/api/src/feature/funding/funding.service.ts
  packages/api/src/feature/user/repository/executive.repository.ts
  packages/api/src/feature/user/service/user.public.service.ts
  packages/interface/src/api/activity/endpoint/apiAct024.ts
  packages/interface/src/api/activity/endpoint/apiAct025.ts
  packages/interface/src/api/activity/endpoint/apiAct026.ts
  packages/interface/src/api/funding/apiFnd001.ts
  packages/interface/src/api/funding/apiFnd002.ts
  packages/interface/src/api/funding/apiFnd003.ts
  packages/interface/src/api/funding/apiFnd004.ts
  packages/interface/src/api/funding/apiFnd005.ts
  packages/interface/src/api/funding/apiFnd006.ts
  packages/interface/src/api/funding/index.ts
  packages/interface/src/common/type/id.type.ts
  packages/web/src/app/clubs/[id]/page.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoThirdFrame.tsx
  packages/web/src/features/activity-report/components/CurrentActivityReportTable.tsx
  packages/web/src/features/activity-report/components/tables/ProfessorActivityReportTable.tsx
  packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
  packages/web/src/features/activity-report/hooks/useGetActivityReportDetail.ts
  packages/web/src/features/activity-report/hooks/useGetCurrentActivityReportList.ts
  packages/web/src/features/activity-report/hooks/useGetProfessorActivityReportList.ts
  packages/web/src/features/activity-report/types/activityReport.ts
  packages/web/src/features/activity-report/types/table.ts
  packages/web/src/features/clubs/components/ClubDetailCard.tsx
  packages/web/src/features/clubs/components/ClubInfoCard/ClubInfoItem.tsx
  packages/web/src/features/clubs/components/ClubInfoCard/index.tsx
  packages/web/src/features/clubs/components/ClubMemberCard.tsx
  packages/web/src/features/clubs/components/ClubRegistrationButton.tsx
  packages/web/src/features/clubs/components/RegisterInfo.tsx
  packages/web/src/features/clubs/components/_atomic/ClubRegistrationButtonWrapper.tsx
  packages/web/src/features/clubs/frames/ClubDetailInfoFrame.tsx
  packages/web/src/features/clubs/frames/ClubDetailPublicFrame.tsx
  packages/web/src/features/clubs/frames/ClubDetailStudentFrame.tsx
  packages/web/src/features/clubs/hooks/useHasAdvisor.ts
  packages/web/src/features/clubs/services/_mock/mockupClubDetail.ts
  packages/web/src/features/clubs/services/_mock/mockupRegistraion.ts
  packages/web/src/features/clubs/services/getClubDetail.ts
  packages/web/src/features/clubs/services/getMyMemberRegistration.ts
  packages/web/src/features/clubs/services/registerClub.ts
  packages/web/src/features/clubs/services/unregisterClub.ts
  packages/web/src/features/credits/credits.ts
  packages/web/src/features/executive/register-member/frames/ExecutiveRegisterMemberDetailFrame.tsx
  packages/web/src/features/manage-club/frames/MemberManageFrame.tsx
  packages/web/src/features/manage-club/frames/ProfessorManageClubFrame/ClubInfoSection.tsx
  packages/web/src/features/manage-club/frames/RegistrationManageFrame.tsx
  packages/web/src/features/manage-club/frames/_atomic/RepresentativeLoadFrame.tsx
  packages/web/src/features/manage-club/funding/services/useGetNewFundingList.ts
  packages/web/src/features/manage-club/members/components/RegisterMemberList.tsx
  packages/web/src/features/manage-club/services/_mock/mockFundingDetail.ts
  packages/web/src/features/my/frames/_atomic/MyMemberRegisterFrame.tsx
Labels: release

#1292 impl executive activity report page
  packages/web/src/app/executive/activity-report/page.tsx
  packages/web/src/app/not-found.tsx
  packages/web/src/constants/tableTagList.ts
  packages/web/src/features/credits/credits.ts
  packages/web/src/features/executive/activity-report/components/ActivityReportStatistic.tsx
  packages/web/src/features/executive/activity-report/components/ExecutiveActivityClubTable.tsx
  packages/web/src/features/executive/activity-report/frames/ExecutiveActivityReportFrame.tsx
  packages/web/src/features/executive/activity-report/services/useGetExecutiveActivities.tsx
  packages/web/src/features/executive/register-member/components/StatusInfoFrame.tsx
Labels: enhancement, front-end

#1245 Create storybook for TextInput, Card, Modal
  packages/web/src/common/components/Card.tsx
  packages/web/src/common/components/Modal/AgreeModal.tsx
  packages/web/src/common/components/Modal/ErrorModal.tsx
  packages/web/src/stories/Card.stories.tsx
  packages/web/src/stories/Modal.stories.tsx
  packages/web/src/stories/TextInput.stories.tsx
Labels: front-end

#1231 feat: replace TextEditor to Markdown
  package-lock.json
  packages/web/src/common/components/Markdown/index.tsx
  packages/web/src/features/meeting/agenda/create/components/AgendaBlock.tsx
  packages/web/src/features/meeting/agenda/create/components/AgendaEditor.tsx
  packages/web/src/features/meeting/agenda/create/components/AgendaViewer.tsx
  packages/web/src/features/meeting/services/_mock/mockupMeetingAgenda.ts
Labels: front-end

#1301 1300 refactor funding
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/funding/controller/funding.controller.ts
  packages/api/src/feature/funding/funding.module.ts
  packages/api/src/feature/funding/funding.repository.ts
  packages/api/src/feature/funding/funding.service.ts
  packages/api/src/feature/funding/model/funding.model.ts
  packages/api/src/feature/funding/repository/funding.repository.ts
  packages/api/src/feature/funding/service/funding.service.ts
  packages/interface/src/api/activity/type/activity.type.ts
  packages/interface/src/api/file/type/file.type.ts
  packages/interface/src/api/funding/apiFnd001.ts
  packages/interface/src/api/funding/apiFnd002.ts
  packages/interface/src/api/funding/apiFnd003.ts
  packages/interface/src/api/funding/apiFnd005.ts
  packages/interface/src/api/funding/apiFnd006.ts
  packages/interface/src/api/funding/type/funding.type.ts
  packages/interface/src/api/user/type/user.type.ts
  packages/web/src/features/manage-club/funding/components/NewFundingListSection.tsx
Labels: back-end

#1308 Add more information on act023
  packages/api/src/drizzle/schema/club.schema.ts
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/api/src/feature/user/repository/executive.repository.ts
  packages/api/src/feature/user/service/user.public.service.ts
  packages/interface/src/api/activity/endpoint/apiAct023.ts
  packages/web/src/features/executive/activity-report/frames/ExecutiveActivityReportFrame.tsx
Labels: back-end, interface

#1311 impl ExecutiveActivityChargedTable
  packages/web/src/features/executive/activity-report/components/ChargedActivityModalTable.tsx
  packages/web/src/features/executive/activity-report/components/ExecutiveActivityChargedTable.tsx
  packages/web/src/features/executive/activity-report/components/ExecutiveActivityClubTable.tsx
  packages/web/src/features/executive/activity-report/components/ExecutiveClubActivitiesTable.tsx
  packages/web/src/features/executive/activity-report/frames/ExecutiveActivityReportFrame.tsx
Labels: enhancement, front-end

#1317 refactor: improve sorting of activity durations and terms
  packages/api/src/feature/activity/service/activity.activity-term.service.ts
  packages/api/src/feature/activity/service/activity.service.ts
Labels: back-end

#1287 connect create funding api
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/funding/service/funding.service.ts
  packages/web/src/app/manage-club/funding/[id]/edit/page.tsx
  packages/web/src/app/manage-club/funding/create/page.tsx
  packages/web/src/common/components/Forms/DateInput.tsx
  packages/web/src/features/activity-certificate/frames/ActivityCertificateInfoFrame/ActivityCertificateInfoSecondFrame.tsx
  packages/web/src/features/activity-report/_mock/mock.ts
  packages/web/src/features/activity-report/components/ActivityReportForm.tsx
  packages/web/src/features/activity-report/components/SelectParticipant.tsx
  packages/web/src/features/activity-report/hooks/useGetActivityReportDetail.ts
  packages/web/src/features/activity-report/hooks/useGetInitialActivityReportFormData.ts
  packages/web/src/features/activity-report/types/activityReport.ts
  packages/web/src/features/manage-club/funding/components/FixtureEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/components/NonCorpEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/components/OtherEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/components/TransportEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/frames/AddEvidenceFrame.tsx
  packages/web/src/features/manage-club/funding/frames/BasicEvidenceFrame.tsx
  packages/web/src/features/manage-club/funding/frames/CreateFundingFrame.tsx
  packages/web/src/features/manage-club/funding/frames/EditFundingFrame.tsx
  packages/web/src/features/manage-club/funding/frames/FundingForm.tsx
  packages/web/src/features/manage-club/funding/frames/FundingInfoFrame.tsx
  packages/web/src/features/manage-club/funding/hooks/useCreateFunding.ts
  packages/web/src/features/manage-club/funding/hooks/useGetInitialFundingForm.ts
  packages/web/src/features/manage-club/funding/hooks/useUpdateFunding.ts
  packages/web/src/features/manage-club/funding/services/useGetFunding.ts
  packages/web/src/features/manage-club/funding/services/useGetNewFundingList.ts
  packages/web/src/features/manage-club/funding/services/usePostFunding.ts
  packages/web/src/features/manage-club/funding/services/usePutFunding.ts
  packages/web/src/features/manage-club/funding/types/funding.ts
  packages/web/src/features/manage-club/services/_mock/mockFundingDetail.ts
  packages/web/src/features/register-club/components/_atomic/ActivityReportForm.tsx
  packages/web/src/utils/isTransportation.ts
Labels: front-end

#1335 동아리방 비밀번호 필드 주서처리
  packages/web/src/features/manage-club/components/ChangeClubInfoCard.tsx
Labels: front-end

#1336 fix: utc timezone value to kst
  packages/api/src/feature/club/repository/club.club-student-t.repository.ts
Labels: bug, back-end

#1328 refactor: rename fundingOrder to funding and update related fields in funding schema, model, repository, and service
  packages/api/src/drizzle/schema/funding.schema.ts
  packages/api/src/feature/funding/model/funding.model.ts
  packages/api/src/feature/funding/repository/funding.repository.ts
  packages/api/src/feature/funding/service/funding.service.ts
  packages/interface/src/api/funding/type/funding.type.ts
  packages/interface/src/common/enum/funding.enum.ts
  packages/web/src/constants/tableTagList.ts
  packages/web/src/features/manage-club/funding/components/FixtureEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/components/TransportEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/components/_atomic/NewFundingListTable.tsx
  packages/web/src/features/manage-club/funding/detail/components/FixtureEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/components/TransportationEvidenceList.tsx
  packages/web/src/features/manage-club/funding/hooks/useCreateFunding.ts
  packages/web/src/features/manage-club/funding/hooks/useGetInitialFundingForm.ts
  packages/web/src/features/manage-club/funding/hooks/useUpdateFunding.ts
  packages/web/src/features/manage-club/funding/types/funding.ts
  packages/web/src/features/manage-club/services/_mock/mockFundingDetail.ts
  packages/web/src/features/manage-club/services/_mock/mockManageClub.ts
Labels: back-end

#1325 과거 활보 수정, 삭제, 승인 버튼 안 보이도록 변경
  packages/web/src/features/activity-report/components/PastActivityReportTable.tsx
  packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
  packages/web/src/features/activity-report/frames/ActivityReportMainFrame.tsx
  packages/web/src/features/activity-report/services/useGetActivityDeadline.ts
Labels: front-end

#1338 chore: divide error case for change delegate accept
  packages/api/src/feature/club/delegate/club.club-delegate-d.repository.ts
Labels: bug, back-end

#1315 impl change charged executive
  packages/web/src/common/components/Select/SelectOption.tsx
  packages/web/src/common/components/Select/index.tsx
  packages/web/src/common/components/Table/CheckboxCenterPlacerStopPropagation.tsx
  packages/web/src/features/executive/activity-report/components/ChargedChangeActivityModalContent.tsx
  packages/web/src/features/executive/activity-report/components/ChargedChangeActivityModalTable.tsx
  packages/web/src/features/executive/activity-report/components/ChargedChangeClubModalContent.tsx
  packages/web/src/features/executive/activity-report/components/ChargedChangeClubModalTable.tsx
  packages/web/src/features/executive/activity-report/components/ExecutiveActivityChargedTable.tsx
  packages/web/src/features/executive/activity-report/components/ExecutiveActivityClubTable.tsx
  packages/web/src/features/executive/activity-report/components/ExecutiveClubActivitiesTable.tsx
  packages/web/src/features/executive/activity-report/frames/ExecutiveActivityReportClubFrame.tsx
  packages/web/src/features/executive/activity-report/frames/ExecutiveActivityReportFrame.tsx
  packages/web/src/features/executive/activity-report/services/patchActivityChargedExecutive.tsx
  packages/web/src/features/executive/activity-report/services/putClubActivitiesChargedExecutive.tsx
  packages/web/src/features/executive/activity-report/services/useGetActivityClubChargeAvailableExecutives.tsx
  packages/web/src/utils/getChargedExecutiveContent.tsx
Labels: enhancement, front-end

#1349 refactor: simplify activity status query in ActivityRepository
  packages/api/src/feature/activity/repository/activity.repository.ts
Labels: back-end

#1350 Merge dev into main
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/web/src/features/clubs/components/ClubCard.tsx
Labels: release

#1362 1360 impl funding api for writing funding docs
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/activity/service/activity.public.service.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/api/src/feature/club/repository/club.semester-d.repository.ts
  packages/api/src/feature/club/service/club.public.service.ts
  packages/api/src/feature/funding/controller/funding.controller.ts
  packages/api/src/feature/funding/service/funding.service.ts
  packages/api/src/feature/user/model/student.summary.model.ts
  packages/interface/src/api/activity/type/activity.type.ts
  packages/interface/src/api/club/type/semester.type.ts
  packages/interface/src/api/funding/apiFnd007.ts
  packages/interface/src/api/funding/apiFnd008.ts
  packages/interface/src/common/enum/activity.enum.ts
  packages/web/src/constants/tableTagList.ts
  packages/web/src/features/activity-report/constants/activityReportProgress.ts
  packages/web/src/features/executive/activity-report/components/ExecutiveClubActivitiesTable.tsx
Labels: enhancement, back-end

#1368 1365 fix funding and activity model to add fields edited at and commented at
  packages/api/src/drizzle/schema/activity.schema.ts
  packages/api/src/drizzle/schema/funding.schema.ts
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/api/src/feature/funding/model/funding.model.ts
  packages/api/src/feature/funding/repository/funding.repository.ts
  packages/interface/src/api/activity/endpoint/apiAct002.ts
  packages/interface/src/api/activity/endpoint/apiAct005.ts
  packages/interface/src/api/activity/endpoint/apiAct019.ts
  packages/interface/src/api/funding/type/funding.type.ts
  packages/web/src/features/activity-report/_mock/activityReportList.ts
  packages/web/src/features/activity-report/_mock/mock.ts
  packages/web/src/features/activity-report/services/useGetActivityReport.tsx
Labels: back-end

#1371 refactor: update funding schema and related services to use activityDId instead of semesterId
  packages/api/src/drizzle/schema/funding.schema.ts
  packages/api/src/feature/activity/service/activity.public.service.ts
  packages/api/src/feature/funding/controller/funding.controller.ts
  packages/api/src/feature/funding/model/funding.model.ts
  packages/api/src/feature/funding/repository/funding.repository.ts
  packages/api/src/feature/funding/service/funding.service.ts
  packages/interface/src/api/activity/type/activity.type.ts
  packages/interface/src/api/funding/apiFnd006.ts
  packages/interface/src/api/funding/type/funding.type.ts
Labels: back-end

#1376 fix: add literal comment to approval
  packages/api/src/feature/activity/service/activity.service.ts
Labels: back-end

#1332 1331 connect apifnd002 apifnd004
  packages/api/src/feature/funding/service/funding.service.ts
  packages/web/src/app/manage-club/funding/[id]/page.tsx
  packages/web/src/features/manage-club/funding/components/FixtureEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/components/_atomic/NewFundingListTable.tsx
  packages/web/src/features/manage-club/funding/components/_atomic/PastFundingListTable.tsx
  packages/web/src/features/manage-club/funding/constants/fundingProgressStatus.ts
  packages/web/src/features/manage-club/funding/detail/components/BasicEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/components/FixtureEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/components/FundingInfoList.tsx
  packages/web/src/features/manage-club/funding/detail/components/NonCorpEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/components/OtherEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/components/TransportationEvidenceList.tsx
  packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
  packages/web/src/features/manage-club/funding/frames/FundingForm.tsx
  packages/web/src/features/manage-club/funding/frames/FundingInfoFrame.tsx
  packages/web/src/features/manage-club/funding/hooks/useCreateFunding.ts
  packages/web/src/features/manage-club/funding/hooks/useUpdateFunding.ts
  packages/web/src/features/manage-club/funding/services/useDeleteFunding.ts
  packages/web/src/utils/Date/getKSTDate.ts
Labels: front-end

#1369 connect apiFnd006
  packages/api/src/feature/funding/controller/funding.controller.ts
  packages/api/src/feature/funding/service/funding.service.ts
  packages/interface/src/api/funding/endpoint/apiFnd006.ts
  packages/web/src/app/manage-club/funding/page.tsx
  packages/web/src/constants/manageClubFunding.ts
  packages/web/src/features/manage-club/funding/components/PastFundingListSection.tsx
  packages/web/src/features/manage-club/funding/components/_atomic/PastFundingListTable.tsx
  packages/web/src/features/manage-club/funding/components/_atomic/PastSingleSemesterFundingListSection.tsx
  packages/web/src/features/manage-club/funding/hooks/useGetPastFundingList.ts
  packages/web/src/features/manage-club/funding/services/useDeleteFunding.ts
  packages/web/src/features/manage-club/funding/services/useGetTermFundingList.ts
Labels: front-end

#1381 feat: connect apiFnd005
  packages/interface/src/common/enum/funding.enum.ts
  packages/web/src/app/manage-club/funding/[id]/page.tsx
  packages/web/src/constants/manageClubFunding.ts
  packages/web/src/features/activity-report/constants/index.ts
  packages/web/src/features/activity-report/frames/ActivityReportMainFrame.tsx
  packages/web/src/features/manage-club/components/FundingTable.tsx
  packages/web/src/features/manage-club/frames/ActivityManageFrame.tsx
  packages/web/src/features/manage-club/funding/components/NewFundingListSection.tsx
  packages/web/src/features/manage-club/funding/components/PastFundingListSection.tsx
  packages/web/src/features/manage-club/funding/constants/fundingDeadlineEnumToString.ts
  packages/web/src/features/manage-club/funding/constants/fundingProgressStatus.ts
  packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
  packages/web/src/features/manage-club/funding/services/useGetFundingDeadline.ts
Labels: front-end

#1384 지원금 페이지에 지출 목적 api 연결
  .vscode/typescriptreact.code-snippets
  packages/web/src/common/components/FormController.tsx
  packages/web/src/features/activity-report/services/useGetActivityAvailable.ts
  packages/web/src/features/activity-report/services/useGetActivityParticipants.ts
  packages/web/src/features/manage-club/frames/ActivityManageFrame.tsx
  packages/web/src/features/manage-club/funding/components/NewFundingListSection.tsx
  packages/web/src/features/manage-club/funding/components/TransportEvidenceBlock.tsx
  packages/web/src/features/manage-club/funding/constants/index.ts
  packages/web/src/features/manage-club/funding/detail/components/FundingInfoList.tsx
  packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
  packages/web/src/features/manage-club/funding/frames/AddEvidenceFrame.tsx
  packages/web/src/features/manage-club/funding/frames/CreateFundingFrame.tsx
  packages/web/src/features/manage-club/funding/frames/EditFundingFrame.tsx
  packages/web/src/features/manage-club/funding/frames/FundingForm.tsx
  packages/web/src/features/manage-club/funding/frames/FundingInfoFrame.tsx
  packages/web/src/features/manage-club/funding/hooks/useCreateFunding.ts
  packages/web/src/features/manage-club/funding/hooks/useUpdateFunding.ts
  packages/web/src/features/manage-club/funding/services/useDeleteFunding.ts
  packages/web/src/features/manage-club/funding/services/useGetNewFundingList.ts
  packages/web/src/features/manage-club/funding/services/useGetTermFundingList.ts
  packages/web/src/features/manage-club/funding/services/usePostFunding.ts
  packages/web/src/features/manage-club/funding/services/usePutFunding.ts
  packages/web/src/features/manage-club/funding/types/funding.ts
Labels: front-end

#1390 update frontend getKSTDate logic
  packages/web/src/utils/Date/getKSTDate.ts
Labels: front-end

#1393 feat: update activity API response with commentedAt and editedAt fields
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/interface/src/api/activity/endpoint/apiAct024.ts
  packages/web/src/features/executive/activity-report/components/ExecutiveClubActivitiesTable.tsx
Labels: back-end

#1396 update check clubId logic in FudningDetailFrame
  packages/web/src/features/manage-club/funding/detail/frames/FundingDetailFrame.tsx
Labels: front-end

#1407 add a validation logic to funding expenditure date field
  packages/web/src/features/manage-club/funding/frames/FundingInfoFrame.tsx
  packages/web/src/utils/Date/getKSTDate.ts
Labels: front-end

#1405 fix: reset file input using ref to allow re-selection of the same file
  packages/web/src/common/components/FileUpload.tsx
Labels: front-end

#1412 Merge dev into main
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/funding/model/funding.model.ts
  packages/api/src/feature/funding/model/funding.summary.model.ts
  packages/interface/src/api/funding/type/funding.type.ts
  packages/web/src/features/manage-club/funding/hooks/useCreateFunding.ts
  packages/web/src/features/manage-club/funding/hooks/useUpdateFunding.ts
Labels: release
