Repository sparcs-kaist/clubs, pull requests merged in 2025-05, with the labels that each got.

#1562 [TU-119] division tag color 중복 사용 버그 해결
  packages/web/src/common/hooks/useGetDivisionType.ts
  packages/web/src/constants/tableTagList.ts
  packages/web/src/features/activity-report/components/executive/ChargedActivityModalTable.tsx
  packages/web/src/features/activity-report/components/executive/ExecutiveActivityClubTable.tsx
  packages/web/src/features/executive/funding/components/ChargedFundingModalTable.tsx
  packages/web/src/features/executive/funding/components/ExecutiveFundingClubTable.tsx
  packages/web/src/features/executive/register-member/components/RegisterMemberTable.tsx
  packages/web/src/features/manage-club/frames/ProfessorManageClubFrame/ClubInfoSection.tsx
  packages/web/src/features/my/components/MyClubProfTable.tsx
  packages/web/src/features/my/components/MyClubTable.tsx
  packages/web/src/features/my/components/MyMemberTable.tsx
  packages/web/src/types/clubdetail.types.ts
Labels: front-end

#1615 [TU-216] 활보 마감 기한 텍스트 표시 버그 수정
  packages/web/src/features/activity-report/constants/index.ts
Labels: bug, front-end

#1617 [TU-217] 활보 활동기간 모달 날짜 오류 수정
  packages/web/src/common/components/Forms/DateInput.tsx
  packages/web/src/features/activity-report/components/ActivityReportForm.tsx
  packages/web/src/features/activity-report/components/CurrentActivityReportTable.tsx
  packages/web/src/features/activity-report/components/PastActivityReportTable.tsx
  packages/web/src/features/activity-report/components/SelectParticipant.tsx
  packages/web/src/features/activity-report/components/professor/ProfessorActivityReportTable.tsx
  packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
  packages/web/src/features/activity-report/hooks/useCreateActivityReport.ts
  packages/web/src/features/activity-report/hooks/useUpdateActivityReport.ts
  packages/web/src/features/activity-report/services/useGetParticipants.ts
  packages/web/src/features/activity-report/types/activityReport.ts
  packages/web/src/features/register-club/components/activity-report/ActivityReportList.tsx
  packages/web/src/features/register-club/components/activity-report/CreateActivityReportModal.tsx
  packages/web/src/features/register-club/components/activity-report/EditActivityReportModal.tsx
  packages/web/src/features/register-club/components/activity-report/EditActivityTermModal.tsx
  packages/web/src/features/register-club/components/activity-report/_atomic/ActivityReportForm.tsx
  packages/web/src/features/register-club/components/activity-report/_atomic/ActivityTermRow.tsx
  packages/web/src/features/register-club/components/activity-report/_atomic/SelectActivityTerm.tsx
  packages/web/src/features/register-club/types/registerClub.ts
  packages/web/src/utils/Date/formatDate.ts
  packages/web/src/utils/Date/getKSTDate.ts
Labels: bug, front-end

#1618 [TU-220] Base Repository timezone for create
  packages/api/src/common/base/base.multi.repository.ts
  packages/api/src/common/base/base.repository.ts
  packages/api/src/common/base/base.single.repository.ts
Labels: bug, back-end

#1620 [TU-222] Club, Delegate 등 타 모듈 작업
  packages/api/src/common/base/base.repository.ts
  packages/api/src/drizzle/schema/club.schema.ts
  packages/api/src/feature/activity/activity.module.ts
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/model/activity-club-charged-executive.model.ts
  packages/api/src/feature/activity/repository/activity-club-charge-executive.repository.ts
  packages/api/src/feature/activity/repository/activity.activity-club-charged-executive.old.repository.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/api/src/feature/club/club.module.ts
  packages/api/src/feature/club/model/club-delegate.model.ts
  packages/api/src/feature/club/model/club-division-history.model.ts
  packages/api/src/feature/club/model/club-semester.model.ts
  packages/api/src/feature/club/model/club.model.ts
  packages/api/src/feature/club/repository-old/club.club-student-t.repository.ts
  packages/api/src/feature/club/repository/club-delegate-repository.ts
  packages/api/src/feature/club/repository/club-division-history.repository.ts
  packages/api/src/feature/club/repository/club-semester.repository.ts
  packages/api/src/feature/club/repository/club.repository.ts
  packages/api/src/feature/club/service/club.public.service.ts
  packages/api/src/feature/division/division.module.ts
  packages/api/src/feature/division/model/district.model.ts
  packages/api/src/feature/division/model/division.model.ts
  packages/api/src/feature/division/model/division.summary.model.ts
  packages/api/src/feature/division/model/old.division.model.ts
  packages/api/src/feature/division/repository/district.repository.ts
  packages/api/src/feature/division/repository/division.repository.ts
  packages/api/src/feature/division/repository/old.division.repository.ts
  packages/api/src/feature/division/service/division.public.service.ts
  packages/api/src/feature/division/service/division.service.ts
  packages/api/src/feature/semester/repository/semester.repository.ts
  packages/api/src/feature/user/model/old.student.model.ts
  packages/api/src/feature/user/model/professor.model.ts
  packages/api/src/feature/user/model/student.model.ts
  packages/api/src/feature/user/model/student.summary.model.ts
  packages/api/src/feature/user/repository/old.professor.repository.ts
  packages/api/src/feature/user/repository/old.student.repository.ts
  packages/api/src/feature/user/repository/professor.repository.ts
  packages/api/src/feature/user/repository/student.repository.ts
  packages/api/src/feature/user/service/user.public.service.ts
  packages/api/src/feature/user/service/user.service.ts
  packages/api/src/feature/user/user.module.ts
  packages/domain/src/activity/activity-club-charged-executive.ts
  packages/domain/src/division/district.ts
  packages/domain/src/division/division.ts
  packages/domain/src/user/professor.ts
  packages/domain/src/user/student.ts
Labels: new feature, back-end

#1622 [TU-223] Base Multi table find add isnull
  packages/api/src/common/base/base.multi.repository.ts
Labels: bug, back-end

#1624 [TU-213]
  packages/api/src/app.module.ts
  packages/api/src/feature/overview/controller/overview.controller.ts
  packages/api/src/feature/overview/overview.exception.ts
  packages/api/src/feature/overview/overview.module.ts
  packages/api/src/feature/overview/repository/overview.repository.ts
  packages/api/src/feature/overview/service/overview.service.ts
  packages/interface/src/api/overview/endpoint/apiOvv001.ts
  packages/interface/src/api/overview/endpoint/apiOvv002.ts
  packages/interface/src/api/overview/index.ts
Labels: new feature, back-end, interface

#1627 [TU-231] fix: notice sort bug
  packages/api/src/feature/notice/controller/notice.controller.ts
  packages/api/src/feature/notice/repository/notice.repository.ts
  packages/api/src/feature/notice/service/notice.service.ts
Labels: bug, back-end

#1628 [TU-232] 프론트엔드 mock 모드 에러 수정
  packages/web/src/features/activity-report/services/useGetActivityAvailable.ts
  packages/web/src/features/manage-club/funding/services/useGetFundingDeadline.ts
  packages/web/src/lib/_axios/axiosMockInterceptor.ts
  packages/web/src/lib/axios.ts
Labels: bug, front-end

#1625 [TU-17] 지원금 임시저장 기능
  packages/web/src/constants/localStorage.ts
  packages/web/src/features/manage-club/funding/constants/fundingDeadlineEnumToString.ts
  packages/web/src/features/manage-club/funding/frames/CreateFundingFrame.tsx
  packages/web/src/features/manage-club/funding/frames/EditFundingFrame.tsx
  packages/web/src/features/manage-club/funding/frames/FundingForm.tsx
  packages/web/src/utils/index.ts
Labels: front-end

#1550 [TU-118] 분과 학생회장 변경 (마이페이지) 기능 연결
  packages/interface/src/api/division/endpoint/apiDiv005.ts
  packages/web/src/constants/changeDivisionPresident.ts
  packages/web/src/features/my/components/ChangeDivisionPresidentModalContent.tsx
  packages/web/src/features/my/components/ChangeRepresentativeModalContent.tsx
  packages/web/src/features/my/components/MyChangeDivisionPresident.tsx
  packages/web/src/features/my/components/MyChangeRepresentative.tsx
  packages/web/src/features/my/frames/MyChangesFrame.tsx
  packages/web/src/features/my/services/_mock/mockMyDivisionPresidentRequest.ts
  packages/web/src/features/my/services/useGetMyDivisionPresidentRequest.ts
Labels: front-end

#1630 [TU-225] Add PatchNoteModal.tsx
  packages/web/src/common/components/Modal/PatchNoteModal.tsx
  packages/web/src/common/providers/AuthContext.tsx
  packages/web/src/constants/localStorage.ts
  packages/web/src/constants/patchNote.ts
Labels: front-end

#1611 [TU-192] notice last update time
  packages/api/src/feature/notice/service/notice.service.ts
  packages/interface/src/api/notice/endpoint/apiNtc001.ts
  packages/interface/src/api/notice/type/notice.type.ts
  packages/web/src/features/landing/frames/NoticeSectionFrame.tsx
  packages/web/src/features/notices/frames/NoticeListAndPaginationFrame.tsx
  packages/web/src/features/notices/services/_mock/mockupNoticeList.ts
Labels: new feature, front-end, back-end, interface

#1612 [TU-210] 집행부원 활보 조회 검색 로직 백으로 이전
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/interface/src/api/activity/endpoint/apiAct023.ts
  packages/web/package.json
  packages/web/src/common/components/SearchInput.tsx
  packages/web/src/features/activity-report/components/executive/ExecutiveActivityChargedTable.tsx
  packages/web/src/features/activity-report/components/executive/ExecutiveActivityClubTable.tsx
  packages/web/src/features/activity-report/frames/executive/ExecutiveActivityReportFrame.tsx
  packages/web/src/features/activity-report/services/executive/useGetExecutiveActivities.ts
  pnpm-lock.yaml
Labels: front-end, back-end
