Repository sparcs-kaist/clubs, pull requests merged in 2025-04, with the labels that each got.

#1552 [TU-101] 공지사항 Notice 엔티티 정의 및 레포지토리 작성
  packages/api/src/feature/notice/model/notice.model.ts
  packages/api/src/feature/notice/repository/notice.repository.ts
  packages/api/src/feature/notice/service/notice.service.ts
  packages/interface/src/api/notice/type/notice.type.ts
Labels: new feature, back-end

#1561 [TU-161] next js 취약점 대응 버전 업
  packages/web/package.json
  pnpm-lock.yaml
Labels: front-end

#1578 TU-176 fix timezone in db
  packages/api/src/common/util/decorators/time-decorator.ts
  packages/api/src/common/util/util.ts
  packages/api/src/feature/semester/model/semester.model.ts
  packages/interface/src/common/utils/field-operations.ts
Labels: back-end

#1580 TU-180
  packages/api/src/app.module.ts
  packages/api/src/feature/activity/activity.module.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/api/src/feature/club/club.module.ts
  packages/api/src/feature/club/service/club.service.ts
  packages/api/src/feature/registration/club-registration/club-registration.exception.ts
  packages/api/src/feature/registration/club-registration/club-registration.module.ts
  packages/api/src/feature/registration/club-registration/controller/club-registration.controller.ts
  packages/api/src/feature/registration/club-registration/service/club-registration.service.ts
  packages/api/src/feature/registration/controller/registration.controller.ts
  packages/api/src/feature/registration/dto/registration.dto.ts
  packages/api/src/feature/registration/member-registration/controller/member-registration.controller.ts
  packages/api/src/feature/registration/member-registration/member-registration.exception.ts
  packages/api/src/feature/registration/member-registration/member-registration.module.ts
  packages/api/src/feature/registration/member-registration/service/member-registration.service.ts
  packages/api/src/feature/registration/model/member.registration.model.ts
  packages/api/src/feature/registration/registration.module.ts
  packages/api/src/feature/registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/repository/member-registration.repository.ts
  packages/api/src/feature/registration/repository/registration.repository.ts
  packages/api/src/feature/registration/service/registration.public.service.ts
  packages/api/src/feature/registration/service/registration.service.ts
Labels: back-end, refactor

#1582 제발 아마 잘될거야
  .docker/dockerfile/api.Dockerfile
  .docker/dockerfile/web.bundle.stage.Dockerfile
  .github/workflows/ci.yml
  .gitignore
  .husky/pre-commit
  .vscode/settings.json
  package.json
  packages/api/eslint.config.mjs
  packages/api/package.json
  packages/api/tsconfig.json
  packages/domain/package.json
  packages/eslint-config/base.mjs
  packages/eslint-config/nest-js.mjs
  packages/eslint-config/next-js.mjs
  packages/eslint-config/package.json
  packages/eslint-config/rest-api.mjs
  packages/eslint-config/tsconfig.json
  packages/eslint-config/unused.ts
  packages/interface/eslint.config.mjs
  packages/interface/package.json
  packages/interface/src/open-api.ts
  packages/interface/tsconfig.json
  packages/typescript-config/base.json
  packages/typescript-config/nest-js.json
  packages/typescript-config/next-js.json
  packages/typescript-config/package.json
  packages/typescript-config/rest-api.json
  packages/web/.eslintrc.json
  packages/web/eslint.config.mjs
  packages/web/next.config.mjs
  packages/web/package.json
  packages/web/tsconfig.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo.json
Labels: new feature, front-end, back-end, interface, refactor

#1587 TU-181
  packages/api/src/app.module.ts
  packages/api/src/common/base/base.public.service.ts
  packages/api/src/common/repository/base.repository.ts
  packages/api/src/common/util/util.ts
  packages/api/src/feature/activity/activity.module.ts
  packages/api/src/feature/activity/controller/activity.activity-term.controller.ts
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/service/activity.activity-term.service.ts
  packages/api/src/feature/activity/service/activity.public.service.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/api/src/feature/club/club.module.ts
  packages/api/src/feature/club/controller/club.controller.ts
  packages/api/src/feature/club/delegate/delegate.module.ts
  packages/api/src/feature/club/delegate/delegate.service.ts
  packages/api/src/feature/club/repository/club.club-t.repository.ts
  packages/api/src/feature/club/repository/club.semester-d.repository.ts
  packages/api/src/feature/club/service/club.public.service.ts
  packages/api/src/feature/club/service/club.service.ts
  packages/api/src/feature/common-space/common-space.module.ts
  packages/api/src/feature/common-space/service/common-space.service.ts
  packages/api/src/feature/funding/funding.module.ts
  packages/api/src/feature/funding/service/funding.service.ts
  packages/api/src/feature/registration/registration.module.ts
  packages/api/src/feature/registration/service/registration.service.ts
  packages/api/src/feature/semester/model/activity.deadline.model.ts
  packages/api/src/feature/semester/model/activity.duration.model.ts
  packages/api/src/feature/semester/model/funding.deadline.model.ts
  packages/api/src/feature/semester/model/registration.deadline.model.ts
  packages/api/src/feature/semester/model/semester.model.ts
  packages/api/src/feature/semester/publicService/activity.deadline.public.service.ts
  packages/api/src/feature/semester/publicService/activity.duration.public.service.ts
  packages/api/src/feature/semester/publicService/funding.deadline.public.service.ts
  packages/api/src/feature/semester/publicService/registration.deadline.public.service.ts
  packages/api/src/feature/semester/publicService/semester.public.service.ts
  packages/api/src/feature/semester/semester.module.ts
  packages/api/src/feature/semester/service/semester.public.service.ts
  packages/api/src/feature/semester/service/semester.service.ts
Labels: back-end

#1588 Add semester domain
  packages/api/src/feature/club/repository/club.repository.ts
  packages/api/src/feature/club/service/club.public.service.ts
  packages/api/src/feature/funding/service/funding.service.ts
  packages/api/src/feature/semester/model/activity.deadline.model.ts
  packages/api/src/feature/semester/model/activity.duration.model.ts
  packages/api/src/feature/semester/model/funding.deadline.model.ts
  packages/api/src/feature/semester/model/registration.deadline.model.ts
  packages/api/src/feature/semester/model/semester.model.ts
  packages/domain/src/semester/activity-duration.ts
  packages/domain/src/semester/deadline.ts
  packages/domain/src/semester/semester.ts
  packages/interface/src/api/activity/type/activity.type.ts
  packages/interface/src/api/club/type/club.type.ts
  packages/interface/src/api/funding/endpoint/apiFnd007.ts
  packages/interface/src/api/registration/endpoint/apiReg026.ts
  packages/interface/src/api/registration/endpoint/apiReg027.ts
  packages/interface/src/api/registration/endpoint/apiReg028.ts
  packages/interface/src/api/semester/apiSem001.ts
  packages/interface/src/api/semester/type/activity.duration.type.ts
  packages/interface/src/api/semester/type/deadline.type.ts
  packages/interface/src/api/semester/type/semester.type.ts
  packages/interface/src/api/user/type/user.type.ts
Labels: documentation, interface

#1591 [TU-182] Base repository structure for single and multimodels
  packages/api/src/common/base/base.multi.repository.ts
  packages/api/src/common/base/base.public.service.ts
  packages/api/src/common/base/base.repository.ts
  packages/api/src/common/base/base.single.repository.ts
  packages/api/src/common/base/entity.model.ts
  packages/api/src/common/meta-keys.ts
  packages/api/src/common/model/entity.model.ts
  packages/api/src/common/repository/base.repository.ts
  packages/api/src/common/util/decorators/deprecated-model-field-decorator.ts
  packages/api/src/common/util/util.ts
  packages/api/src/drizzle/drizzle.module.ts
  packages/api/src/drizzle/drizzle.transaction-manager.ts
  packages/api/src/drizzle/schema/funding.schema.ts
  packages/api/src/drizzle/schema/registration.schema.ts
  packages/api/src/drizzle/schema/semester.schema.ts
  packages/api/src/feature/activity/activity.module.ts
  packages/api/src/feature/activity/model/activity.model.new.ts
  packages/api/src/feature/activity/repository/activity.new.repository.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/api/src/feature/division/model/district.model.ts
  packages/api/src/feature/division/model/division.model.ts
  packages/api/src/feature/division/model/division.summary.model.ts
  packages/api/src/feature/funding/funding.module.ts
  packages/api/src/feature/funding/model/funding.comment.model.ts
  packages/api/src/feature/funding/repository/funding.comment.repository.ts
  packages/api/src/feature/funding/service/funding.service.ts
  packages/api/src/feature/notice/model/notice.model.ts
  packages/api/src/feature/registration/model/member.registration.model.ts
  packages/api/src/feature/registration/repository/club-registration.repository.ts
  packages/api/src/feature/registration/repository/member-registration.repository.ts
  packages/api/src/feature/registration/service/registration.service.ts
  packages/api/src/feature/semester/model/activity.deadline.model.ts
  packages/api/src/feature/semester/model/activity.duration.model.ts
  packages/api/src/feature/semester/model/funding.deadline.model.ts
  packages/api/src/feature/semester/model/registration.deadline.model.ts
  packages/api/src/feature/semester/model/semester.model.ts
  packages/api/src/feature/semester/publicService/activity.deadline.public.service.ts
  packages/api/src/feature/semester/publicService/activity.duration.public.service.ts
  packages/api/src/feature/semester/publicService/funding.deadline.public.service.ts
  packages/api/src/feature/semester/publicService/registration.deadline.public.service.ts
  packages/api/src/feature/semester/publicService/semester.public.service.ts
  packages/api/src/feature/semester/repository/activity.deadline.repository.ts
  packages/api/src/feature/semester/repository/activity.duration.repository.ts
  packages/api/src/feature/semester/repository/funding.deadline.repository.ts
  packages/api/src/feature/semester/repository/registration.deadline.repository.ts
  packages/api/src/feature/semester/repository/semester.repository.ts
  packages/api/src/feature/semester/service/semester.service.ts
  packages/api/tsconfig.json
  packages/interface/src/api/activity/type/activity.type.ts
  pnpm-lock.yaml
Labels: back-end

#1590 Setup for jest
  packages/api/jest.config.ts
  packages/api/package.json
  packages/api/src/feature/activity/activity.controller.spec.ts
  packages/api/src/feature/meeting/meeting.gateway.spec.disabled.ts
  packages/api/tsconfig.spec.json
  pnpm-lock.yaml
Labels: back-end

#1593 [TU-187] feat: add articleId column to notice
  packages/api/src/drizzle/schema/notice.schema.ts
  packages/api/src/feature/notice/model/notice.model.ts
  packages/interface/src/api/notice/type/notice.type.ts
Labels: back-end

#1575 [TU-163] 로그인 헤더 수정
  packages/web/src/common/components/Header/_atomic/Login.tsx
  packages/web/src/common/components/MyMenu/index.tsx
  packages/web/src/common/components/NavTools/MobileNavMenu.tsx
  packages/web/src/i18n/messages/en.json
  packages/web/src/i18n/messages/ko.json
Labels: front-end

#1584 [TU-154] 지도교수 동아리 등록 상세페이지 api 중복 요청 해결
  packages/web/src/app/executive/register-club/[id]/page.tsx
  packages/web/src/app/manage-club/permanent/register-club/[id]/page.tsx
  packages/web/src/app/my/register-club/[id]/page.tsx
  packages/web/src/features/my/register-club/frames/ProfessorRegisterClubDetailButton.tsx
  packages/web/src/features/register-club/frames/MyRegisterClubDetailFrame.tsx
  packages/web/src/features/register-club/frames/RegisterClubDetailAuthFrame.tsx
  packages/web/src/features/register-club/frames/RegisterClubDetailFrame.tsx
Labels: front-end

#1574 [TU-107]
  packages/api/package.json
  packages/api/src/feature/notice/controller/notice.controller.ts
  packages/api/src/feature/notice/model/notice.model.ts
  packages/api/src/feature/notice/notice.module.ts
  packages/api/src/feature/notice/repository/notice.repository.ts
  packages/api/src/feature/notice/service/notice.service.ts
  packages/domain/src/notice/notice.ts
  packages/interface/src/api/notice/endpoint/apiNtc001.ts
  packages/interface/src/api/notice/type/notice.type.ts
  pnpm-lock.yaml
Labels: new feature, back-end

#1596 [TU-194]
  packages/api/src/common/base/base.repository.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/interface/src/api/activity/endpoint/apiAct004.ts
Labels: back-end

#1594 [TU-190] Club 도메인 모델 작성
  packages/api/src/feature/registration/model/member.registration.model.ts
  packages/domain/src/club/club-delegate-change-request.ts
  packages/domain/src/club/club-delegate.ts
  packages/domain/src/club/club-division-history.ts
  packages/domain/src/club/club-history.ts
  packages/domain/src/club/club-member.ts
  packages/domain/src/club/club.ts
  packages/domain/src/club/division.ts
  packages/domain/src/notice/notice.ts
  packages/domain/src/registration/member-registration.ts
  packages/domain/src/user/executive.ts
  packages/domain/src/user/professor.ts
  packages/domain/src/user/student.ts
  packages/eslint-config/base.mjs
  packages/eslint-config/custom_rules/zod-number-rules.mjs
  packages/eslint-config/tsconfig.json
  packages/interface/src/api/_example/_endpoints/apiTmp000.ts
  packages/interface/src/api/_example/endpoints/apiTmp000.ts
  packages/interface/src/api/activity-certificate/endpoint/apiAcf002.ts
  packages/interface/src/api/activity-certificate/endpoint/apiAcf005.ts
  packages/interface/src/api/activity-certificate/endpoint/apiAcf006.ts
  packages/interface/src/api/club/endpoint/apiClb013.ts
  packages/interface/src/api/club/type/club.type.ts
  packages/interface/src/api/common-space/endpoint/apiCms001.ts
  packages/interface/src/api/common-space/endpoint/apiCms002.ts
  packages/interface/src/api/common-space/endpoint/apiCms006.ts
  packages/interface/src/api/common-space/endpoint/apiCms007.ts
  packages/interface/src/api/file/type/file.type.ts
  packages/interface/src/api/funding/endpoint/apiFnd008.ts
  packages/interface/src/api/funding/endpoint/apiFnd009.ts
  packages/interface/src/api/funding/endpoint/apiFnd010.ts
  packages/interface/src/api/meeting/apiMee001.ts
  packages/interface/src/api/meeting/apiMee009.ts
  packages/interface/src/api/meeting/apiMee012.ts
  packages/interface/src/api/notice/endpoint/apiNtc001.ts
  packages/interface/src/api/notice/type/notice.type.ts
  packages/interface/src/api/promotional-printing/endpoint/apiPrt001.ts
  packages/interface/src/api/promotional-printing/endpoint/apiPrt002.ts
  packages/interface/src/api/promotional-printing/endpoint/apiPrt003.ts
  packages/interface/src/api/registration/endpoint/apiReg001.ts
  packages/interface/src/api/registration/endpoint/apiReg002.ts
  packages/interface/src/api/registration/endpoint/apiReg003.ts
  packages/interface/src/api/registration/endpoint/apiReg006.ts
  packages/interface/src/api/registration/endpoint/apiReg007.ts
  packages/interface/src/api/registration/endpoint/apiReg008.ts
  packages/interface/src/api/registration/endpoint/apiReg013.ts
  packages/interface/src/api/registration/endpoint/apiReg018.ts
  packages/interface/src/api/registration/endpoint/apiReg020.ts
  packages/interface/src/api/rental/endpoint/apiRnt001.ts
  packages/interface/src/api/rental/endpoint/apiRnt003.ts
  packages/interface/src/api/semester/apiSem001.ts
  packages/interface/src/api/user/endpoint/apiUsr001.ts
  packages/interface/src/api/user/type/user.type.ts
  packages/interface/src/common/api.ts
Labels: back-end, interface

#1598 [TU-189] AS base repository
  packages/api/src/common/base/base.multi.repository.ts
  packages/api/src/common/base/base.single.repository.ts
  packages/api/src/feature/funding/repository/funding.comment.repository.ts
  packages/api/src/feature/notice/repository/notice.repository.ts
  packages/api/src/feature/registration/repository/member-registration.repository.ts
  packages/api/src/feature/semester/repository/activity.deadline.repository.ts
  packages/api/src/feature/semester/repository/activity.duration.repository.ts
  packages/api/src/feature/semester/repository/funding.deadline.repository.ts
  packages/api/src/feature/semester/repository/registration.deadline.repository.ts
  packages/api/src/feature/semester/repository/semester.repository.ts
Labels: bug, back-end

#1595 [TU-121] Activity 리팩토링
  packages/api/src/drizzle/schema/activity.schema.ts
  packages/api/src/feature/activity/repository/activity.new.repository.ts
  packages/domain/src/activity/activity-comment.ts
  packages/domain/src/activity/activity.ts
  packages/domain/src/common/id.ts
  packages/domain/src/common/utils.ts
  packages/domain/src/file/file.ts
  packages/interface/src/api/activity/endpoint/apiAct024.ts
  packages/web/package.json
  packages/web/src/features/activity-report/components/ActivityReportStatusSection.tsx
  packages/web/src/features/activity-report/constants/activityReportProgress.ts
  packages/web/src/features/activity-report/services/useGetActivityReport.ts
  packages/web/src/features/activity-report/types/table.ts
  packages/web/src/features/activity-report/utils/sortActivities.ts
  packages/web/src/features/register-club/components/activity-report/EditActivityReportModal.tsx
  packages/web/src/features/register-club/components/activity-report/PastActivityReportModal.tsx
  packages/web/src/features/register-club/types/registerClub.ts
  pnpm-lock.yaml
Labels: back-end, interface

#1600 [TU-198] Club Repository with Base
  packages/api/src/drizzle/schema/club.schema.ts
  packages/api/src/feature/activity/activity.module.ts
  packages/api/src/feature/activity/repository/activity.repository.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/api/src/feature/club/club.exception.ts
  packages/api/src/feature/club/club.module.ts
  packages/api/src/feature/club/delegate/club.club-delegate-d.repository.ts
  packages/api/src/feature/club/delegate/delegate.service.ts
  packages/api/src/feature/club/model/club-delegate.model.ts
  packages/api/src/feature/club/model/club-division-history.model.ts
  packages/api/src/feature/club/model/club-old.model.ts
  packages/api/src/feature/club/model/club-semester.model.ts
  packages/api/src/feature/club/model/club.model.ts
  packages/api/src/feature/club/model/club.summary.model.ts
  packages/api/src/feature/club/repository-old/club-old.repository.ts
  packages/api/src/feature/club/repository-old/club.club-room-t.repository.ts
  packages/api/src/feature/club/repository-old/club.club-student-t.repository.ts
  packages/api/src/feature/club/repository-old/club.club-t.repository.ts
  packages/api/src/feature/club/repository-old/club.division-permanent-club-d.repository.ts
  packages/api/src/feature/club/repository-old/club.get-student-club-brief.ts
  packages/api/src/feature/club/repository-old/club.put-student-club-brief.ts
  packages/api/src/feature/club/repository/club-delegate-repository.ts
  packages/api/src/feature/club/repository/club-division-history.repository.ts
  packages/api/src/feature/club/repository/club-semester.repository.ts
  packages/api/src/feature/club/repository/club.repository.ts
  packages/api/src/feature/club/service/club.public.service.ts
  packages/api/src/feature/club/service/club.service.ts
  packages/api/src/feature/common-space/common-space.module.ts
  packages/api/src/feature/common-space/service/common-space.service.ts
  packages/api/src/feature/funding/repository/funding.repository.ts
  packages/api/src/feature/registration/repository/club-registration.repository.ts
  packages/api/src/feature/rental/repository/rental.rental-order.repository.ts
  packages/api/src/feature/rental/repository/rental.rental-service.repository.ts
  packages/api/src/feature/user/service/user.service.ts
  packages/api/src/feature/user/user.module.ts
  packages/domain/src/club/club-delegate.ts
  packages/domain/src/club/club-member.ts
  packages/domain/src/club/club-semester.ts
  packages/interface/src/api/activity/endpoint/apiAct001.ts
  packages/interface/src/api/common-space/endpoint/apiCms002.ts
  packages/web/src/features/activity-report/services/useGetActivityReportProvisional.ts
  packages/web/src/features/meeting/constants/meetingTemplate.ts
  packages/web/src/features/notices/services/_mock/mockupNoticeList.ts
  packages/web/src/features/register-club/services/_mocks/mockMyRegistration.ts
  packages/web/src/i18n/messages/en.json
Labels: new feature, back-end

#1601 [TU-197] Normalize Act 009
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/api/src/feature/club/controller/club.controller.ts
  packages/api/src/feature/club/service/club.service.ts
  packages/api/src/feature/semester/publicService/activity.duration.public.service.ts
  packages/interface/src/api/activity/endpoint/apiAct006.ts
  packages/web/src/features/activity-report/constants/index.ts
Labels: bug, back-end

#1597 [TU-195] 활보 deadline 관련 로직 수정
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/api/src/feature/semester/controller/semester.controller.ts
  packages/api/src/feature/semester/publicService/activity.deadline.public.service.ts
  packages/api/src/feature/semester/service/semester.service.ts
  packages/interface/src/api/activity/endpoint/apiAct016.ts
  packages/interface/src/api/activity/endpoint/apiAct018.ts
  packages/web/src/app/manage-club/activity-report/[id]/edit/page.tsx
  packages/web/src/app/manage-club/activity-report/create/page.tsx
  packages/web/src/common/frames/NotActivityReportCreatePeriod.tsx
  packages/web/src/features/activity-report/frames/ActivityReportDetailFrame.tsx
  packages/web/src/features/activity-report/frames/ActivityReportMainFrame.tsx
Labels: front-end, back-end

#1602 [TU-203] `src/**/*` import 차단
  packages/api/src/drizzle/drizzle.config.ts
  packages/api/src/feature/activity-certificate/activity-certificate.module.ts
  packages/api/src/feature/activity-certificate/repository/activity-certificate.repository.ts
  packages/api/src/feature/activity/activity.module.ts
  packages/api/src/feature/auth/auth.module.ts
  packages/api/src/feature/auth/repository/auth.repository.ts
  packages/api/src/feature/club/club.module.ts
  packages/api/src/feature/club/delegate/club.club-delegate-d.repository.ts
  packages/api/src/feature/club/repository-old/club-old.repository.ts
  packages/api/src/feature/club/repository-old/club.club-room-t.repository.ts
  packages/api/src/feature/club/repository-old/club.club-student-t.repository.ts
  packages/api/src/feature/club/repository-old/club.club-t.repository.ts
  packages/api/src/feature/club/repository-old/club.division-permanent-club-d.repository.ts
  packages/api/src/feature/file/file.module.ts
  packages/api/src/feature/file/repository/file.repository.ts
  packages/api/src/feature/funding/funding.module.ts
  packages/api/src/feature/meeting/entity/content/content.module.ts
  packages/api/src/feature/meeting/entity/content/content.repository.ts
  packages/api/src/feature/meeting/entity/entity.module.ts
  packages/api/src/feature/meeting/entity/entity.repository.ts
  packages/api/src/feature/meeting/entity/vote/vote.module.ts
  packages/api/src/feature/meeting/entity/vote/vote.repository.ts
  packages/api/src/feature/meeting/meeting.module.ts
  packages/api/src/feature/meeting/meeting.repository.ts
  packages/api/src/feature/notice/notice.module.ts
  packages/api/src/feature/promotional-printing/promotional-printing.module.ts
  packages/api/src/feature/promotional-printing/repository/promotional-printing-order-size.repository.ts
  packages/api/src/feature/promotional-printing/repository/promotional-printing-order.repository.ts
  packages/api/src/feature/rental/rental.module.ts
  packages/api/src/feature/rental/repository/rental.rental-object.repository.ts
  packages/api/src/feature/rental/repository/rental.rental-order.repository.ts
  packages/api/src/feature/rental/repository/rental.rental-service.repository.ts
  packages/api/src/feature/semester/semester.module.ts
  packages/api/src/feature/user/privacy-policy/privacy-policy.module.ts
  packages/api/src/feature/user/privacy-policy/privacy-policy.repository.ts
  packages/api/src/feature/user/repository/user.endpoint.repository.ts
  packages/api/src/feature/user/repository/user.repository.ts
  packages/api/src/feature/user/user.module.ts
  packages/eslint-config/base.mjs
  packages/eslint-config/custom_rules/eslint-plugin-zod-coerce.mjs
  packages/eslint-config/nest-js.mjs
Labels: back-end

#1603 [TU-204] 집행부의 이전 2학기 지원금 데이터 조회 요청 처리
  packages/api/src/feature/funding/service/funding.service.ts
Labels: back-end

#1605 [TU-196] pnpm run test 스켈레톤 코드 작성
  package.json
  packages/api/package.json
  packages/api/src/env.ts
  packages/api/test/app.e2e-spec.ts
  packages/api/test/jest-e2e.json
  pnpm-lock.yaml
Labels: back-end

#1599 [TU-170] 활보 신청내역 페이지에 학기별 조회 기능 추가
  packages/api/src/feature/activity/controller/activity.controller.ts
  packages/api/src/feature/activity/service/activity.service.ts
  packages/interface/src/api/activity/endpoint/apiAct024.ts
  packages/web/src/app/executive/activity-report/club/[id]/page.tsx
  packages/web/src/features/activity-report/components/executive/ExecutiveClubActivitiesTable.tsx
  packages/web/src/features/activity-report/components/executive/ExecutiveCurrentActivityReportSection.tsx
  packages/web/src/features/activity-report/components/executive/ExecutivePastActivityReportSection.tsx
  packages/web/src/features/activity-report/frames/executive/ExecutiveActivityReportClubFrame.tsx
  packages/web/src/features/activity-report/hooks/useGetExecutiveClubActivities.ts
  packages/web/src/features/activity-report/services/executive/useGetExecutiveActivities.ts
  packages/web/src/features/activity-report/services/executive/useGetExecutiveClubActivities.ts
  packages/web/src/features/activity-report/services/executive/useGetExecutiveClubActivitiesForDuration.ts
Labels: front-end

#1608 [TU-206] 바로 터보레포 정상화! OUT!! 역시 정상화는 김 현 수
  packages/api/package.json
  packages/api/src/main.ts
  packages/api/tsconfig.json
  turbo.json
Labels: back-end

#1610 [TU-209] 담당자 변경 기능에 검색기능 추가 및 요청 완료 후 체크박스 해제 기능 추가
  packages/web/src/common/components/Forms/SearchSelect.tsx
  packages/web/src/features/activity-report/components/executive/ChargedChangeActivityModalContent.tsx
  packages/web/src/features/activity-report/components/executive/ChargedChangeClubModalContent.tsx
  packages/web/src/features/activity-report/components/executive/ExecutiveCurrentActivityReportSection.tsx
  packages/web/src/features/activity-report/frames/executive/ExecutiveActivityReportFrame.tsx
Labels: front-end

#1609 TU-167 "move to activity report page" button and "link copy" button to PastActivityReportModal
  packages/web/src/features/register-club/components/activity-report/PastActivityReportModal.tsx
Labels: front-end

#1554 [TU-135] Add excel download button
  packages/web/package.json
  packages/web/src/features/manage-club/members/frames/AllMemberListFrame.tsx
  packages/web/src/features/manage-club/members/hooks/useDownloadMembers.ts
  packages/web/src/features/manage-club/members/services/useGetClubMembers.ts
  packages/web/src/utils/downloadExcel.ts
  pnpm-lock.yaml
Labels: front-end
